lib/core/console.js
I've used `_` as a convention for the unused index; any thoughts for/against it?
=> console: Swap out forEach for $.each

lib/modules/usernameHider.js
=> usernameHider: Fix module name

lib/modules/neverEndingReddit.js
Fixes this bug [\(reddit\)](https://www.reddit.com/r/RESissues/comments/2qtkus/bugneverending_reddit_page_2_starting_way_down/)
Amendment to #1909
=> Stop NER progressIndicator from getting pushed below the sidebar

lib/modules/neverEndingReddit.js
You can usually see this on pages when you've set the number of links displayed to 10.
=> neverEndingReddit: Ensure that right border of NERPageMarker appears

README.md
Last one for a long time i promise
=> Update readme to reflect gulp changes

lib/modules/sourceSnudown.js
=> sourceSnudown: unescape &gt; &lt; &amp;

Opera/browsersupport-opera.js, lib/core/console.js, lib/modules/commentTools.js, lib/modules/keyboardNav.js, lib/modules/styleTweaks.js
Just because we aren't actually using the newly created `[]`.
=> Convert [] to Array.prototype for clarity

lib/modules/commentTools.js
Suggested in [1756 comments](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/1756#issuecomment-69371463) (and previously suggested somewhere).
=> Options for commentTools keyboard shortcuts

lib/core/migrate.js, lib/core/utils.js, lib/modules/RESTips.js, lib/modules/bitcointip.js, lib/modules/commentTools.js, lib/modules/filteReddit.js, lib/modules/keyboardNav.js, lib/modules/notifications.js, lib/modules/styleTweaks.js, lib/modules/uppersAndDowners.js
Resolves #1510 
Before: 143 KB, after: 45 KB (fresh install)
=> [WIP] RESUtils: save only option values, not their descriptions, etc.

lib/core/template.js, lib/core/utils.js, lib/modules/RESTips.js, lib/modules/betteReddit.js, lib/modules/commandLine.js, lib/modules/commentPreview.js, lib/modules/commentTools.js, lib/modules/filteReddit.js, lib/modules/hideChildComments.js, lib/modules/hover.js, lib/modules/keyboardNav.js, lib/modules/noParticipation.js, lib/modules/notifications.js, lib/modules/saveComments.js, lib/modules/searchHelper.js, lib/modules/showImages.js, lib/modules/showParent.js, lib/modules/singleClick.js, lib/modules/styleTweaks.js, lib/modules/subredditInfo.js, lib/modules/userHighlight.js, lib/modules/userTagger.js, lib/modules/usernameHider.js
There is definitely more that I could have changed, but I tried to be conservative in some areas.
=> More linting

lib/modules/saveComments.js, lib/modules/spamButton.js, lib/modules/userTagger.js
Fixes #1929
I think this is everything those comments were missing.
=> Add rts button, save-RES button, and vote handlers to newly loaded comments

XPI/lib/main.js
=> Load new tabs in foreground based on browser preference

lib/modules/subredditManager.js
https://www.reddit.com/r/RESissues/comments/2spz5y/bug_trying_to_sort_subreddits_az_doesnt_work/
=> Subreddit shortcut A-Z/Z-A button doesn't sort

lib/modules/nightmode.css
=> Nightmode policy pages

lib/modules/usernameHider.js
Fixes [this bug (reddit).](https://www.reddit.com/r/RESissues/comments/2tk25t/bug_username_hider_peraccountdisplaytext_displays/#!settings/contribute)
I'm not sure if these were omitted on purpose - is there a situation where these links don't point to your profile?
=> usernameHider: add missing attribute selectors

lib/modules/betteReddit.js
Reddit has rolled out its own version of unread counts
=> Fix betteReddit option description

lib/reddit_enhancement_suite.user.js
As these variables are already declared in other files, these declarations should be unnecessary.
=> res.user: Remove unnecessary var declarations

lib/modules/accountSwitcher.js
=> Account Switcher - show gold, options to not show karma/gold, refactoring

Chrome/manifest.json, Opera/includes/loader.js, OperaBlink/manifest.json, RES.safariextension/Info.plist, XPI/lib/main.js, lib/core/migrate.js, lib/core/templates.html, lib/modules/betteReddit.js, lib/modules/submitHelper.js
=> rebased #1877 (submitHelper)

lib/modules/upload.js
=> Uploader does not work on /submit

lib/modules/hosts/flickr.js
Resolves [an issue from reddit.](https://www.reddit.com/r/Enhancement/comments/2r4fuy/correct_flickr_settings_for_expando/)
Also, checking for `media_url` avoids creating an expando when this would occur:
Picture by: undefined @ Flickr
Loading of image undefined failed. Click to view directly
=> Flickr fixes

lib/modules/hosts/fiveHundredPx.js
See here: http://www.reddit.com/r/foxes/comments/2upplj/blep/
=> drscdn.500px.org not included in 500px expando support

lib/modules/subredditInfo.js
https://www.reddit.com/r/Enhancement/comments/2upqky/feature_request_hover_info_for_trending_subreddits/
=> Show subreddit info hover on trending subreddits

README.md, gulpfile.js, package.json
to add new modules to browser manifests
=> gulp add-module --file newModule.js 

lib/core/options.js
Nothing is being hidden in the closure, as everything is being attached to `RESUtils.options.table`.
=> options: Remove redundant function scope

lib/core/res.css, lib/modules/dashboard.js, lib/modules/neverEndingReddit.js, lib/modules/nightmode.css, lib/modules/settingsNavigation.js
Resolves #2015 
The play button might be like 0.5px off, but I'm not sure if we can get it any better than that.
=> More batch icons

lib/modules/subredditManager.js
https://www.reddit.com/r/Enhancement/comments/2w1vnz/feature_request_allow_uppercase_and_lowercase/
=> Allow lowercase text in subreddit manager shortcuts

lib/modules/nightmode.css
Make infobar/jump to content legible/more visible
=> Night mode tweaks

OperaBlink/background.js, OperaBlink/manifest.json, lib/modules/showImages.js
Looking through #1352's commits:
Removed sites that are gone - already done
Minor refactoring - included
Pastebin support - it appears that we'll be able to use the embed now (instead of raw text), so I'm working on it
JSFiddle support - will be in a future fix-up PR (or never, since it doesn't appear to play nice with https)
Fixed permissions - some already done, the rest in this PR
=> #1352 fixed up / rebased (without expandos)

lib/core/utils.js, lib/modules/neverEndingReddit.js
=> Better NER pause button positioning

lib/modules/hosts/gfycat.js
=> The option to prefer RES support for gfycat "gifs"

lib/modules/quickMessage.js
This fixes an issue where your username would get added to the "from" dropdown twice - once immediately and once when we received a response from reddit.
=> quickMessage.getValidSendFrom minor refactoring

lib/modules/accountSwitcher.js
Fixes some edge cases with the account switcher menu:
- No more weirdness when hovering from the menu to the alien
- Menu properly closes after opening the accounts settings page
=> Fix account switcher overlay toggle

lib/modules/subredditManager.js
https://www.reddit.com/r/Enhancement/comments/2xnkn2/is_there_a_way_to_keep_your_subreddit_shortcuts/
also a few other old requests
=> option to use the same set of shortcuts across all accounts

lib/core/utils.js
RES leaks. https://www.reddit.com/r/RESissues/comments/2y5ta2/bug_night_mode_and_reddit_toolbar_make_some/
=> Don't run modules on reddit.com/tb/ (toolbar) pages

lib/core/utils.js
I fixed the bug showing wrong age of certain accounts. Also added a little bit of documentation to explain logic for new code.
=> Fixed user age calculator on userhover

lib/modules/nightmode.css
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1994
The filler text is also visible now in the text fields. Hope this is good; I've included some before and after pictures.
Before
After
=> Nightmode UI Fixes

lib/modules/hosts/fiveHundredPx.js
=> drscdn.500px URLs

lib/modules/hideChildComments.js
=> Show number of child comments in "show child comments"

lib/core/res.css, lib/modules/filteReddit.js, lib/modules/settingsConsole.js
The custom filters branch seems to be ready to roll.
I do still need to write up some kind of guide for them though
Still need to:
=> Create interface for creating complex custom filters

lib/modules/commentNavigator.js, lib/modules/nightmode.css
=> Use triangle icon for commentNav buttons

lib/modules/commandLine.js
=> Hide command line error when showing a valid tip

lib/modules/keyboardNav.js
=> explain scrollStyle option values

lib/core/res.css
Although the current gear is somewhat iconic, so maybe it wouldn't be a good idea to replace it.
=> Replace gear icon with Batch gear icon

lib/modules/nightMode.js
hopefully this works cross browser/OS
=> nightmode toggle moon/sun instead of on/off

lib/modules/filteReddit.js
Looks like there was an issue already created (#1831).
=> Allow subreddit filtering everywhere

lib/modules/keyboardNav.js
=> mediaBrowseMode: remember state

lib/modules/commentTools.js
=> Always create the macro default group, even if there are no macros

Chrome/background.js, Chrome/manifest.json, Opera/browsersupport-opera.js, Opera/includes/loader.js, Opera/index.html, OperaBlink/background.js, OperaBlink/manifest.json, RES.safariextension/Info.plist, RES.safariextension/background-safari.html, RES.safariextension/browsersupport-safari.js, XPI/data/browsersupport-firefox.js, XPI/lib/main.js, lib/modules/hosts/twitter.js, lib/modules/showImages.js, lib/modules/styleTweaks.js
This needs testing ([links](https://www.reddit.com/domain/twitter.com)) in Safari, but I suspect it'll work.
=> Move twitter support into its own siteModule

lib/core/init.js, lib/core/res.css, lib/core/utils.js, lib/modules/betteReddit.js, lib/modules/nightMode.js, lib/modules/showImages.js, lib/modules/styleTweaks.js
and an option to turn it off, of course
closes #1804
=> highlight nsfw buttons

lib/modules/usernameHider.js
So friending yourself won't cause your anonymous username to have no background.
Also makes some existing CSS redundant.
=> usernameHider: inherit background-color, border-radius, and padding

lib/modules/context.js
See: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1903
=> Make defaultContext setting apply to profile pages.

lib/modules/accountSwitcher.js
Transparency vs security-by-obscurity?  Discuss.
=> add password recovery and "no protection" link/warning to account switcher

Chrome/background.js, OperaBlink/background.js, RES.safariextension/background-safari.html, XPI/lib/main.js, lib/modules/troubleshooter.js
fixes orangered misfiring read/unread at the wrong account
=> Prevent multicast between incognito and normal tabs

lib/core/templates.html, lib/core/utils.js, lib/modules/quickMessage.js, lib/modules/userTagger.js
Fixes #2150, fixes #2087, fixes #2071, fixes #1953, fixes #1952.
Dropdown box is disabled if there are no choices:
Should the "last selected" sendAs be per-user?
Should we host the shield icon instead of referring to reddit's spritesheet?
=> Various quickMessage improvements

lib/core/res.css, lib/modules/announcements.js, lib/modules/menu.js
Fixes #2155.
Whenever the "!" is added on page load, it will flash a few times (pretty non-intrusively):
However, if the user hasn't cleared it for 3 days, it will get a little more intrusive (and it won't stop):
=> Announcement badge pizzazz

lib/modules/presets.js
=> preset is one word

lib/modules/subredditInfo.js
=> who needs watchforelement? not us.

lib/modules/settingsConsole.js
=> focus search on console open

README.md
=> Add nightly builds to readme

lib/core/migrate.js, lib/modules/quickMessage.js
=> quickMessage: open from the "send message" link on user pages

lib/modules/commandLine.js, lib/modules/menu.js
Implements #1875 in both ways mentioned.
=> #1875 -- Command line launches from menu and from gear icon click

lib/core/init.js, lib/core/utils.js, lib/modules/commentTools.js, lib/modules/filteReddit.js, lib/modules/newCommentCount.js, lib/modules/quickMessage.js, lib/modules/searchHelper.js, lib/modules/userTagger.js, lib/modules/usernameHider.js
Some lint fixes added as well.
=> utils: Compile regexes into RESUtils.regexes

lib/modules/hosts/onedrive.js
I've fixed a video playback issue with OneDrive, by reverting to the default video player.
I've also added support for audio playback.
=> OneDrive Playback issue, Audio support

lib/modules/hosts/clyp.js, lib/modules/hosts/giphy.js, lib/modules/hosts/imgur.js, lib/modules/hosts/raddit.js, lib/modules/showImages.js
Fixes an issue from [reddit](https://www.reddit.com/r/RESissues/comments/31wa85/bug_widescreen_youtube_videos_in_comments/) (iframe aspect ratio).
Also fixes an issue that has been haunting me for a long time: when you have a bunch of expandos in a comment, all of the video ones would get removed (specificially: all of the video expandos above a giphy, radd.it or imgur expando).
[](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/1593#discussion_r17503641)
=> Some expando fixes

lib/modules/commandLine.js, lib/modules/commentTools.js, lib/modules/settingsConsole.js
=> Fix dependent options

lib/modules/voteEnhancements.js
=> Link to the controversial indicator reddit pref from the RES option

lib/modules/settingsConsole.js
=> Don't hide the save button for disabled modules

lib/modules/noParticipation.js
As pointed out [here](https://www.reddit.com/r/RESissues/comments/33qwe7/bug/)
=> Change wording on noParticipation

lib/modules/quickMessage.js
=> quickMessage: load templates asynchronously

lib/modules/userTagger.js
=> userTagger: properly reset the state of the "ignored" toggle

lib/modules/styleTweaks.js
=> Option to sentence-case or Title Cast post titles

XPI/data/browsersupport-firefox.js
~~Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/3b128b19f0181a39a79d0f52a8d44d08f9238bb7#commitcomment-11031916~~
Fixed by c6c080644d80d5ce834d596d3dd9a6aebc71ee43, but we might as well not make `transactions` global.
=> RESLoadResourceAsText: fix Firefox callbacks

Chrome/background.js, Opera/index.html, OperaBlink/background.js, RES.safariextension/background-safari.html, lib/core/templates.html, lib/core/utils.js, lib/modules/hosts/imgur.js, lib/modules/showImages.js
gallery single-image posts will load
check for gifv if no extension given
refactored siteModules.imgur into a lot of deferreds.
added RESUtils.deferred.map and .deferred.collection
=> Some imgur fixups

README.md
Code Climate gives an informative display of the complexity and duplication in our code so we can identify problem areas easier.
=> README: Add Code Climate badge

lib/core/utils.js, lib/modules/about.js, lib/modules/accountSwitcher.js, lib/modules/betteReddit.js, lib/modules/customToggles.js, lib/modules/filteReddit.js, lib/modules/floater.js, lib/modules/hover.js, lib/modules/keyboardNav.js, lib/modules/menu.js, lib/modules/nightMode.js, lib/modules/selectedEntry.js, lib/modules/settingsConsole.js, lib/modules/showKarma.js
=> Make various lint cleanup and Exception -> Error fixes

lib/modules/hosts/imgur.js
too many mislabelled .jpgs are out in the wild thanks to RES
=> support i.stack.imgur.com and .yahoo.imgur images, hit API for .jpg's

lib/modules/betteReddit.js, lib/modules/keyboardNav.js, lib/modules/selectedEntry.js, lib/modules/spamButton.js, lib/modules/userTagger.js, lib/modules/voteEnhancements.js
=> Fix saving posts/comments with keyboard nav

lib/modules/hosts/futurism.js, lib/modules/showImages.js
to reflect the new domain, thanks!  please let me know if I did anything wrong...
=> changed futurism.co to futurism.com

lib/modules/nightmode.css
=> Makes NSFW stamp red in nightmode

lib/modules/nightMode.js, lib/modules/presets.js, lib/modules/troubleshooter.js
One-button to turn off all modules except a nice subset
=> RES Lite preset

lib/core/utils.js
This should fix up the bugs mentioned. Pinging @andytuba to make sure.
=> utils: Fix deferred.collection

lib/modules/selectedEntry.js
=> Keyboard nav "next/prev post" does not skip filtered posts

lib/core/migrate.js
Unrelated to the issue I just opened.
=> Some migration fixes

lib/modules/quickMessage.js
=> quickMessage: Fix case when fields.from is null/undef

lib/core/utils.js, lib/modules/neverEndingReddit.js
At least don't break the search page before properly taking care of #2242
=> Never Ending Reddit quits without a #siteTable

lib/core/migrate.js
also fix setting the latest options version
=> Migrate default macros into settings

lib/modules/showImages.js
When this is released, it will make obsolete http://github.com/reddit/reddit/commit/0a2d360 from http://github.com/reddit/reddit/pull/1332
fixes #2271
=> prevent RES expando button from triggering reddit expando toggle

lib/core/res.css, lib/core/templates.html
=> gussy settings console up a little

lib/modules/commentTools.js
...and properly set the limit when editing self posts.
Fixes #2274.
=> commentTools: max length of selftext is always 40000

lib/core/res.css, lib/modules/hover.js, lib/modules/userInfo.js
Fixes #2281 and a few other things.
=> Reset popup dimensions after hide

.travis.yml, lib/browsersupport.js, lib/core/init.js, lib/core/storage.js, lib/core/utils.js, lib/modules/RESTips.js, lib/modules/accountSwitcher.js, lib/modules/filteReddit.js, lib/modules/hosts/deviantart.js, lib/modules/hosts/fitbamob.js, lib/modules/hosts/imgur.js, lib/modules/hosts/onedrive.js, lib/modules/hover.js, lib/modules/keyboardNav.js, lib/modules/onboarding.js, lib/modules/selectedEntry.js, lib/modules/spoilerTags.js, lib/modules/stylesheet.js, lib/modules/troubleshooter.js
Most of these are simple ones like adding semicolons and converting double quotes to single quotes.
=> Fix various JSHint errors

lib/modules/nightMode.js
Hopefully addresses problems in #2279 at some point, but until I figure out the problem I'll keep fixing some minor issues.
=> Improve night mode

lib/modules/commentPreview.js
=> Don't run commentPreview on automod config page

lib/core/res.css, lib/core/templates.html, lib/modules/commentPreview.js, lib/modules/menu.js, lib/modules/nightmode.css, lib/modules/orangered.js, lib/modules/settingsConsole.js
Fixes #1993 (although it was already partially fixed).
=> Minor UI/UX improvements

lib/core/utils.js, lib/modules/keyboardNav.js, lib/modules/selectedEntry.js, lib/modules/subredditInfo.js, lib/modules/userTagger.js
Fixes #2243
Anything that includes 'linklist' now needs to explicitly include 'search'
Includes `RESUtils.thing(elementInsideThing)` which provides `.thing`, `.entry`, and getter methods for various elements in a thing
Might also fix a problem with /r/{{subreddit}}/wiki/submit whichI think @hermithome mentioned
=> SelectedEntry, KeyboardNav support for new search layout

lib/core/res.css, lib/core/utils.js, lib/modules/settingsConsole.js, lib/modules/showImages.js
https://www.reddit.com/r/RESissues/comments/3btl2l/bug_showviewimagestab_should_prevent_the_view/
=> showViewImagesTab=false should prevent tab from rendering

lib/modules/searchHelper.js
https://www.reddit.com/r/Enhancement/comments/3bswno/can_res_add_featurelegacy_search_into_search/
=> Optionally add ?feature=legacy_search to search forms

lib/core/res.css
Almost exactly the same at 100% resolution:
And significantly less terrible at high res:
=> Nicer-looking outline on gear icon

Chrome/manifest.json, Opera/includes/loader.js, OperaBlink/manifest.json, RES.safariextension/Info.plist, XPI/lib/main.js, lib/modules/messageMenu.js, lib/modules/quickMessage.js
Dropdown menu on envelope button with links to various parts of inbox
=> Message menu

Chrome/manifest.json, Opera/includes/loader.js, OperaBlink/manifest.json, RES.safariextension/Info.plist, XPI/lib/main.js, lib/modules/hosts/oddshot.js
Implementation of [oddshot.tv](http://oddshot.tv). [Requested](http://redd.it/3bv6qw) on /r/Enhancement. Fixes #2321. Videos can be tested [here](https://www.reddit.com/domain/oddshot.tv).
Will detect if the browser supports `video/mp4` and will reject if that's not the case.
=> Oddshot.tv Support

lib/modules/styleTweaks.js
This change removes the FOUC of the right header by moving the `navTop` CSS initialization to `beforeLoad`.
=> Fix navTop FOUC

lib/modules/searchHelper.js
Only display it on legacy_search.
Fixes #2246
=> Don't display show/hide button on new search

lib/modules/betteReddit.js
It's been swell, except for all the bug reports where people thought RES owned the toolbar.
http://github.com/reddit/reddit/commit/38928f110d1a
await toolbar removal on June 26
=> [HOLD] remove toolbarfix

lib/core/res.css, lib/core/templates.html
moved bitpay up to free options, 2 col layout,
=> Donation page layout fixups

lib/modules/bitcointip.js, lib/modules/saveComments.js, lib/modules/singleClick.js, lib/modules/sourceSnudown.js, lib/modules/subredditManager.js, lib/modules/userTagger.js, lib/vendor/guiders.js
Just to make them consistent across the project.
=> Standardize javascript:void 0 and mute JSHint warnings

lib/modules/userHighlight.js
Even with three of us looking it over, we still missed something -.-
(hopefully only one thing...)
=> Minor lint fix

lib/core/templates.html, lib/modules/neverEndingReddit.js
Using RES on latest master: https://www.allthefoxes.me/img/32-LdzcIQMx.png
No RES: https://www.allthefoxes.me/img/32-RoHR3TdE.png
=> New search is not showing the "more" button under subreddit list

lib/modules/subredditManager.js
<Githue> latest dev: when clicking +shortcut, I get this error...
<Githue> subredditManager.js:1409 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
=> Another minor lint fix

lib/core/utils.js
Removed the performance simplification, so all of these are just style changes.
=> utils: Simplify pageType calls

Chrome/background.js, OperaBlink/background.js, RES.safariextension/background-safari.html, XPI/lib/main.js
We really need to consolidate the Chrome and OperaBlink files...
=> Lint browser-specific files

lib/modules/searchHelper.js
Remove redundant options: searchSubredditByDefault, and addSubmitButton.
Also makes toggleSearchOptions and its sibling dependant on
legacySearch.
=> Update for searchHelper settings

lib/modules/logoLink.js
Added option to link the reddit logo to the RES dashboard as discussed in issue #2362
=> Added RES Dashboard option to redditLogoDestination setting.

lib/modules/commandLine.js
Doesn't conflict with the existing `/r/` for going to subreddits.
[via reddit](https://www.reddit.com/r/Enhancement/comments/3ecggb/feature_request_sort_by_rising_from_command_box/)
=> commandLine: support for navigating to the rising sort page

lib/modules/nightmode.css
Tested in both legacy_search and the new search page.
=> Get nightmode.css up to date

changelog.txt, lib/modules/noParticipation.js
https://www.reddit.com/r/Enhancement/comments/3e96h4/feature_request_turn_np_links_that_exit_a_post/
=> escapeNP bugged for <a href="/...">

lib/core/res.css
#2372, forgot to change change the class in one spot.
=> Sub buttons: fixed a selector that I missed

lib/modules/hosts/youtube.js
=> Youtube regex fix

lib/core/res.css, lib/modules/settingsConsole.js
Also changed em units to px to avoid jitter during animation.
The max height CSS transition was causing the delay, so I've swapped it with jQuery's slide() animation.
=> Remove delay on settings console accordian menu

lib/modules/styleTweaks.js
=> Fix the userbar sometimes taking up 100% of the header height

lib/modules/hosts/oddshot.js
- Fixed strange "onedrive" typo
- Updated AWS URL, old URL no longer supported.
- Updated RegEx to work better with Oddshot's new URL format.
=> Fixed oddshot.tv expando

lib/core/utils.js, lib/modules/filteReddit.js, lib/modules/neverEndingReddit.js
Added/refactored a bunch of "get attributes/elements of this post/comment" to RESUtils.thing
filteReddit uses RESUtils.thing().
Needs testing for syntax errors, works on new search layout, still works on old search layout and other post listings, and will work on inbox comments.  Probably need to regression test other things that use changed RESUtils.thing methods.
=> filteReddit support for new search layout

lib/modules/nightmode.css
=> Nightmode settings console and notifications

lib/core/migrate.js, lib/core/options.js
and remove duplicates for people who've been getting them in dev branch since https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/01923f7d49309e3f7392f7e5a5e501bf6afdddd1
=> avoid duplicate notification types

lib/core/res.css, lib/modules/notifications.js
As per: http://caniuse.com/#feat=css-animation and https://developer.mozilla.org/en-US/docs/Web/CSS/animation#Browser_compatibility
Mainly for Android browser and Safari.
=> Notifications: cross browser compatibility for animation

lib/modules/userTagger.js
... because #2418 was moved to 4.6.2.
=> UserTagger hotfix: correct toggleButton position

lib/core/res.css, lib/modules/hover.js
- Stops dropdown lists from going outside of the viewport.
- Corrects height of toggleButtons in dropdowns.
- Corrects cursor for top-right gearIcon in Firefox.
Before / after:
=> Correct positioning for dropdown lists

lib/modules/subredditInfo.js, lib/modules/subredditTagger.js
Fix for issue #2219. It also fixes the subreddit hover, which was closely related.
=> Fix for issue #2219 on GitHub

lib/modules/dashboard.js, lib/modules/newCommentCount.js, lib/modules/notifications.js
- Added icons for subscribe/unsubscribe/renew buttons (using Github's idea of audio icon)
- Changed notifications, added unsubscribe button ([requested here](https://www.reddit.com/r/Enhancement/comments/3kptpd/feature_request_a_little_trash_can_or_x_next_to_x/))
- Improved readability of Dashboard table
- Fixed the broken 'Open on Reddit' button and changed the wording
Icon makes the button more recognizable, easy to find:
Unsubscribe from within notification:
Dashboard:
=> Usability & style changes for thread subscriptions

lib/core/res.css, lib/modules/dashboard.js, lib/modules/tableTools.js, lib/modules/userTagger.js
* sorting tagged users by username now works even after re-sorting other columns.
* added 'Page' before pagination buttons, and fixed their positioning.
* tableTools no longer affects dashboard. Was requiring an extra click to sort by username.
=> Fixed username sorting of tagged users in dashboard

lib/core/res.css
Primarily for /r/naut, but will help against subreddits that apply a general style to all buttons. Also fixes the height of #moduleOptionsSave button for Firefox. \**shakes fist*\*
Not related to toggle buttons.
=> Fortify button elements in settings console

lib/core/res.css, lib/modules/commentBoxes.css, lib/modules/commentTools.js
Here's my detailed analysis of this issue and how I found a solution: http://output.jsbin.com/wemonaw/
As an extra safeguard for the future, it will be important to be very careful with using floats inside form.usertext. Try to avoid using floats when they're not needed, for example div.commentingAs only needs to be floated when span.RESMacroWrappingSpan is present, so I've added an if statement to check for the latter.
This PR is the closest I can get to a permanent solution to this long-standing problem, it will be interesting to see how it holds up in  the wild.
Fixes #2359
=> Comment box falling below sidebar

lib/modules/newCommentCount.js, lib/modules/nightmode.css
Subscribe button looks more like a button in threads and notifications.
=> Buttony appearance for subscribe to thread button

lib/core/res.css
Found these when I opened res.css in Visual Studio Code.
=> Minor CSS cleanup

lib/core/utils.js, lib/modules/showImages.js
Keep the expando button visible at the top of the page while scrolling through an expando.
http://i.imgur.com/FPNLCzD.gifv
related to #849
=> Sticky expando button

lib/core/utils.js, lib/modules/showImages.js
Reverts honestbleeps/Reddit-Enhancement-Suite#2376
doesn't seem to work at first glance.. nevermind, will debug later
=> Revert "Sticky expando button"

lib/modules/styleTweaks.js, lib/modules/userTagger.js
=> Fix voteWeight and hiding archived posts' arrows

lib/modules/newCommentCount.js
The button wasn't getting thread ID correctly. `subObj.id` > `commentID`
=> Fix unsubscribing from threads via notification button 

lib/modules/filteReddit.js, lib/modules/searchHelper.js
searchHelper would try to remove an element from the search form in the sidebar (instead of just on the search page), throwing an error.
filteReddit would try to filter comments by title, domain, etc. on profile pages, also throwing an error.
=> Fix a few error cases

.jscsrc, .jshintrc
Did not realize this wasn't part of the build. This'll be nice to enforce.
=> jscs: Enforce tab indentation

OperaBlink/background.js
Missing sendResponse in delete cookies broke account switcher.
=> Bring in changes from Chrome/background.js.

lib/core/templates.html
Two hover cards can be present at the same time: user & subreddit.
The IDs weren't being referenced from anywhere else, so no other changes needed.
=> Replace non-unique IDs with classes

lib/modules/commentTools.js
Fixes this bug: https://www.reddit.com/r/RESissues/comments/3qzvs4/bug_minor_problem_with_the_reply_to_macro/
=> {{reply_to}} macro correctly handles comment editing

.jscsrc, .jshintrc
Reverts honestbleeps/Reddit-Enhancement-Suite#2407
=> Revert "jscs: Enforce tab indentation"

lib/core/utils.js, lib/modules/stylesheet.js
also includes some interesting changes to .pageType that hopefully won't break everything
closes #2474
=> don't load stylesheet module in certain pages

lib/modules/subredditManager.js
All scrollbars should be hidden in the subreddit header area
=> Hide subreddit header scrollbars

.gitignore, Chrome/manifest.json, Opera/config.xml, OperaBlink/manifest.json, RES.safariextension/Info.plist, XPI/package.json, gulpfile.js, lib/core/init.js, lib/core/utils.js, lib/modules/onboarding.js, lib/reddit_enhancement_suite.user.js, package.json
Update each browse manifest and in-code version number with values from package.json
**FYI** `npm install` after pulling -- this adds new dependencies.
=> gulp build generates browser manifests

XPI/index.js
Mostly converting `let` to `const` for unchanged variables.
=> XPI/index: Fix ESLint issues

lib/css/modules/_nightMode.scss, lib/css/modules/_styleTweaks.scss
Same as #2550, but for master instead of 4.6.
=> SCSS Nightmode fixes, improvements, additions

XPI/package.json
It'd be a lot nicer if our extension file wasn't some randomly-generated string of characters, but I'm not sure how the add-on upgrade process works. Thoughts @honestbleeps @andytuba?
=> XPI: Rename Firefox extension

Firefox/data/browsersupport-firefox.js, lib/browsersupport.js, lib/core/storage.js, node/lib/browsersupport-node.js
=> browsersupport: Remove unneeded localStorageTest

Gruntfile.js, lib/core/utils.js, tests/qunit/test-insertAfter.js, tests/qunit/test-niceDateDiff.js, tests/qunit/tests.html
Closes #2583 
Adds QUnit tests to travis
Adds QUnit tests for niceDateDiff, skipping a failing test:
>> niceDateDiff: Mar 31 2014 - May 01 2015 = 1 year, 1 month and 1 day
>> Message: RESUtils.niceDateDiff(new Date("Mar 31 2014"), new Date("May 01 2015"));
>> Actual: "1 year and 1 month"
>> Expected: "1 year, 1 month and 1 day"
=> Fix "days ago" in Jan/Feb

README.md, gulpfile.babel.js, package.json, tests/qunit/tests.html
Part of #2587.
Currently the tests fail, but they seem to pass with cb9368f48347501cd3359a741b7b624909063cdd and 2b0e7a7ade47ea74dd62afca3d5da0553f0d40db.
(I haven't actually tried cherry-picking those commits, but it works when I cut out the `console.error` by hand)
=> Run QUnit tests in Gulp

README.md
Ref: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2544#issuecomment-169068859
=> Add Python and node.js version to readme

lib/modules/subredditManager.js
=> Set max dimensions on shortcut dropdown, for users with many links

lib/css/modules/_subredditManager.scss
=> subredditManager: Set max dimensions on shortcut dropdown

README.md
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2614
=> Update Safari instructions

lib/core/utils.js
=> utils: Remove unused elementUnderMouse function

lib/core/utils.js
Fixes [this issue](https://www.reddit.com/r/RESissues/comments/427wrx/bug_when_i_go_into_my_savedreddit_page_res_inline/) (from reddit).
=> Fix showImages on NER pages on /u/me/saved

lib/core/templates.html, lib/modules/neverEndingReddit.js
=> Fix NER on the modlog and comments listings

lib/core/utils.js
=> commaDelimitedString: handle invalid locales

lib/modules/keyboardNav.js
=> keyboardNav: enable voting and followPermalinkNewTab in the inbox

lib/modules/dashboard.js
=> Fix search widget #2625

lib/modules/selectedEntry.js
=> selectedEntry: allow selecting things on message permalink pages

lib/core/utils.js
Fixes #2621.
At some point we should bring back the `modqueue` pageType from #1858, maybe.
=> Exclude modqueue and similar pages from subredditAbout pageType

lib/modules/newCommentCount.js
Fixed new comment count is still broken in Japanese interface.
function processCommentCounts(ele) was fixed by #2139, but need same fix for function updateCommentCount(mycomment) too.
=> Fixed new comment count is still broken (#2139)

lib/modules/messageMenu.js, lib/modules/newCommentCount.js, lib/modules/nightMode.js, lib/modules/pageNavigator.js, lib/modules/selectedEntry.js, lib/modules/spoilerTags.js, lib/modules/subredditTagger.js, lib/modules/userbarHider.js
Is my wording for cleanComments fair?
=> Clarify module descriptions and options

lib/modules/commentBoxes.css
Like it was in 4.5.4
Fixes https://www.reddit.com/r/RESissues/comments/42exc9/bug_comments_cover_sidebar/
=> Fix comments passing through sidebar.

lib/modules/nightmode.css
Announcement: https://www.reddit.com/r/modnews/comments/42o2i0/moderators_subreddit_rules_now_available_for_all/
=> Nightmode: support new report form and rules page

.codeclimate.yml
=> codeclimate: Enable ratings

README.md
Hopefully this gives the channel more visibility.
=> README: Add IRC badge

lib/core/migrate.js, lib/modules/stylesheet.js
Expand loadSubredditStylesheets into also loading external urls. Deprecate r/resupdates.
=> External stylesheets

lib/core/res.css, lib/core/utils.js, lib/modules/nightmode.css, lib/modules/userTagger.js
Enabled colors when disabled
Closes #2696
reverseToggleButton disabled
reverseToggleButton enabled
reverseToggleButton disabled nightmode
reverseToggleButton enable nightmode
toggleButton disabled
toggleButton enabled
toggleButton disabled nightmode
toggleButton enabled nightmode
=> .reverseToggleButton for user tagger toggle

lib/core/res.css, lib/core/templates.html, lib/core/utils.js, lib/modules/announcements.js, lib/modules/notifications.js, lib/reddit_enhancement_suite.user.js
Show a notification for new /r/RESAnnouncements post once every several days, if storage is working
Don't show ! or notification for older posts
Red ! shows all the time for "recent posts" even if storage isn't working
Regression-checked ! with pizzazz
=> Announcement notifications

lib/css/modules/_commentPreview.scss, lib/modules/commentPreview.js, lib/modules/commentTools.js
=> commentTools: ban messages are limited to 1000 characters

lib/core/utils.js
=> Fix RESUtils.thing::getScore() for posts

lib/core/res.css, lib/modules/presets.js, lib/modules/settingsConsole.js
=> Confirm presets

Chrome/background.js, Firefox/index.js, Safari/background.js, lib/browsersupport.js, lib/core/migrate.js, lib/modules/announcements.js, lib/modules/backupAndRestore.js, lib/modules/commandLine.js, lib/modules/commentTools.js, lib/modules/filteReddit.js, lib/modules/saveComments.js, lib/modules/spamButton.js, lib/modules/subredditTagger.js, lib/modules/troubleshooter.js, lib/modules/userbarHider.js, node/lib/browsersupport-node.js
Depends on #2684; [diff](https://github.com/erikdesjardins/Reddit-Enhancement-Suite/compare/promise-to-async...native-storage).
Fixes #1893, closes #1840.
=> Use indexedDB in Firefox

lib/modules/showImages.js
=> Fix conserveMemory on 4.6.1

lib/modules/showImages.js
Fixes #2605
Should be able to cherry-pick this to 4.6.1 without conflict.
=> Fix handling of image hrefs - images in albums link to the album

lib/core/res.css, lib/core/templates.html, lib/modules/about.js, lib/modules/settingsConsole.js, lib/reddit_enhancement_suite.user.js
=> Obviouser onboarding

lib/core/alert.js, lib/core/utils.js, lib/modules/RESTips.js, lib/modules/accountSwitcher.js, lib/modules/commandLine.js, lib/modules/commentNavigator.js, lib/modules/commentTools.js, lib/modules/dashboard.js, lib/modules/hover.js, lib/modules/keyboardNav.js, lib/modules/notifications.js, lib/modules/quickMessage.js, lib/modules/settingsConsole.js, lib/modules/showImages.js, lib/modules/styleTweaks.js, lib/modules/submitIssue.js, lib/modules/subredditManager.js
The mods can have nice things again. I'll brace for educating the userbase "yes, it might disappear in some subreddits, here are some other methods."
=> Remove protective styling on subreddit style checkbox

lib/core/utils.js, lib/modules/keyboardNav.js, lib/modules/selectedEntry.js, lib/modules/showImages.js
=> Improve selecting/scrolling on keyboard move up/down

lib/core/__tests__/niceDateDiff.js, lib/core/utils.js
I added the Oxford comma as well; hope nobody minds.
=> niceDateDiff: Fix edge case for day diff

lib/modules/neverEndingReddit.js
=> fix NER event name: neverEndingLoaded -> neverEndingLoad

CHANGELOG.md, firefox/index.js, lib/core/utils.js, lib/modules/announcements.js, lib/modules/keyboardNav.js, lib/modules/selectedEntry.js, lib/modules/showImages.js
[master...release/4.6.1](https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/release/4.6.1)
See also #2743, #2775 
#2780 also belongs with these commits.
=> Port the final 4.6.1 changes back to master

lib/modules/hosts/iloopit.js
Cross platform embed/iframe for iloopit.net instead of mp4 video. 
Also this PR removes additional ajax to get video info.
=> Embed iframe for 'iloopit'

lib/modules/hosts/example.js, lib/modules/showImages.js
=> Fix image captions (#2534 rebased)

lib/modules/pageNavigator.js
=> Change alt attribute to title (#2707 rebased)

lib/modules/userHighlight.js
=> highlightFirstComments doesn't work when loading... (#2742 rebased)

lib/css/modules/_nightMode.scss
=> self-serve nightmode style issues (#2746 rebased)

lib/core/__tests__/niceDateDiff.js
Tested with several different system time zones (BST, UTC, a bunch in America, Moscow).
Please let me know if I should do anything different in the code, the commit, PR or whatever.  I tried to follow the style guidelines, but I may have missed something.
And do feel free to close the issue, ignore the pull request, fix it yourself in some other way, copypaste the code or whatever makes your life easier. 
Kind regards,
Victor
=> Fixes #2832.  Test failed depending on the system time zone.

chrome/background.js, chrome/browsersupport-chrome.js, chrome/manifest.json
Should have been part of #2689, but I didn't do enough research.
Turns out the `storage` and `unlimitedStorage` permissions [don't cause warnings](https://developer.chrome.com/extensions/permission_warnings#nowarning).
Edit: tested this with another published extension, it definitely doesn't seem to cause warnings
=> Use chrome.storage in Chrome

lib/css/modules/_betteReddit.scss, lib/modules/betteReddit.js
Fixes an issue [from reddit.](https://www.reddit.com/r/Enhancement/comments/33ocbr/feature_request_add_random_to_the_comments)
=> Optionally show hidden sort options on all pages (random, Q&A, etc.)

.travis.yml, README.md
27% coverage seems a *little* high, I'll look into that.
=> Add badge for Coveralls

node/lib/browsersupport-node.js
This makes the output considerably saner:
https://travis-ci.org/erikdesjardins/Reddit-Enhancement-Suite/jobs/120093921#L1361
vs
https://travis-ci.org/erikdesjardins/Reddit-Enhancement-Suite/jobs/120102374#L1235
=> Fixup node mock storage

chrome/manifest.json, firefox/index.js, lib/modules/hosts/pixpit.js, lib/modules/userHighlight.js, node/files.json, safari/Info.plist
See https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2729 for original
=> Port pixpit mediaHost to new format

Chrome/manifest.json, Firefox/index.js, Safari/Info.plist, lib/modules/hosts/pixpit.js, node/files.json
Adding expando support for [PixPit](http://www.pixpit.com). Test it [here](https://www.reddit.com/r/funny/comments/3zofv6/king_of_hover_hands/)
=> PixPit Expando Support

chrome/manifest.json, firefox/index.js, lib/modules/hosts/xkcd.js, node/files.json, safari/Info.plist
Captions currently don't work, although this looks to be fixed by https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2534/files
=> Add XKCD media host (via oembed)

lib/modules/commentTools.js, lib/modules/userTagger.js, lib/modules/usernameHider.js
=> Clone username from userbar for "commenting as"

Chrome/manifest.json, Firefox/index.js, Safari/Info.plist, lib/modules/hosts/spotify.js, node/files.json
For #2737 
First time contributing, let me know if I'm not doing something wrong.
=> Spotify expando

chrome/manifest.json, firefox/index.js, lib/modules/hosts/derpibooru.js, node/files.json, safari/Info.plist
=> Rebase and update #2531: Derpibooru expandos

lib/core/utils.js, lib/modules/betteReddit.js, lib/modules/saveComments.js, lib/modules/showImages.js, lib/modules/sourceSnudown.js, lib/modules/userHighlight.js, lib/modules/userTagger.js, lib/modules/voteEnhancements.js
=> Rebase and update #2618: forEachChunked dynamic

.travis.yml, package.json
This works locally. Let's see if it works on Travis.
ref: https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2842#issuecomment-204521444
=> Fix per-line coverage reporting

lib/modules/dashboard.js
add a delay on sortable widget to prevent unwanted drags
=> add a delay on sortable widget

chrome/manifest.json, firefox/index.js, lib/core/utils.js, lib/modules/xPostLinks.js, node/files.json, safari/Info.plist
Closes #2425.
Test links:
https://www.reddit.com/r/ideasfortheadmins/comments/4dh34o/xpost_from_rmodhelp_git_hooks_for_subreddit_css/
https://www.reddit.com/search?q=xpost&sort=relevance&t=all
=> Update and rebase #2425: xpost links

chrome/manifest.json, firefox/index.js, lib/modules/hosts/reddituploads.js, node/files.json, safari/Info.plist
https://www.reddit.com/r/Enhancement/comments/4drsku/feature_request_add_ireddituploadscom/
=> reddituploads host

lib/modules/keyboardNav.js
=> Fix keynav followLink on comments pages

chrome/manifest.json, firefox/index.js, lib/core/utils.js, lib/modules/hover.js, lib/modules/messageMenu.js, lib/modules/multiredditNavbar.js, node/files.json, safari/Info.plist
=> Multireddit quicklinks menu

lib/css/modules/_betteReddit.scss, lib/modules/betteReddit.js
=> Rebase #2646: Truncate Long Links

lib/css/modules/_showImages.scss, lib/modules/hosts/wikipedia.js
* Remove Wikipedia attribution
* make in-comment text info look better (ie. Wikipedia expando's)
fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2860 https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2859
Screeny of wiki text-expando in comments with new styles:
=> Improve wikipedia expando

lib/modules/showImages.js
Hopefully resolves https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1586
So far as i can tell, getting the spotlight links in the `findAllImages` selector seems to get everything working as expected.
=> Make expando's work in homepage spotlight area

lib/css/modules/_subredditManager.scss, lib/css/modules/_userTagger.scss, lib/css/modules/_userbarHider.scss, lib/modules/subredditManager.js, lib/modules/userbarHider.js
=> Rebase #2602: CSS cleanup for subreddit themes

lib/modules/tableTools.js
=> Rebase #2592: TableTools goes funky when headers contain extra markdown

lib/core/templates.html, lib/css/modules/_showImages.scss, lib/modules/showImages.js
Fixes issues arising from 7f59bef5cff569bc3a8542475b95615d15891000 (bring back clickable link on videos)
Implements #2884
=> Video advanced: Fixes, made controls optional

lib/vendor/favico.js
=> vendor: Update favico.js to v0.3.10

README.md
Hopefully the README isn't too cluttered.
=> README: Add AppVeyor badge

lib/modules/betteReddit.js
=> Rebase #2569: Fix pinHeader

lib/css/modules/_showImages.scss, lib/modules/showImages.js, lib/templates/videoAdvanced.mustache
The circle appears on progress bar `hover`:
=> Video advanced: Set current time from progress bar

chrome/environment.js, edge/environment.js, webpack.config.babel.js
=> Fix Edge permissions

lib/modules/neverEndingReddit.js
=> Rebase #2429: Update to NER notifications

lib/modules/userTagger.js
=> userTagger: fix the "ignored" icon on the dashboard

lib/css/res.scss, lib/utils/alert.js
=> Rebase #2545: Keep alert messages on-screen and scrollable

lib/modules/betteReddit.js, lib/modules/commentPreview.js, lib/modules/commentTools.js, lib/modules/filteReddit.js, lib/modules/keyboardNav.js, lib/modules/selectedEntry.js, lib/modules/showImages.js, lib/modules/spamButton.js, lib/modules/voteEnhancements.js, lib/modules/xPostLinks.js, lib/utils/location.js
Closes #1871. Fixes #1855.
Most of #1871 has already been implemented in #2916.
=> Resurrect #1871: add `modqueue` pageType

lib/css/_zindex.scss, lib/css/res.scss
=> Adjust z-indexes

lib/modules/context.js
=> context: run on modqueue-like pages

chrome/manifest.json, edge/manifest.json, lib/modules/hosts/codepen.js, safari/Info.plist
=> CodePen expandos

lib/css/modules/_betteReddit.scss, lib/modules/betteReddit.js
=> betteReddit: option to show the comment collapse button in the inbox

lib/modules/newCommentCount.js
=> Add .res-hasNewComments to .thing containing .newComments

lib/modules/logoLink.js
=> Rebase #2468: custom destinations for reddit logo link

lib/css/res.scss
=> Rebase #2567: Menu CSS more sturdy, consistent across themes

lib/css/_zindex.scss, lib/css/modules/_pageNavigator.scss, lib/modules/pageNavigator.js, lib/templates/showLinkTitle.mustache
Closes #2750.
From #2750:
Closes #2736
Closes #1821
Fixes #849
=> Rebase #2750: New feature: Show Link Title

lib/css/modules/_userTagger.scss, lib/modules/userTagger.js, lib/templates/userTaggerDialog.mustache
=> Rebase #2418: UserTagger: fix a number of layout/styling issues

lib/modules/betteReddit.js
https://www.reddit.com/r/Enhancement/comments/4j1zm8/what_does_the_donoctrlf_do_actually_im_not_quite/d33o90i
=> no ctrl-f "comments" links in sidebar

lib/utils/array.js, lib/utils/async.js, lib/utils/index.js
=> Add utils for deferring a function call to the next frame and debouncing

lib/modules/betteReddit.js
http://www.reddit.com/r/enhancement/comments/4j1zm8/what_does_the_donoctrlf_do_actually_im_not_quite_sure_what_the_description_is_saying/d33hcxh?context=2
=> DoNoCtrlF description readability tweak

lib/css/res.scss, lib/modules/betteReddit.js, lib/modules/hosts/raddit.js, lib/modules/keyboardNav.js, lib/modules/showImages.js, lib/templates/tabMenuLink.mustache, lib/utils/createElement.js
This uses the `li.selected` class to indicate that a tab / filter is active; another class may be more appropriate.
=> ShowImages: Rewrite custom image filter

lib/css/modules/_showImages.scss, lib/modules/showImages.js, lib/templates/mediaControls.mustache
=> ShowImages MediaControls: Style clean-up

lib/css/modules/_showImages.scss, lib/modules/showImages.js
=> ShowImages: Restore expando classes

lib/modules/hosts/youtube.js
=> Rebase #2975: Adds Youtube parameters more dynamically

lib/utils/localization.js
=> L10n: check html[lang] against list of reddit's supported languages

lib/modules/xPostLinks.js
=> xPostLinks: add `x-posted from` before the `to /r/actual_subreddit`

lib/modules/hosts/imgur.js
=> Imgur: display gifv inside albums

lib/modules/newCommentCount.js
=> Rebase #2647: Show Subscribe Button

lib/modules/commentDepth.js
=> Rebase #2514: Adds commentDepth module

lib/modules/showImages.js
=> Use document listeners for makeMediaZoomable and makeMediaMovable

lib/modules/filteReddit.js, lib/modules/keyboardNav.js, lib/modules/selectedEntry.js, lib/modules/subredditInfo.js, lib/modules/userTagger.js
=> Command line subreddit filtering

lib/modules/hosts/simplecove.js
Adding simplecove functionality to RES
=> Creating simplecove.js

lib/modules/commentDepth.js, lib/modules/context.js
unless the user really wants it
closes #3030
=> Don't set comment depth on permalinks

lib/css/modules/_showImages.scss, lib/modules/showImages.js, lib/templates/expando.mustache, lib/templates/image.mustache
It will right-align if there's free space on the left side; if not, then left-align.
=> showImages: Align expando-box when exceeding width of body

lib/core/init.js, lib/modules/commentDepth.js, lib/modules/commentTools.js, lib/modules/newCommentCount.js, lib/modules/quickMessage.js, lib/modules/searchHelper.js, lib/modules/showImages.js, lib/modules/subredditInfo.js, lib/modules/usernameHider.js, lib/utils/Thing.js, lib/utils/index.js, lib/utils/location.js
=> Regex cleanup

lib/modules/showImages.js
ref: https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/79994427f96e547ba04aae9aad95cf9e650ebcf1#commitcomment-17833388
=> Fix expando container resizing in Edge

chrome/background.entry.js, firefox/background.entry.js, lib/environment/history.js, lib/environment/index.js, lib/modules/filteReddit.js, lib/utils/Thing.js, safari/environment.js
Useful for browsing /top.
Creates a button for removing links already visited, similar to "view images"
Closes #2456
=> Filter visited links

lib/css/modules/_styleTweaks.scss
Reddit seemingly added more specifity to their `.compressed` selector
=> Fix styleTweaks showExpando

lib/modules/voteEnhancements.js, lib/utils/__tests__/color.js, lib/utils/__tests__/math.js, lib/utils/color.js, lib/utils/index.js, lib/utils/math.js, package.json
=> voteEnhancements: interpolate custom link/comment score colors

lib/modules/hosts/bime.js
Lets you embed a shared data dashboard.
=> Bime.io host

lib/environment/_common.js, lib/environment/auth.js, lib/environment/index.js, lib/utils/index.js, lib/utils/location.js
~~Probably doesn't work yet in Firefox (at least, it will probably choke if you close the tab before the redirect).~~
Appears to work in all browsers (Chrome, Firefox, Edge, Safari), for both OneDrive and Google Drive.
=> Generic OAuth 2 auth flow handler

lib/css/modules/_neverEndingReddit.scss, lib/css/res.scss, lib/modules/neverEndingReddit.js, lib/modules/userInfo.js
=> Rebase and update #2509: New simple loading icon

lib/core/migrate.js, lib/modules/userTagger.js
=> userTagger: make it more obvious that colorUser controls vote weight tracking

lib/modules/menu.js, lib/modules/nightMode.js, lib/modules/styleTweaks.js, lib/utils/bodyClasses.js
Fixes #3079, fixes #3037
There is a short flicker when auto-disabling subreddit style on subreddits that don't support nightmode, on the first load (before it's cached).
Otherwise (i.e. for subreddits with the style manually disabled), it's instant.
=> Remove subreddit style before pageload

lib/modules/hosts/imgur.js
=> imgur: option to load lower-resolution images

lib/modules/subredditInfo.js
=> Update #2033: Added subreddit hover feature for full links.

lib/modules/commentNavigator.js, lib/templates/commentNavigator.mustache
=> commentNav: navigate by tagged users

lib/modules/keyboardNav.js
=> Mention goMode in descriptions of goMode shortcuts

lib/css/modules/_nightMode.scss
via https://github.com/Reddit-Enhancement-Suite/hotfix-data/pull/10
Fixes #2889
=> Fix reports being unreadable in nightmode

lib/modules/hosts/redditmedia.js
Primarily for direct links posted in comments, like [this one](https://www.reddit.com/r/announcements/comments/4p5dm9/image_hosting_on_reddit/d4i5e9z).
=> Add redditmedia host

lib/css/res.scss, lib/modules/noParticipation.js
=> Keep "Hover here for more details" open when you hover on said details

lib/modules/hosts/imgur.js
=> Imgur: support non-looping .gifv

lib/modules/sourceSnudown.js
Bandaid. I thought we put one on a while ago already, but shouldn't hurt to add this too. ¯\\\_(ツ)_/¯
https://www.reddit.com/r/RESissues/comments/4pu2lf/bug_source_button_multiplied/
=> guard against "source" button being added mutiple times

lib/modules/troubleshooter.js
Would have been useful to troubleshoot this: https://www.reddit.com/r/RESissues/comments/4rff0w/when_i_view_an_image_with_the_inline_image_viewer/
=> Add troubleshooter button for testing environment

lib/modules/keyboardNav.js
=> keyboardNav: make the hide shortcut work to unhide posts

lib/modules/hosts/derpibooru.js
=> derpibooru: update API calls to use `id` instead of `id_number`

lib/modules/userHighlight.js
Closes #2758
Adding to 4.7 because it's nearly trivial.
=> Rebase #2758: Body class for User Highlighter

lib/modules/keyboardNav.js, lib/templates/goModePanel.mustache
Closes #3136 
Updates the descriptions to match the behavior.
=> Fix goMode

lib/modules/keyboardNav.js
=> keyboardNav: options for sibling and thread scroll style

lib/modules/keyboardNav.js, lib/utils/dom.js
=> New scrollStyle 'middle'

package.json
It works as-is; this is mainly to experiment with coverage.
=> Update nyc config

lib/core/migrate.js, lib/modules/singleClick.js
=> Rebase #2285: hide [l=c] by default

.gitignore, lib/modules/hosts/redditmedia.js, lib/modules/showImages.js, lib/utils/__tests__/location.js, lib/utils/index.js, lib/utils/location.js, lib/utils/thingMetadata.js
=> Finish #3123: "reddit" media host, for image posts that link to comments page

lib/modules/showImages.js
=> showImages: don't trigger resize events for unloaded images

lib/core/init.js, lib/core/metadata.js, lib/css/modules/_version.scss, lib/css/res.scss, lib/modules/version.js, lib/templates/concurrentInstalls.mustache
and incidentally fix the settings console title
=> Warn user about multiple versions of RES running

lib/css/res.scss, lib/modules/submitHelper.js, lib/modules/submitIssue.js, lib/templates/diagnostics.mustache, lib/templates/submitIssueDefaultBody.mustache
=> Add help/info to reddit help/beta submit/warnings

lib/css/modules/_commentTools.scss, lib/modules/commentTools.js
=> commentTools fixes (Edge title, "use selected title" overlap)

examples/host.js, lib/modules/showImages.js
For twitch clips #3172.
Also fixes an issue where siteModules could not be disabled.
=> Allow multiple hosts per domain

lib/modules/accountSwitcher.js, lib/modules/showKarma.js, lib/modules/userInfo.js
=> Update link to post karma

.travis.yml, README.md, appveyor.yml, webpack.config.babel.js
So we don't have any surprises when deployment tries to build them
=> Build all targets on CI

.travis.yml
Spun off from #2946 since this may be needed before Chrome Beta
=> Automated GitHub release creation

chrome/background.entry.js, chrome/environment.js, lib/environment/permissions.js, lib/modules/accountSwitcher.js, lib/modules/backupAndRestore.js, lib/modules/commandLine.js, lib/modules/commentTools.js, lib/modules/newCommentCount.js, lib/modules/notifications.js, lib/modules/userTagger.js, lib/utils/alert.js
Now it opens an alert before opening the native popup, instead of only warning after the user denies it.
=> Refactor Chrome permissions message

lib/modules/styleTweaks.js
update description to remove reference to omnibar / make more browser nonspecific.
=> fixes #3201

lib/core/migrate.js, lib/modules/showImages.js
Resolves https://www.reddit.com/r/RESAnnouncements/comments/4vt35o/announcement_chrome_and_firefox_beta_releases/d61id8z
=> showImages gallery: Update filmstrip options

firefox/package.json
=> Limit firefox version to >=46

lib/modules/customToggles.js, lib/modules/filteReddit.js, lib/modules/nightMode.js, lib/modules/settingsConsole.js, lib/utils/createElement.js
=> Fix disabling NSFWQuickToggle

lib/modules/styleTweaks.js
=> styleTweaks: avoid readding subreddit styles when disabled natively

lib/modules/showImages.js
=> Transform single-piece gallery expandos

lib/modules/hosts/superstack.js, safari/Info.plist
I've added a new host file in `lib/modules/hosts` that supports images from [Super Stack](https://superstack.io).
I've tested this in Firefox, Chrome, and Safari. The code is linted.
=> Added support for Super Stack images in the inline image viewer.

lib/modules/accountSwitcher.js, lib/modules/dashboard.js, lib/modules/newCommentCount.js, lib/modules/showKarma.js, lib/modules/submitHelper.js, lib/modules/subredditInfo.js, lib/modules/subredditManager.js, lib/modules/userInfo.js, lib/modules/voteEnhancements.js, lib/utils/index.js, lib/utils/localization.js
=> localization: stop munging negative numbers to positive

lib/modules/userInfo.js
=> userInfo: handle suspended accounts

edge/edge.entry.js
Updated browser shim removing unneeded code. Needs further testing to make sure nothing broke.
=> Edge Shim cleanup

lib/modules/showImages.js
FIxes issue mentioned here: https://www.reddit.com/r/Enhancement/comments/4wjokb/how_to_prevent_image_from_moving_to_left_when/
=> showImages makeMediaZoomable: Fix sensitivity issue when expanding towards left edge

lib/modules/showImages.js, lib/utils/expando.js
=> showImages: Scroll-tweaks to make it pinHeader compatible

lib/modules/userTagger.js
=> Fix duplicate tag icon in commentingAs when you have a tag

lib/modules/commentTools.js
=> commentTools: {{escaped}} placeholder escapes >quoted lines

lib/css/modules/_styleTweaks.scss, lib/modules/styleTweaks.js
=> styleTweaks: implement floatingSideBar in pure CSS

lib/modules/nightMode.js, lib/modules/styleTweaks.js, lib/utils/__tests__/array.js, lib/utils/array.js, lib/utils/index.js
https://www.reddit.com/r/RESissues/comments/4wk8sb/bug_usesubredditstyles_does_not_adhere_when_using/
I can't repro the above issue, so there may be more races; this is definitely one of them, though.
=> Fix a useSubredditStyles/isNightmodeCompatible race

lib/modules/newCommentCount.js
=> newCommentCount: fix inaccurate subscriptionLength description

lib/modules/RESTips.js, lib/vendor/guiders.css
=> "Welcome to RES" tip asks for donations

lib/css/modules/_subredditManager.scss
Added :empty selector to the subreddit manager dropdown ul.
=> Hide the ugly empty space above edit buttons if link is not multireddit.

lib/css/modules/_showImages.scss
Also fixes `.linkImg` expandos on `/comments` pages.
=> showImages: expando-button CSS clean-up

lib/modules/showImages.js, lib/utils/expando.js
=> showImages: New function to discover button mediaClass and title

lib/modules/styleTweaks.js
=> styleTweaks: fix a potential race when disabling subreddit style in nightmode

lib/core/migrate.js, lib/modules/neverEndingReddit.js
=> NER hides dupes by default

lib/modules/commentTools.js, lib/utils/location.js
Fixes #3268.
Added the regex for live threads to location.js and added option to allow updates to live threads to be submitted with ctrl+enter (enabled by default).
=> Submit updates to live threads with ctrl+enter

lib/modules/hosts/xkcd.js
=> xkcd: match only www.xkcd.com and xkcd.com

lib/css/res.scss, lib/modules/announcements.js, lib/modules/commandLine.js, lib/modules/menu.js
incidentally, show gear menu on click
Addresses part of #3208
=> move ! gear announcement badge to separate clickable icon

lib/constants/sessionStorage.js, lib/core/init.js, lib/core/profiling.js, lib/modules/troubleshooter.js
=> Text-based visual profiling

lib/utils/dom.js
by fixing the MutationObserver sanity check
=> Fix show images, single click opener, etc. on NER p2+

lib/modules/orangered.js
mostly to ensure the native message count is up to date with the nre floating message, and unreadLinksToInbox is applied to every orangered element.
=> Orangered fixups

lib/modules/voteEnhancements.js
=> Add option to disable score color interpolation

lib/modules/orangered.js
Fixes console error: "Assignment to read-only properties is not allowed in strict mode".
=> Fixes bug with writing to style (strict compliance) causing edge to break filters.

lib/css/modules/_nightMode.scss
=> keyboard help panel - nightmode

lib/css/modules/_showImages.scss, lib/modules/showImages.js, lib/templates/mediaControls.mustache
1st click: Show the info
2nd click: Disable it
Implements #3292
=> showImages clippy: Integrate with mediaControls

safari/environment.js
=> use Init.headReady instead of Safari rolling its own

.travis.yml
=> Resume Edge Deployments

lib/modules/filteReddit.js, lib/modules/showImages.js
Resolves https://www.reddit.com/r/csshelp/comments/5067pt/any_way_to_select_just_one_of_the_res_buttons/
Resolves #2926
=> Set class name for 'filter visited links' and 'show images'

lib/modules/localDate.js
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2800
=> Make localDate work within sidebar

lib/environment/permissions.js, lib/modules/troubleshooter.js
=> Ensure that permissions denials are cached

lib/modules/hosts/gatherer.js
Fixes: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3351
=> Add image expander module for gather.wizards.com MTG card images

lib/utils/Cache.js, lib/utils/user.js
=> Fix stale karma numbers

lib/modules/selectedEntry.js
I don't believe this will cause any issues.
Resolves #3362
=> selectedEntry: Select on mouse down instead of only left click

lib/modules/keyboardNav.js, lib/modules/showImages.js, lib/utils/Thing.js
=> showImages: Destroy expando on hide

lib/modules/showImages.js
=> Fix building of expandos on non-thing links

lib/modules/showImages.js
=> Gallery: Remember the last resize width

lib/utils/__tests__/location.js, lib/utils/location.js
=> Comments regex should not match comment linklists

lib/core/migrate.js
It's abusing the reddit api too hard. Let's find a better solution in a few days.
=> disable fixing "commentpage+preview -> original post"

lib/css/modules/_styleTweaks.scss
=> floatingSidebar: scroll on overflow

lib/modules/showImages.js
=> show images button: Always show a count

lib/css/modules/_nightMode.scss
Fixes: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3343
=> Fix styles for nightmode search

lib/utils/__tests__/location.js, lib/utils/location.js
=> Fix pageType modqueue regex for multireddit match

lib/css/modules/_nightMode.scss
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3358
=> Fix nightmode styling for private subreddits

lib/utils/Thing.js
=> fall back to current subreddit if thing doesn't contain subreddit link

lib/modules/commentTools.js, lib/utils/Thing.js
=> remove now-unnecessary currentSubreddit() fallbacks for Thing::getSubreddit()

lib/css/modules/_dashboard.scss
=> dashboard: set min-height (not height) for add, edit, etc. widgets

lib/modules/subredditInfo.js
Basically allows users to conditionally revert #3096
Fixes #3408
=> subredditInfo: requireDirectLink option to only show the popup for /r/ links

lib/core/migrate.js, lib/modules/showImages.js
but with less abusing the reddit API this time
also applicable for other posts that link to comments page + preview (as seen in some experiments)
=> Re-enable redditmedia/i.redd.it expandos

lib/modules/dashboard.js
=> dashboard: Restore sidebar dashbord shortcut

lib/modules/keyboardNav.js, lib/modules/singleClick.js, lib/utils/dom.js, lib/utils/index.js
=> Keyboard shortcut works even when singleClick [L=C] is disabled

lib/modules/commentTools.js
https://www.reddit.com/r/modnews/comments/51gi3l/for_wider_release_sidebar_updates_with_added_css/
=> Update sidebar max character length

lib/css/modules/_showImages.scss, lib/modules/hosts/imgur.js, lib/modules/showImages.js, lib/templates/mediaControls.mustache, lib/templates/videoAdvanced.mustache
Resolves #3440.
I hope this is the correct way to implement this. I simply added a download button to the media controls that downloads the image/videos source.
I also removed the downloadurl from video-advanced as this replaces that. However from my testing it seems that didn't even work in the first place.
=> Adds download button to media controls.

lib/modules/neverEndingReddit.js
I didn't realize modifying the hash added a new history entry.
=> neverEndingReddit: Avoid adding a new history entry when selecting another page

lib/modules/neverEndingReddit.js
=> Workaround `replaceState` quirk in Edge

lib/modules/showImages.js
=> showImages draglistener: Fix mouseup outside of video/image

lib/modules/neverEndingReddit.js
Resolves https://www.reddit.com/r/RESissues/comments/53d1aj/bug_expanding_the_very_last_post_on_a_page_will/
=> neverEndingReddit: Don't auto load on select if paused

lib/modules/newCommentCount.js
=> Null-check the current comment count object

lib/modules/accountSwitcher.js, lib/modules/betteReddit.js, lib/modules/commentTools.js, lib/modules/dashboard.js, lib/modules/filteReddit.js, lib/modules/newCommentCount.js, lib/modules/subredditManager.js, lib/modules/userTagger.js
Backport some changes from #3321 that don't directly involve types, in the interest of avoiding merge conflicts.
=> Backport Flow changes

lib/modules/floater.js, lib/modules/pageNavigator.js, lib/utils/dom.js
The top offset should not depend on tab menu height, as that varies across custom stylesheets (e.g. /r/spacex). This change places the floater at a consistent position (left: 8px, right: 8px) and hides it if the header is visible.
=> floater: Consistent position, increased visiblity test frequency

.travis.yml, build/deploy.js, firefox/beta/package.json, firefox/getVersion.js, package.json, webpack.config.babel.js
...by using a separate build config so both are available at release time.
I hope the AMO API is reentrant.
=> Properly automate releasing Firefox stable versions as beta

lib/modules/accountSwitcher.js
- now uses proper function
- includes relevant import
___________________________________
See #3485 for relevant discussion.
=> Update gold expiration date calc to use formatDate

README.md
Good documentation is happy documentation
=> Documentation update - Update readme

lib/modules/multiredditNavbar.js
This fix #3495
I'm kinda surprised the solution was this simple so perhaps I didn't understand the issue fully? Anyway, according to my tests it now work as expected.
=> Fix multireddit navigation settings button link

lib/modules/hosts/vidgif.js
swirl.xyz has been renamed to vidgif.com
=> Update swirl.xyz expando

lib/modules/floater.js, lib/modules/showImages.js, lib/utils/Thing.js
Makes scrolling / using NER less janky.
=> Reduce number of layout recalculations

lib/modules/submitIssue.js
=> report diagnostics on /r/resbetatesting

lib/core/init.js
=> Don't run RES on advertising management pages

lib/modules/newCommentCount.js
=> bugfix - maintain subscription comment count on cache clear

lib/modules/notifications.js
Adds a class to [div.RESNotificationContent](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/notifications.js#L251) constructed from the notifications `moduleID` and `notificationID`.
```html
<div class="RESNotificationContent moduleID-notificationID"></div>
```
Resolves #2835
=> Add class to notifications

lib/modules/subredditManager.js
- Disable adding 'Last visited' to the subreddit table when storeSubredditVisit is false.
- Fixes #3448 
Let me know if you were looking for any additional changes along with this. This change just prevents the columns from being added to the host table.
=> Avoid drawing 'last visited' from storeSubredditVisit setting

lib/modules/subredditManager.js
=> #3498 Add "saved" shortcut to subreddit manager

lib/modules/showImages.js
Resolves https://www.reddit.com/r/RESissues/comments/57xhtn/bug_view_images_not_working/
=> Fix checkElementForMedia for non-Thing links

lib/modules/hosts/dropbox.js, lib/modules/showImages.js
Reimplements #1852 
Resolves #2604
=> New mediahost: Dropbox

chrome/environment.js, firefox/environment.js, lib/environment/__tests__/messaging.js, lib/environment/_messaging.js, node/environment.js, safari/environment.js
This is a prerequisite for the API for #3463
=> Add tests and minor refactor for messaging

lib/modules/commentTools.js
Added flair text magicPlaceholder for comment replies.
=> magicPlaceholders flair text for comments replies

lib/modules/commentTools.js
=> Supports comment tools on live threads

lib/modules/search.js, lib/modules/settingsConsole.js, lib/modules/settingsNavigation.js
=> Updated lines mentioned in #3483 to use _.startCase

lib/modules/userHighlight.js
=> Rebase and update #3110: Added '.alum' selector to User Highligher

lib/modules/filteReddit.js
=> Display correct title for filteReddit.options.NSFWfilter

firefox/background.entry.js
https://www.reddit.com/r/Enhancement/comments/59uxcf/indexeddb_corruption_in_the_firefox_change_the/
=> link to Firefox Bug #1236557 in indexedDB storage failure notification
