honestbleeps/Reddit-Enhancement-Suite

lib/modules/quickMessage.js

Fixes [a bug reported on reddit.](https://www.reddit.com/r/RESissues/comments/2qypen/bug_private_message_get_truncated_when_is_used/) (Would you prefer that I create an issue on github, even if it'll be immediately resolved?)
Also, stop silently shortening the subject to 100 characters and add an error message for it.

Prevent quick messages from being truncated on some characters + more

---

lib/modules/betteReddit.js
lib/modules/commentNavigator.js

As suggested in #1562, this handles comment navigator buttons (no performance impact) and reddit's comment/link buttons (slight performance impact, so disabled by default).
It's not very feasible to apply this to submission times (as was suggested), since they are dynamically updated.

Make more elements not show up in searches (noCtrlF)

---

lib/modules/showImages.js

The steam module only support links on the steampowered.com domain but I'm seeing a lot of links coming out of steamusercontent.com now.
This updates the domains and the detection regex on this module.

Added steamusercontent.com domain support to showImages Steam module.

---

gulpfile.js

changed the build dirs for Safari and Firefox to RES.safariextension and XPI to make the extension builders happier
refactored gulpfile directory references a little

Gulp build folders tweak

---

lib/modules/showImages.js

Fixes #1494.
Originally, the image would be replaced if the current `src` was different from the stored source. This obviously causes problems in albums, resulting in the image getting reset after each scroll.
Instead, we can check that the image we're replacing is the `transparentGif` used as a substitute for the original image. As far as I can tell, conserveMemory still works properly after this change.

showImages: stop conserveMemory messing up albums

---

lib/core/console.js
lib/core/res.css
lib/modules/commentPreview.js
lib/modules/settingsNavigation.js

Swapped out a few icon images for batch font icons.  This should supersede some of the "move icons from `url(https://aws...)` to `uri(data:...)`" PR
thanks to @erikdesjardins for suggestions.
Still need to do gear dropdown search button

Images to batch icons

---

lib/core/utils.js
lib/modules/quickMessage.js

This is the second most common API call that RES makes to the API, and it's unnecessary for the average user. Change it so we don't check for subreddits we moderate if we're sure we don't moderate any :sun_with_face:

Obviate calls to /subreddits/mine/moderator.json

---

Chrome/manifest.json
Opera/includes/loader.js
OperaBlink/manifest.json
RES.safariextension/Info.plist
XPI/lib/main.js
lib/core/migrate.js
lib/core/utils.js
lib/modules/commentTools.js
lib/modules/keyboardNav.js
lib/modules/saveComments.js
lib/modules/selectedEntry.js
lib/modules/showImages.js
lib/modules/userTagger.js

* commands: name, default keycode, description, include/exclude, and callback (explicit or name matching a keyboardNav method)
* commands can be registered from other modules
* more efficient lookup for keyboard commands
* use SelectedEntry to manage which post/comment entry is active/selected
* commands for navigating link/comment listing traverse the DOM starting at Selected Entry
* KeyboardNav help panel shows GoMode prefix
* Shortcuts work in more edge places now: fixes #1097
* Migrate some options from keyboardNav into more relevant modules
* fixed segfault error on "move to entry"
new module providing an interface for the currently selected post or comment.
* RESUtils.IsMatchURL, .matchesPageType, .isPageType
*  Deferred fetching module option values until all modules have run …

KeyboardNav refactor

---

lib/modules/settingsConsole.js

Fixes #1954
This occurred because the event handler to update the keycode for each shortcut used `.getElementById(optionKey)`, which would select the modmail icon (for users that have it) instead of the modmail option.
I'm not sure if it would be better to change our `id` naming scheme instead - it would make more sense but require more changes.
@andytuba I don't appear to have permission to make a PR from the issue; I imagine I might if I was the issue's creator.

Allow modmail keyboard shortcut to be saved properly

---

lib/core/migrate.js
lib/core/utils.js
lib/modules/hover.js
lib/modules/showParent.js
lib/modules/subredditInfo.js
lib/modules/userTagger.js

Fixes this issue [(reddit post).](https://www.reddit.com/r/RESissues/comments/2vh45v/bug_cant_disable_fading_on_any_hover_popups)
`$.fadeTo` measures speed in seconds (instead of the fractional speed we used before), causing `fadeSpeed.value = 1` to fade things out over 1 second instead of instantly (as intended).

fadeSpeed corrections

---

lib/core/options.js
lib/core/templates.html
lib/modules/settingsConsole.js
lib/modules/settingsNavigation.js

* stage options changed while console is open, so user can switch modules without losing changes
* before closing console/window, prompt user to discard unsaved changes (if any exist)
* some refactoring, of course
This could probably use another iteration for UX, such as autosave+revert, but this is a good incremental step.

Settings staging / prompt before discard

---

Chrome/background.js
Chrome/browsersupport-chrome.js
Chrome/manifest.json
Opera/browsersupport-opera.js
Opera/includes/loader.js
Opera/index.html
OperaBlink/background.js
OperaBlink/manifest.json
RES.safariextension/Info.plist
RES.safariextension/background-safari.html
RES.safariextension/browsersupport-safari.js
XPI/data/browsersupport-firefox.js
XPI/lib/main.js
lib/core/utils.js
lib/modules/betteReddit.js
lib/modules/floater.js
lib/modules/neverEndingReddit.js
lib/modules/orangered.js

Unread messages/notifications/buttons
* update all tabs when RES sees a new notification: userbar mail icon, userbar mail count (adds if missing), userbar retro mail count, title, favicon, NRE mail icon and count  (where appropriate options are enabled)
* refactored modules.floater, for managing elements that need to float around -- particularly the NER pause button and floating orangered. fixes issue where floating buttons are invisible when betteReddit.pinHeader = fullHeader
* Refactored Never-Ending Reddit's floating inbox into orangered
* `RESUtils.rpc(moduleID, methodOnModule, [ 0, "or", "some", "args" ])` -- indirectly call a module method. future plans: call from RES command line and from messages from other extensions
* `RESUtils.sendMessage({ "multicast", moduleID: "someModule", …

Orangered, Floater

---

lib/core/init.js
lib/modules/hosts/fitbamob.js
lib/modules/hosts/gfycat.js
lib/modules/hosts/gifyoutube.js
lib/modules/hosts/giphy.js
lib/modules/hosts/imgur.js
lib/modules/quickMessage.js

Maybe they used to do something, I don't know.
But since `RESTemplates.load` does absolutely nothing [if the callback is falsy](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/401b0b61363ae7921599c9939dcb68acf1127671/lib/core/template.js#L5), they don't do anything now.

Remove uneffective RESTemplates.load calls without callbacks

---

lib/core/utils.js
lib/modules/commentPreview.js
lib/modules/sourceSnudown.js

Fixes #2036 
Works for me in Chrome and Firefox, not sure which browser @andytuba was using when it didn't:
(it's darkened in the .gif for visibility)

Align live preview and source stripes with the top left

---

Chrome/manifest.json
Opera/includes/loader.js
OperaBlink/manifest.json
RES.safariextension/Info.plist
XPI/lib/main.js
lib/modules/hosts/pastebin.js

Replaces would-be pastebin support in #1352, since it appears that their iframes work fine now, even with https.
(might be too wide, i dunno)

Pastebin expando support

---

lib/modules/hosts/pastebin.js

No `|| options.default` since it's not catastrophic if it's left blank, they can leave the width unspecified if they want.

pastebin.js: option for expando width

---

Chrome/manifest.json
Opera/includes/loader.js
OperaBlink/manifest.json
RES.safariextension/Info.plist
XPI/lib/main.js
lib/modules/hosts/github.js

There are a few rendering glitches in `.md` files due to differences between Snudown and Markdown, but it's definitely better than the raw text.
---
---
how2loop.js just happens to be the name of the gist, if you're wondering why it's duplicated

GitHub gist expandos

---

lib/core/utils.js
lib/modules/keyboardNav.js

In https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/903c8a9553f1f46b63e9d65994b04da3dd6a728f, the behavor of RESUtils.isMatchURL() changed, probably unintentionally.  It more or less just checks isReddit() and then passes off all the work to matchesPageType().  
The old matchesPageType() did more than match the page type.  It would also see if the include/exclude was a regex and test it versus the URL (see old lines 96 and 108 in the diff above).  The new matchesPageType() does only what the name implies, and so, for example, filteReddit's regexes in its include list don't match things like "linklist" and so isMatchURL() will always be false.

Regression in RESUtils.isMatchURL()

---

lib/modules/nightmode.css

lighten the background of uncolored tags in nightmode

---

lib/modules/userTagger.js

One less icon relying on the spritesheet!
There are a few subreddit stylesheets that conflict (their icon overlaps) - but the button still works, and all they should have to do is add `.userTagLink.RESUserTagImage::after { content: ""; }` to hide ours.
Before/after:

Use Batch for user tagger icon

---

lib/modules/quickMessage.js

Only expose what's necessary, instead of everything.
I guess the 6th (?) time's the charm.

quickMessage: use addModule() properly

---

lib/modules/commentTools.js
lib/modules/settingsConsole.js

Move boilerplate macros into macro default values so that users can customize them better and not have to put up with defaults they don't want.
Not bothering to add migration to add default macros because anyone who cares can probably do it themselves or ask for help.
Removed look of disapproval. It's stale. 
---
I fixed settings console showing "undefined" in table options when a value is missing (like when a new field is added)
---
P.S. I left the LOD modal in in case somebody wants to add an autodetect in for "user has pasted a hundred [R..E..S]()".

Macro default values, settings console fix

---

lib/core/res.css

I don't see the current one on Chrome (a browser specific issue that isn't FF? whaaat), I guess it doesn't choose fallback fonts as intelligently:
Here's how it looks in Firefox, original / this PR:
Alternatively we could specify the font for the original icon, but I don't believe there's a single font that'll work on all platforms. (judging by [this site](http://www.fileformat.info/info/unicode/char/26a0/fontsupport.htm), whose trustworthiness is debatable, we'd have something like: `font-family: 'Segoe UI Symbol', FreeSans, STIXGeneral-Regular;`)

Use batch icon for advanced options warning

---

lib/modules/betteReddit.js

Fixes #1788
I'm not completely satisfied with the options (they take up a *lot* of space), nor the timestamps themselves (although it might be the best we can do with CSS alone).

betteReddit: options to show full timestamps by default

---

lib/core/res.css
lib/modules/accountSwitcher.js

For better alignment:
(original / 15px / 14px - Chrome without notifications, FF with) - *now with valign:middle it's 2px lower than this image*
Also removes the 3px extra padding-bottom from the userbar - here's how it looks now:

gear icon font size 15px -> 14px

---

lib/modules/hosts/ctrlv.js
lib/modules/hosts/deviantart.js
lib/modules/hosts/flickr.js
lib/modules/hosts/futurism.js
lib/modules/hosts/giphy.js
lib/modules/hosts/imgflip.js
lib/modules/hosts/imgur.js
lib/modules/hosts/livememe.js
lib/modules/hosts/makeameme.js
lib/modules/hosts/memecrunch.js
lib/modules/hosts/memedad.js
lib/modules/hosts/memegen.js
lib/modules/hosts/minus.js
lib/modules/hosts/onedrive.js
lib/modules/hosts/photobucket.js
lib/modules/hosts/picshd.js
lib/modules/hosts/snag.js
lib/modules/hosts/steampowered.js
lib/modules/hosts/vidble.js
lib/modules/showImages.js

This is no longer necessary, since we use [addUrlToHistory()](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/8719cc456bce7ef6f338ad7c22f172c5873d3833/lib/modules/showImages.js#L1636).
Also, for single-image expandos, make the image link to its source URL (this basically preserves existing behavior, since it used to be set to the title URL, which used to be changed to the source URL).

Stop changing expandos' link URLs

---

lib/core/res.css

So it doesn't flicker when you move to the next gallery image.
Alternatively, it could pop into existence after a little while, or maybe something else. (any suggestions?)

Fade in the image loading spinner

---

lib/modules/hosts/deviantart.js

It was already in the regex, but omitted from the domains.
https://www.reddit.com/domain/fav.me

Add fav.me to deviantART's domains

---

lib/modules/settingsConsole.js

`RuntimeError` does not exist as an error for JavaScript.

settingsConsole: Replace RuntimeError with Exception

---

lib/modules/newCommentCount.js

Fixes #2139. There was a split of the number of the comments and the word "comments" predicated on a space. Japanese doesn't use a space after numbers from what I can tell. Changed it to strip all non-numeric characters.
I noticed it always uses the word "new" no matter the interface language. Does RES have multiple interface languages? Is it an issue that "new" is always in English?

Fixed #2139 -- new comment count now shows in Japanese language interface

---

lib/modules/hosts/youtube.js

–instead of ignoring all posts.
Fixes #2184 
Also, we already know that the domain matches, so we don't need to check it again.

YouTube expandos: only ignore post if it already has an expando

---

lib/modules/commandLine.js

lets you be super lazy about capitalization and full words with `RESStorage get RESmodules.moduleName'.  basically takes anything except bad capitalization/spelling for the module name or the or storage key

Lazy RESStorage command line support

---

lib/modules/hosts/deviantart.js
lib/modules/hosts/fitbamob.js
lib/modules/hosts/gfycat.js
lib/modules/hosts/gifyoutube.js
lib/modules/hosts/giphy.js
lib/modules/hosts/imgrush.js
lib/modules/hosts/imgur.js
lib/modules/hosts/minus.js
lib/modules/hosts/onedrive.js
lib/modules/hosts/redditbooru.js
lib/modules/hosts/tumblr.js
lib/modules/hosts/vidble.js
lib/modules/showImages.js

Mainly this PR removes the caching (anti)pattern that appears in a lot of siteModules, where responses are cached in an object (i.e. only for one pageload) - so it only makes a difference when a link appears on the same page twice, which is uncommon (especially since RES ignores repeated links by default).
Technically it doesn't *hurt* anything, but I know that many people have blindly copied it when creating new siteModules (I probably have, at some point), so I think it's best to get rid of it.
And if we absolutely need to avoid sending the same request twice, we can use `aggressiveCache: true`, which does the exact same thing.
Also includes support for `tumblr.com/image/` URLs, a few other kinds of tumblr text posts - specifically `quote, link, chat, answer` - and better handling of …

More expando improvements

---

lib/modules/keyboardNav.js

commentsLinkNewTab wasn't even being used for some reason?
commentsLinkNewTabFocus fixed.
fixes #2213

keyboardnav fixes

---

lib/core/res.css

So when you're copy-pasting stuff from a comment, the navigation helpers, user tags, embeds, etc. don't get copied with it.

Add user-select:none to RES widgets in comments

---

README.md
gulpfile.js

Fixes #2141 
This produces exactly the same output as before (unless there are unexpected files in lib/, in which case it will perform identically to Grunt and makelinks.sh).
Gulp now works as follows:
There are 6 tasks: `build, zip, watch, add-module, add-host, clean`.
Browsers (`chrome, firefox, safari, opera, oblink`) can be specified with `-b browser1 -b browser2`. If none are specified, gulp will use all of them.
Files for add-module and add-host are still specified with `--file filename.js`.
The zip output directory now defaults to `<rootBuildDir>/zip`, and can be specified with `--zipdir /path/to/dir`.
If you run multiple tasks the specified browser will apply to all of them, i.e. `gulp build watch -b chrome` will build only chrome and watch only chrome.

gulp overhaul

---

lib/modules/usernameHider.js

Fixes #1881. Could we potentially do a migration so that all users have the accounts value at least set to an empty array, so we don't require this null check anywhere?

usernameHider: Add null check for accountSwitcher accounts

---

lib/modules/hosts/gfycat.js
lib/modules/hosts/giphy.js
lib/modules/hosts/raddit.js

98d9c22e7b3bb3629432fbf04a5dd3aa535c70fe removes existing expandos for any RES-handled post, so we don't need to do so in the siteModules.

Minor siteModule cleanup

---

lib/modules/singleClick.js

Fixes an issue [from reddit.](https://www.reddit.com/r/RESissues/comments/39zqd3/bug_single_click_opener_treats_self_posts/)
This'll be fine as long as nobody manages to guess their post's ID (good luck).

L=C doesn't get set properly on search pages

---

makelinks.sh

Double brackets eliminate the need for quoting variables.

makelinks: Use double brackets to simplify expressions

---

lib/core/migrate.js
lib/modules/keyboardNav.js

Separate preference for "move down/up in tree-threaded comment lists" from generic "move down/up in flat lists"
https://www.reddit.com/r/Enhancement/comments/341x9n/feature_request_keyboard_navigation_settings/
TODO: test functionality, test migration. basically test the whole thing.

keyboardNav moveDownComment/moveUpComment

---

lib/modules/quickMessage.js

Otherwise we end up with two overlapping listeners on "error" pages (i.e. "this sub is private" pages).

quickMessage: refine .content selector

---

changelog.txt

Categorize enhancements and add a few more items. Closes #1976.
Assumes that #2325 will be merged for 4.6.
As always, big thanks to @allthefoxes for putting this together.
Not sure if we want to keep the [silly commit messages](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2328/files#diff-e8800259c4985f4a73b0936128034c53R104), but they're there for now.

Update changelog for v4.6.0

---

lib/core/utils.js

This would cause issues when clicking message links like `/message/compose?to=/r/enhancement#header`.

utils: fix minor getUrlParams issue

---

lib/core/utils.js

`eventTarget` doesn't exist, and `event.target` seems like the best replacement.

utils: Use event.target instead of eventTarget

---

lib/modules/dashboard.js
lib/modules/subredditManager.js

Prevents this from happening: 
[Check for yourself.](https://www.reddit.com/r/funny/search?q=search&sort=relevance&t=all)
It's odd that `.side` wasn't specified in the first place, is there a reason for that?

Remove duplicate buttons on new search page

---

lib/core/res.css

Restores consistency in albums between self and link submissions. This fixes a styling problem introduced when reddit changed their font sizes and line spacing within `.md` divs.
Screenshots showing exactly what this PR does: 
On the left is a self post and the right is a link submission (before & after).
I also modified the css on the controls because the current css is likely to cause headaches (e.g `top: -9px`).

Image albums style cleanup

---

lib/reddit_enhancement_suite.user.js

In particular, this removes the `Function.prototype.bind` polyfill that we should no longer need, given that Safari 5.1 is far, far away.

Compatibility changes

---

lib/modules/dashboard.js

Reddit can serve up to 100 entries per request, so why not?
It won't be fun to manually increment it, but I guess you can always set the default to what you want and then add widgets.
[via reddit](https://www.reddit.com/r/Enhancement/comments/3cstep/feature_request_change_the_widget_cap_to_a_higher/)

Increase max # of rows per dashboard widget

---

lib/modules/userbarHider.js

Fixes #2368 
I tested it with usernameHider, but as far as I can tell there's no instance where `span.user` won't exist.

Userbar: only indent username if toggle button exists

---

lib/modules/subredditManager.js

Left side shows new styling, with mouse pointers to show its advantages over current style.
Added some !important declarations to override themes like /r/askreddit.

Improve usability of subreddit dropdown links

---

lib/core/res.css
lib/modules/dashboard.js
lib/modules/filteReddit.js
lib/modules/subredditInfo.js
lib/modules/subredditManager.js

subredditInfo.js relied on filteReddit.js to apply the correct style to the subscribe button. This PR creates a universal class based on fancy-toggle-button which is module-independent, and removes doubled-up CSS.
I named the class res-subreddit-btn because all the relevant buttons perform subreddit actions: subscribe, shortcut, dashboard, filter. This doesn't touch the +friends button because that uses reddit's class names.

Universal class for subreddit-specific toggle buttons

---

lib/core/res.css

In the showImage module image caption linebreaks are currently not supported, making lists difficult to read. This PR adds a new util function, $.safeHtmlLinebreaks, which first sanitizes the input string then replaces linebreaks with a `<br>` tag.
I only tested this with an imgur album ([this post in particular](https://www.reddit.com/r/interestingasfuck/comments/3fqlf1/famous_last_words/)) so if need be I can try to test other services as well.

Add support for image caption linebreaks

---

gulpfile.js

Since commit 24d772caa2fa056f73bbe01bbe8393a9e8b72b35 `gulp -b firefox` does not create main file because XPI/lib/main.js was moved to XPI/index.js but gulpfile.js was not updated.

Update XPI main file path in gulpfile.js

---

lib/core/res.css
lib/core/templates.html
lib/modules/settingsConsole.js

Minor layout issues have emerged in the settings console; tables difficult to read, long option names cut off by toggle buttons, elements out of alignment, inconsistent spacing between elements, green highlight color isn't colorblind friendly, and so on.
This tweaks some styles to make things more readable and clean, without changing the overall look too much. Some unused CSS was also cut out.
It also changes the layout model to [flex](http://www.w3.org/TR/css-flexbox-1/), which is ideal for the settings console, it only required the addition of one div which I've called 'optionSetting'. Using flex means you no longer have to worry about managing margins and fiddling with floats, flex takes care of it for you.
Screenshots showing before and after of the full settings console (updated): …

Settings console design cleanup

---

lib/modules/nightMode.js
lib/modules/nightmode.css
lib/modules/selectedEntry.js
lib/modules/styleTweaks.js
lib/modules/userTagger.js

* Makes nightmode compatible with different modules and reddit features
* e.g. Visited link color, sticky color, username colors with username highlighter disabled.
* Removes duplicate and unnecessary styles
* The color of the NSFW tag was set in two places, yet it doesn't need to be included at all
* Alternating background colors on link listings isn't something reddit or RES does by default, why should nightmode introduce it? Should be an option in styletweaks that works with and without nightmode.
* Removes overreaching styles
* e.g. selectedEntry should only add BG color on .md-container, not every .md inside the container.
* Groups more selectors to reduce number of lines
* Adds new styles that were missing. e.g. white drop shadows, black text on black, etc
* Doesn't break existing …

Big Nightmode Update

---

lib/core/res.css

* Toggle buttons were sometimes expanding in width.
* Option titles weren't flexing correctly.

Settings console minor layout fixes (toggleButton & optionTitle)

---

lib/modules/selectedEntry.js

e.g. in [this thread](https://www.reddit.com/r/AskReddit/comments/3cfifw/what_was_the_worst_pr_move_in_history/)
Focus a "load more comments" entry with keyNav, then click it or press enter.
In 4.5.4 you will focus the top loaded comment (correctly), but in dev you'll focus the last comment in the chain of loaded comments.

Clicking a focused "load more comments" will focus the last new comment

---

lib/modules/filteReddit.js

`RESUtils.things` should already return an array, so this is unnecessary.

filteReddit: Avoid unnecessary [].slice wrapping

---

lib/modules/nightmode.css
lib/modules/styleTweaks.js
lib/modules/upload.js

* Adjusted some colours to be less harsh.
* **Removed custom expando sprites** and replaced with the simple CSS 'filter'. Filter is a relatively new and experimental style, but I feel that it's worth using because it saves an extra http request, and if it fails for some users they only have to deal with bright icons. [caniuse chart](http://caniuse.com/#feat=css-filters).
* Changed a bit of inline CSS in upload.js.
Animated gif showing differences (new version has darker colors on text):

Make nightmode look a little nicer

---

lib/core/res.css

Adds a border around the donate button, same color as the orange text. It stopped looking like a button when the background color of the console went from light blue to white.

Donate button has lost its buttony look

---

lib/core/res.css
lib/modules/menu.js

I believe this was the intended purpose of this function, because it's only checking the background property of the icon in the user bar. The legacy class shouldn't affect every icon on the page since they could be styled differently.
See /r/naut and /r/askreddit using master and notice the broken icons in userTagger, commentPreview and NER. I'm not sure which other subreddits to check.

Only use legacy gearIcon in user bar

---

lib/core/res.css

Reddit doesn't declare a font-family for its fancy-toggle-buttons, so RES shouldn't either.

remove font-family from res-fancy-toggle

---

Chrome/background.js
Chrome/manifest.json
lib/modules/hosts/onedrive.js

The old implementation of the OneDrive host used an external URL extender for 1drv.ms links because Chrome doesn't allow CORS requests without permissions.
I've re-implemented it so it is no longer depended on the site and now it will ask for optional permissions. The only problem atm is that it will show a message about Twitter if they disallowed it.
If the user already gave permission it will load regularly, if they haven't given permission the expando will show up as a selftext and on open it will transform to the proper expando (if they've given access).
It required changes to the `background.js` from Chrome because I needed the responseURL field of the xhr requests. I'm not entirely sure if this is the best way because it caches extra info for all requests?
I've tested it a lot on …

Removed OneDrive site dependency

---

lib/modules/hover.js

For Subreddit Info and User Info I like to have a short open delay and longer fade delay, but currently that causes this kind of thing to happen: https://imgrush.com/opq6CoX2YGVs
In that situation close() fires after open(), which prevents the card from ever appearing, unless you hover off the link and back over it. My solution is to check if the latest event type is `mouseenter`, and if so, close and reopen the card.
I also replaced the animated shrinking effect on close() with a simple fade, which affects all hover objects including the cog menu. I hope that's okay.

Hover cards open more reliably, and use fadeElementOut

---

lib/modules/nightmode.css

In nightmode the CSS filter property on expandos doesn't play well with the NSFW stripes, because it converts them to grayscale:
I couldn't find a solution to make the stripes work, short of adding the old sprite back in.
As a workaround I added some extra filters and removed the stripes, turning the expando itself red:
The [RES expandos](https://s3.amazonaws.com/b.thumbs.redditmedia.com/tBwwK20XXxtpgudWx1L7bDXla-iotv-JA0jgA0Y-FVs.png) have lighter borders and +/- indicators than the text and video expandos, so they're harder to see. It's still usable, but could be better.

Highlighted NSFW expandos in nightmode

---

lib/modules/subredditInfo.js

Subreddit info wasn't using cached data when the subreddit name contained capital letters. Since user Info doesn't convert usernames to lowercase I didn't see the need to do it for subreddits.
Also, the 'not found' message wasn't always displaying when it should.

Ensure subreddit hoverInfo is cached, and jsonData.kind is subreddit

---

lib/core/res.css
lib/modules/modhelper.js
lib/modules/selectedEntry.js

As requested [here](https://www.reddit.com/r/Enhancement/comments/2odnoi/cssis_there_a_reason_the_active/) and [here](https://www.reddit.com/r/Enhancement/comments/3j3jnu/feature_request_put_reskeynavactiveelement_on_the/).
This doesn't change any existing behavior or styling, it just adds a class to `.thing` and leaves it up to themers to do what they will.
I made a demo page with some styling to show what this makes possible (you'll need to get the PR obviously): https://www.reddit.com/r/resdemo/comments/3jbs3b/nested_comments/
Currently, if you want to get the above result without an active class on `.thing`, then you'd need to rewrite a significant portion of the comments' layout, which is a PITA.

Added an extra class for selected comments

---

Chrome/browsersupport-chrome.js

This is more idiomatic, and it works in Firefox today.
The current code will not work in Firefox until these bugs are resolved:
https://bugzilla.mozilla.org/1208761:
chrome.i18n is undefined in content scripts
https://bugzilla.mozilla.org/1208763:
Treat chrome-extension:// and moz-extension:// schemes as equivalent
This obsoletes #2463

Use getURL() instead of manual URL construction

---

Opera/opera-footer.js
lib/modules/orangered.js

The bundled Favico lib exports itself by setting `this.Favico = Favico`.
The orangered module then presumes that Favico will be available on the
global `window` object, but that's not the case for Firefox's sandbox.
From [Bug 1208775][]'s discussion, it sounds like we might WONTFIX this.
Simply omitting `window.` works equally well in Chrome and Firefox.
[Bug 1208775]: https://bugzilla.mozilla.org/show_bug.cgi?id=1208775#c3

Don't presume window is the global object for js

---

lib/modules/styleTweaks.js

No longer renders on top of sidebar.
Removed the pseudo element and applied styles directly to div.clearleft.
[Bug report](https://www.reddit.com/r/RESissues/comments/3n3m49/bug_highlighttoplevel_line_drawn_over_sidebar/).

Fix styling of highlightTopLevel

---

lib/core/res.css

It was adding extra spacing above self posts (a few pixels).

Don't add CSS overflow property to self text

---

lib/core/utils.js

...such that you can't send more than one request to an endpoint, even if the cache is expired (since the old promise would still be used, as though the old request was still in progress).

RESUtils.cache.fetch is subtly broken

---

lib/modules/userInfo.js

Fixes #2447.
Sets correct attribute values on the friend toggle button.
Clicking the friend button expires the cache on the associated user which forces a new check the next time userInfo is opened.
Makes the throbber work the way it was originally intended to. The throbber element needs to be a variable before being passed to def.notify().

UserInfo friend toggle button fix

---

lib/modules/singleClick.js

Also fixes [this issue](https://www.reddit.com/r/RESissues/comments/3r0o8p/bug_shiftl_not_working/) because keyboard nav just [clicks the link](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/3d453559ea37adf256dd9833a00bae34de81c4d7/lib/modules/keyboardNav.js#L1244).
It should really have the (hacky) link clicking removed, but that's a lot of refactoring that I don't want to do at the moment.

singleClick: respect left/middle click opening in fore/background tabs

---

lib/modules/hosts/raddit.js

To save money on its SSL cert, embed.radd.it is no longer supported via HTTPS.  Updated code to use the new ?embed format instead.  Autoplay is no longer supported.  I've removed it from radd.it's options.
All embedded links are currently broken, so please include this in the next release!

Removed autoplay and replaced embed.radd.it

---

lib/modules/showImages.js

for consistency with removing reddit expandos when RES provides the expando
before:
after:

remove reddit expando button for duplicate images

---

lib/core/utils.js
lib/modules/floater.js
lib/modules/hosts/raddit.js
lib/modules/showImages.js

Utility function RESUtils.getHeaderMenuList() was adding a new tabmenu every time it was called.
The name of the function was misleading because it's not only returning the tabmenu, but it's creating one too. There's only one time it needs to create a new element and that's in showImages.js.
With the fix:

RES is adding too many tabmenus

---

lib/modules/userTagger.js

`JSON.parse('null') === null`, so safeJSON doesn't save us.
Broken in master and 4.6.0.

Prevent voteWeight from breaking when users have no tags

---

.gitignore

Most of the Visual Studio gitignore can be safely removed unless IE development begins again.

gitignore: Remove unused and fix existing rules

---

lib/modules/messageMenu.js

The description says the default value is 800, when it is actually set to 1000.

set hoverDelay to stated default

---

lib/core/templates.html

Bug report: https://www.reddit.com/r/RESissues/comments/40svge/bug_gfycat_expando_controls_have_been_reversed/
Solution: changed physical order of buttons.

gfycat controls are in the wrong order

---

lib/core/utils.js
lib/modules/keyboardNav.js

Fixes #2622 and [this issue](https://www.reddit.com/r/RESissues/comments/41ooxs/bug_you_cant_use_the_movedownsibling_keyboard/) (from reddit).
[This](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/e83e5e0e01ca21e694922e95e2d6413bf32f9257/lib/modules/keyboardNav.js#L1602) is the behavior (from 4.5.4) that the the 'legacy' scrollStyle mimics.
It wasn't an option for j/k scrolling in 4.5.4, but I guess why not?

keyboardNav next/prev sibling works like it did in 4.5.4

---

lib/modules/commandLine.js

These must have been skipped when loggedInUser() was moved into RESUtils. I didn't find any other instances in /lib/.

Command Line returns undefined for loggedInUser() (sometimes)

---

lib/modules/nightmode.css

Closes #2627
Allow subreddits to properly customize Nightmode expandos and the 'self' thumbnail.
Leaves in the one filter property for #RESlogo, which only shows up the in the settings console, which subreddits shouldn't be changing.

Remove filter from nightmode.css

---

lib/core/res.css

Edit: Fixes #2624
https://i.imgur.com/Wfm6Yt4.png
A workaround has been added to /r/resupdates, which fixes that specific issue. However there's other ways this bug can crop up, so the best solution is to nix the offending CSS from RES. It was only acting as an extra safeguard anyway, we should be able to live without it.

Remove some unnecessary CSS from .usertext elements

---

lib/core/utils.js

Fixes #2673 
There's no standard for formatting a query string (you can do basically whatever you want), but the closest thing is [application/x-www-form-urlencoded](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1), which states that spaces should be replaced by `+`.

Decode '+' in query strings to ' '

---

lib/modules/hosts/streamable.js

Fixes #2678
Copied from vimeo.js
However #2522 still applies to streamable videos in comments.

Streamable is handled natively in reddit for submission titles.

---

lib/core/migrate.js

If showUnreadCount was not present, the moveOption migrator would fail, so the forceUpdateOption migrator would switch hideUnreadCount on. Reversing the order of the migrators fixes this.

Fix showUnreadCount migration

---

lib/modules/nightMode.js
lib/modules/nightmode.css
lib/modules/styleTweaks.js
lib/modules/stylesheet.js

Closes #2705 
Nobody seems to have reported the issue about "stylehsheets set to only load inside certain subreddits are loading on frontpage"

Restore grey links by default, add option for colored links

---

lib/modules/betteReddit.js

Depends on #2684; [diff](https://github.com/erikdesjardins/Reddit-Enhancement-Suite/compare/promise-to-async...fix-videoTimes).
Fixes #2234, closes #376.
The quota will be about 10 million requests per day (one request = up to 50 videos, so 10 million listing pageloads or so), and it's enabled by default...not sure if that'll be enough. I really don't know how often the average user browses reddit. If in doubt, we could just migrate it to off.
Although if we leave it on, funnily enough, we'll probably get better usage statistics than the Chrome webstore gives us...

Fix YouTube video times

---

lib/modules/keyboardNav.js

If keyboard nav settings are set to open links in the same tab, it wouldn't work because this was broken sometime down the line.

Fix keyboard nav regression

---

lib/modules/styleTweaks.js

Prevents an error if the user has the checkbox disabled (or it's otherwise uninitialized).
(thanks @andytuba)

styleTweaks: null-check module.styleToggleCheckbox

---

lib/modules/showImages.js

On the first click of an expando the 'collapsed' class doesn't get removed, which is evident if you're using Reddit's new expando CSS.
The fix is on line 172, the other changes are code style.

Expandos lose 'collapsed' class when expanded

---

lib/modules/showImages.js

On the first click of an expando the 'collapsed' class doesn't get removed, which is evident if you're using Reddit's new expando CSS.
The fix is on line 173, the other changes are code style.
Edit: I didn't mean to base this on master, but I'm guessing it's still useful.

Expandos lose 'collapsed' class when expanded (master)

---

lib/modules/hosts/imgur.js

Fixes #2300.
I removed the file extension `(\..+)?` because there don't appear to be any valid `/a/` or `/gallery/` URLs with a file extension. (@andytuba?)

Improve imgur album regex

---

lib/modules/showImages.js

Was doing `&&` when it should've been `||`.
For example, run the following code in the console to see the difference.
```
var module={options:{clippy:{value:false}}};
elem = {title:''}
if (!module.options.clippy.value && elem.title) console.log('skipped 1');
if (!module.options.clippy.value || elem.title) console.log('skipped 2');
>> skipped 2
```

Fixed clippy to correctly be disabled.

---

lib/css/modules/_accountSwitcher.scss

Tiny bug fix for the account switcher dropdown.
When the display style on the account switcher is set to "simple arrow", the arrow icon is misaligned. This fix just switches the arrows vertical align back to middle which fixes it for me.

Bugfix account for swicther "arrow" dropdown

---

lib/css/modules/_userTagger.scss

This makes it so when you select comment text, the vote weight won't get copied (like `/u/username [+2]`)

Make vote weights unselectable in comment text

---

README.md

It seems to imply that Gulp is one of the things you need to install manually, which is no longer the case.

readme: remove potentially misleading line about Gulp

---

chrome/manifest.json
firefox/index.js
lib/modules/hosts/dailymotion.js
node/files.json
safari/Info.plist

Resolves #1096.
These expandos work great, *but* they produce about a million [mixed-content warnings and errors](https://cloud.githubusercontent.com/assets/7673145/5063324/ace7bba2-6daf-11e4-814e-b653ddbfba26.PNG) (no loss of functionality, just logging scripts and other unimportant stuff).

Dailymotion expando support

---

chrome/manifest.json
firefox/index.js
lib/modules/hosts/jsfiddle.js
node/files.json
safari/Info.plist

This is the final part of, and closes #1352.
~~Unfortunately, jsFiddle insists on loading 3rd-party scripts over HTTP, so functionality is broken in many fiddles.~~
~~Update (2016-03-13): They still load dependencies over HTTP. *Why?*~~
Actually, seems like it's just for old ones, new ones seem to work fine.

JSFiddle Expandos

---

chrome/manifest.json
firefox/index.js
lib/modules/hosts/gyazo.js
node/files.json
safari/Info.plist

Resolves #2484.
~~They don't support CORS, so optional perms still need to be added.~~

gyazo expandos

---

chrome/manifest.json
firefox/index.js
lib/modules/hosts/twimg.js
node/files.json
safari/Info.plist

Fixes #913.
~~I can't imagine it's very likely that `img.<png/jpg/gif>:<something>` wouldn't be an image, so I think it would be fine to do this instead of adding a special case for Twitter.~~

Show expandos for twitter's alternate image resolutions

---

Chrome/manifest.json
Firefox/index.js
Safari/Info.plist
lib/modules/hosts/graphiq.js
node/files.json

Add support for [Graphiq](https://www.graphiq.com/) visualizations. These are interactive, live-updating data visualizations which are popular with publishers like [USA Today](http://www.usatoday.com/story/news/world/2016/01/31/boko-haram-attack-village/79623914/), [Forbes](http://www.forbes.com/home_usa/), and [NBC](http://www.nbcnews.com/health/health-news/dole-salad-recalled-after-listeria-kills-1-sickens-12-n502311). The expando support can be tested [here](https://www.reddit.com/search?q=site%3Agraphiq.com&sort=top&restrict_sr=&t=all).

Graphiq visualizations expando support

---

lib/modules/hosts/flickr.js

Fixes #2785 Adds support for flic.kr. When https://github.com/leedo/noembed/issues/60 is fixed we can remove some code

Fix #2785 - support for flic.kr shortlinks

---

lib/core/templates.html
lib/css/modules/_showImages.scss

New look when native controls are not active:

Video advanced controls only visible on hover

---

lib/modules/newCommentCount.js

Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2867
It appears a couple of issues were at play with this one.
* The `updateCommentCountFromMyComment` didn't check that the new comments added were actually by the user (so expanding a collapsed comment would run the `updateCommentCount` logic multiple times)
* The `updateCommentCount` was appending a new "new comments" section each time it got run
* Also, it was counting the numbers within the new comment section (since .textContent returned the child text to), which is why the numbers went so crazy.
Have refactored it a bit (mostly to get my head around it), and it all appears to be working correctly for me.
* `updateCommentCountFromMyComment` - new checks the user is logged in & made the triggering post, before …

Fix duplicating new comment counts

---

lib/browsersupport.js
safari/background.js

Safari and Edge set the status to 0 for local resources.
jQuery also tolerates this: https://github.com/jquery/jquery/blob/91850ecbbe04ad8f5d89dc050aa1d9002047c435/src/ajax/xhr.js#L16
Related: #2880

Tolerate status 0 for ajax requests

---

lib/modules/userTagger.js

[Issue report](https://www.reddit.com/r/RESissues/comments/4c43ww/bug_user_tagger_not_showing_in_sub_even_with/)
UserTagger breaks down when it finds a link formatted like so:
`[username](/u/ username)`

UserTagger breaks if author href preceded by space

---

appveyor.yml

This is already covered by Travis, and all we really need to know from Appveyor is that _something_ works on Windows, so remove the Node 4 test for performance.

appveyor: only test node 5

---

lib/core/templates.html
lib/css/modules/_showImages.scss
lib/modules/hosts/imgur.js
lib/modules/showImages.js

* Settings butto added to media controls
* Media controls now white on black
* Imgur Images/albums/gifvs link to imgur share page, optionally link to direct images instead
* imgur gif(v)s link to gifv, imgur can sort it out
* bring back clickable link on videos

ShowImages tweaks

---

lib/modules/showImages.js

Reduces the time before the first image is shown after clicking "Show images", since the `imageList` array may be unordered due to async media-hosts.

Sort imageList before showing all

---

lib/css/modules/_nightMode.scss

This has been a problem for me since forever. (Not anything to do with the recent night mode changes). The CSS selectors for code/pre tags aren't specific enough all the time.
I went into the inspector and copied out every selector which gave the code a light background colour, so I'm not sure if a couple of these are redundant, but what I do know is that it darkens the background for me as expected.

Fix night mode background colour of code in permalinked posts

---

lib/modules/showImages.js

And /subreddits/search. Not only are there no images to show, but it's adding a second tabmenu on that page.

Exclude showImages on reddit.com/subreddits

---

lib/css/modules/_commentBoxes.scss
lib/css/res.scss

Closes #2572.
Uses `border-color` instead of `outline`.

Update #2572: Improved commentHoverBorder

---

lib/modules/neverEndingReddit.js

Closes #2385.
Also happens to partially fix #2869 - by calling `togglePause` in `go()`, the message in the banner is properly updated when NER is paused.

Rebase #2385: Resume pause when clicking "Open Next Page"

---

lib/core/utils.js
lib/modules/noParticipation.js

for Edge compatibility. See #2880.
jQuery defers to `Element.prototype.matches` for [single-element](https://github.com/jquery/jquery/blob/055cb7534e2dcf7ee8ad145be83cb2d74b5331c7/src/traversing/findFilter.js#L47-L48) `$.fn.is` [where supported](https://github.com/jquery/jquery/blob/055cb7534e2dcf7ee8ad145be83cb2d74b5331c7/external/sizzle/dist/sizzle.js#L933-L939), so this should be effectively the same for the other browsers.

replace `Element.prototype.matches` with `jQuery.fn.is`

---

lib/modules/hosts/imgur.js

Fixes #2911.
This has the added benefit of ignoring size suffixes on 5-char ids.

imgur: allow exactly 5 or 7 char ids (not 6), and an [a-z] suffix

---

lib/css/modules/_nightMode.scss
lib/css/modules/_styleTweaks.scss
lib/modules/styleTweaks.js

Closes #2424. Fixes #2654.
Addressing this comment https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2654#issuecomment-172432168:
I'm not worried about the sidebar -- visitedStyle is disabled by default, so I don't think many people who enable it will mind.
I removed the `[name^="img"]` fallback style, so disabling visitedStyle disables it completely.

Rebase #2424: visitedStyle changes

---

webpack.config.babel.js

https://webpack.github.io/docs/configuration.html#devtool
Chrome seems to have issues with mapping filenames to the correct module or host when you browse through the files manually, but the error line numbers are translated correctly, which is the most important part.
i.e. showImages.js shows up as clyp.js:
But this line number is still correct:

Source maps

---

package.json

babel-plugin-lodash v3.1.2 breaks the build, so using v3.1.0.

package.json: Update deps

---

firefox/package.json

We don't use unsafeWindow anymore.
Closes #1744.

Firefox: remove `unsafe-content-script` permission

---

lib/modules/hosts/youtube.js

Catches significantly more types of link formats without any performance hit, allowing for most variations of Youtube links to be found. 
Also allows options to have a start / end time for the video. Previously only caught '&t=', but not '&start=' ? '&end=', now it catches all of them.
Also properly includes playlists by including the '&list=' parameter.

Youtube: More link formats & parameter options features

---

lib/core/init.js
lib/css/modules/_showImages.scss
lib/css/res.scss
lib/modules/hosts/defaultAudio.js
lib/modules/hosts/onedrive.js
lib/modules/keyboardNav.js
lib/modules/showImages.js
lib/modules/showParent.js
lib/modules/userTagger.js
lib/templates/audio.mustache
lib/templates/expando.mustache
lib/templates/gallery.mustache
lib/templates/image.mustache
lib/templates/mediaControls.mustache
lib/templates/text.mustache
lib/templates/videoAdvanced.mustache
lib/vendor/index.js

- Separated gallery from `generateImageExpando`
- Gallery requires an array `src`, which pieces it pipes into their respective generation functions
- Gallery preloads by default 2 pieces
- `buildExpando` is abstracted from `generate*Expando`, which creates a container it can put the media which is generated from `generate*` into
- All `generate*Expando` has been partially refactored to `generate$0`, and now only requires an options-object, and return a element
- `generateImage`, `generateAudio`, and `generateText` is now template based
- Methods `collapse` on `expand` allows the media to determine itself how to process these events
- The placeholder is replaced with setting the parent height
- When a media is resized, it will emit a `resize` event
- `rotateMedia` only hooks into the event …

Separate gallery from image

---

lib/modules/showImages.js

Limits `dragMedia` to at most one execution per frame.

ShowImages resizer: Reduce Firefox lag

---

lib/modules/voteEnhancements.js

The estimated vote count didn't have a space between the value and the label. This fixes it.

Fixed spacing between est. upvote count and label

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js

MediaControls can interfere with resizing (by triggering a `mouseout` event on hover).

ShowImages: Hide MediaControls when resizing

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/templates/image.mustache

Closes #2906.
Implemented with flexbox order, since there isn't a simple way to reorder elements in a moustache template (AFAIK).
~~Changed the default to `allAbove`, since the status quo is king (people hate change), and the problem it solves is very niche.~~
[after discussion in IRC] Keeps `titleAbove`; moves the option down next to `mediaControls` for discoverability. Hopefully that'll be good enough.

Update #2906: Captions position

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/templates/expando.mustache
lib/templates/gallery.mustache

Propagates the width of the expando-parent into the expandobox, so that text won't horizontally overflow.

ShowImages: Style fixes

---

lib/modules/showImages.js

The `conserveMemory` operation has become cheaper, so we may as well have it run more often so that expandos reload quicker.

ShowImages: ConserveMemory fixes

---

lib/modules/keyboardNav.js

KeyboardNav: Allow navigation when activeElement is 'a' or 'button'

---

lib/modules/hosts/twitch.js

As suggested in [this reddit post.](https://www.reddit.com/r/Enhancement/comments/2krgic/feature_request_any_possibility_of_working/)
~~For no apparent reason, it will ignore the `auto_play` parameter on videos (not streams) - so videos are muted instead.~~
http://reddit.com/domain/twitch.tv
http://www.twitch.tv/toadswoot/c/5388081
http://www.twitch.tv/producks/c/5378574?t=2m
http://www.twitch.tv/ellonija/b/588347589?t=1h18m54s
http://www.twitch.tv/ethotv/v/4488168
http://www.twitch.tv/producks
~~HTML5 is still half broken, no HTTPS support :(~~
~~Current issues: doesn't pause on collapse~~
https://github.com/justintv/Twitch-API/blob/master/embed-video.md

Twitch.tv expandos

---

lib/modules/hosts/eroshare.js
lib/modules/hosts/graphiq.js
lib/modules/hosts/strawpoll.js
lib/modules/hosts/uploadly.js
lib/modules/showImages.js

Removes the width restriction imposed on it by `.entry`, similar to videos and images.

showImages: Allow iframe overflow

---

lib/modules/hosts/soundcloud.js

This uses a different player that is similar, smaller, and does the same stuff. It also allows for a method to create the embeded player using a far simpler method.

Switch soundcloud to less bloated player, no ajax

---

lib/css/modules/_showImages.scss

Issue occurs on custom stylesheets where `.entry .flat-list` has no height.

Fix: Expando box not clearing .entry .flat-list

---

lib/modules/hosts/oddshot.js

Oddshot changed URL scheme to something like "shot/streamer/hash". Changed regex to match new and old URLs.

Fix oddshot.tv expando to work with new URLs

---

lib/css/modules/_showImages.scss
lib/modules/keyboardNav.js
lib/modules/showImages.js

Last implementation utilized Event.path, which Edge has not implemented yet. Also, relying only on `mouseup` and `click` for ending dragging is unreliable.
The new implementation allows both moving and zooming interchangeably without having to release the mouse button.

Simplify makeMediaMovable and makeMediaZoomable

---

lib/modules/neverEndingReddit.js

Uses div#siteTable in selector when finding post links on init of dupeHash.
This way links in div#siteTable_organic are ignored when marking duplicates.
See commentary at https://redd.it/4bsvpw

ignore spotlight box when initializing NER

---

lib/css/modules/_commentTools.scss
lib/css/modules/_userTagger.scss

...because it doesn't seem to make a difference (except in the preview, which is still inline-block), and breaks some stylesheets (like /r/Italy)
ref: https://www.reddit.com/r/RESissues/comments/4nqy5n/issue_shifting_items_on_link_bar/

userTagger: remove `display: inline-block` from .userTagLink

---

lib/utils/dom.js

Adds a padding at the bottom of the page before scrolling when the page otherwise is not long enough to have the element at the top of the viewport. Useful for keyboard navigation in linklists.

Fix scrollStyle 'top': Pad bottom when necessary

---

lib/modules/hosts/raddit.js

URL was pointing at (for example) https://radd.it//r/listentous/music?embed which is breaking some of the embedded playlisters.
Many thanks to whomever restructured all of this embed code.  Certainly not the code I remember!

Removed extra / from <iframe> URL

---

lib/modules/commentTools.js

When using auto-completion for subreddits and users, RES would automatically add a leading slash (/r/, /u/). This change enables support for new subreddit and user linking. Auto complete will now respect whatever the user types initially, so /r/ and /u/ are still supported.
I'm pretty sure no one has already opened an issue or PR for this.
I have verified this works in Firefox, for both comments and text posts, for users and subreddits. Since it's a very minor, one-line change, it should work the same in all other browsers.
It also looks like snudown has been updated to support missing leading slashes in comment/post previews, but hasn't made its way into release.

Added support for r/ and u/ prefixes for auto completion

---

lib/modules/search.js
lib/modules/settingsNavigation.js

Currently, since the current links (`#!settings`) begin with an exclamation mark `!` after the `#`, they cannot be relatively linked since reddit requires 'domains' to start with an alphanumeric character. 
So this is an invalid link:
`[RES Settings](#!settings)`
So I'm proposing changing to a valid link syntax:
`[RES Settings](#res/settings)`
So people on reddit can more easily link to reddit settings that work no matter what page (or page context level) you are viewing them from. 
This change is backwards compatible as well, so previous links will still work and be converted to the new format. The `hashComponents` doesn't have to be changed for this to work, but if it doesn't, it would greatly hinder the features discoverability.

Setting link that can be relatively linked (backwards compatible)

---

lib/core/migrate.js
lib/modules/showImages.js

Also sets default max-width to 100% of viewport, since it works fine with `keepMediaVisible`. In addition it sets default max-height to 95% of viewport, as most media otherwise would require scrolling.

showImages: Media max size (maxHeight, maxWidth) as percentage of viewport

---

lib/modules/hosts/imgur.js

https://api.imgur.com/changelog: `Imgur no longer generates webm. Removed the webm response from the Gallery Image and Image models.`

Imgur video: remove webm source

---

package.json

Until https://github.com/babel/babel/pull/3557 is merged and released.
This works for fresh installs, but it may not work if you've already installed a version of babel-traverse with the issue.
`npm-shrinkwrap` would guarantee this, but hopefully it'll be fixed soon and we won't need to resort to that.

TEMP: try to prevent babel-traverse from updating past 6.9.0 and causing issues

---

lib/modules/hosts/instagram.js

Fixes #2126 
~~They do have an oembed API, but it doesn't seem to support CORS.
This means that instagram videos won't work, but it's better than having to add another permission.~~
Test links:
https://www.reddit.com/domain/instagr.am/
https://www.reddit.com/domain/instagram.com/

Instagram expando support

---

lib/modules/keyboardNav.js

Combines `moveToParent` and then `moveDownSibling`.
I don't think `moveUpParentSibling` is necessary, as it would be the same as `moveToParent`. An symmetrical shortcut (`alt+k`) would be nice but I couldn't think of any good way to implement alternative shortcuts.
This reuses the `threadScrollStyle` option, as the action is similar. The option should probably also be used on `moveToParent`.

keyboardNav: New shortcut: Move to parent's next sibling

---

lib/modules/hosts/strawpoll.js

Strawpoll seems to redirect https://strawpoll.me to http://www.strawpoll.me breaking the embed on https. Updating link to www to avoid the redirect.

Fix strawpoll expando's

---

lib/modules/showImages.js

In Firefox the video bounding rect is not updated before the `loadedmetadata` event is emitted. This PR implmenets a fallback mechanism.
Fixes #3158

showImages: Use fallback mechanism to update placeholder

---

lib/modules/hosts/giphy.js

e.g. http://giphy.com/gifs/hot-heat-overheating-5xtDarIN81U0KvlnzKo

giphy: support urls with "tags" inline

---

lib/modules/backupAndRestore.js

It seems that Edge doesn't like binding to `location`

Fix reloading after restoring a backup in Edge

---

lib/modules/selectedEntry.js
lib/utils/Thing.js
lib/utils/dom.js

This makes `scrollStyle: 'middle'` compatible with more custom stylesheets.

selectedEntry: Use getBoundingClientRect instead of offsetTop to compare position

---

build/isBetaVersion.js
firefox/getVersion.js
firefox/package.json
package.json

For future release automation: since they'll be deployed to the same listing as stable RES, they need the suffix.

Firefox: append `beta` to beta version numbers

---

firefox/background.entry.js
lib/environment/alert.js
lib/environment/index.js

This should give us an idea if #3194 is common or not (in the beta); hopefully we don't have to fall back to simple-storage and its horrible instability :cold_sweat:.

Firefox: show alert when db cannot be created

---

.gitattributes
assets/RESbeta.eps
assets/RESpromo.eps
assets/RESuppercase.eps

https://github.com/Reddit-Enhancement-Suite/assets/pull/1
We're running out of Git LFS bandwidth...which apparently includes forks, CI checkouts, etc.
<sup>Git LFS is probably the worst thing I've ever inflicted on this repo :sweat:</sup>

Move large assets to separate repo

---

safari/background.entry.js

There is a fatal bug that causes the RES Safari extension to not work at all. Specifically, the extension would crash if it ever tried to open a non-Reddit URL in a new tab. The extension was guaranteed to do this 100% of the time thanks to the `onboarding` module, which automatically tries to open http://redditenhancementsuite.com/... in a new tab when RES starts up. Normally it only does this on first install, but since the extension would crash before it could record it had been run, it would try to do this every single time the extension tried to run, leading to a crash every single time.
The root cause of the crash was in the global page's 'openNewTabs` handler. It assumed that it was being passed a browser tab object when it was called by the global page message event handler …

New feature: Safari extension now supports Safari web browser

---

.travis.yml
build/deploy.js
package.json

Resolves #2728.
This does two things:
- For tags with an ~~odd minor version number~~<sup>1</sup> (to be used as beta releases), automatically builds and publishes the Chrome version to a beta listing
- ~~For *all* version number tags, builds all targets and uploads the artifacts to a new GitHub release~~ #3181
<sup>1: Actually, we might as well release all versions to the beta channel, so beta users don't have to switch back to the main extension for normal releases.</sup>
**Todo**

Automated beta releases (for Chrome)

---

lib/core/migrate.js

I noticed that Edge didn't migrate max size (`maxWidth` and `maxHeight`), perhaps because it came directly from 4.5 and still had the settings saved as strings. This should make it work either way.

showImages: Default image max size fixed migration

---

lib/modules/showImages.js

Safari does not expose `MouseEvent.movementX`, `MouseEvent.movementY`, and `MouseEvent.buttons`, which my implementation required. This provides a workaround in order to make `addDragListener` Safari compatible.
Please note that I have not had the opportunity to test this on Safari yet.
Fixes #3209

showImages addDragListener: Safari compatibility

---

firefox/background.entry.js
firefox/package.json

...now that it is stable.
Fixes #3052.

Update account switcher cookie removal for Firefox 48

---

lib/modules/showImages.js

next/prev is accessible via keyboardNav, and using them when filmstrip mode is active breaks the gallery

showImages: generateGallery: Move attaching next/more listeners

---

lib/utils/dom.js

The previous solution missed the reason why scrolling in certain situations is not desirable, and as such did not work as intended all the time.

Tweak scrollStyle middle

---

lib/css/modules/_userTagger.scss

(partially) Reverts honestbleeps/Reddit-Enhancement-Suite#3067
Turns out that this _is_ important (top border is cut off):

Partially revert "userTagger: remove `display: inline-block` from .userTagLink"

---

lib/css/modules/_subredditManager.scss

The elements in `#RESShortcutsEditContainer` may overflow when the browser is zoomed in, causing a horizontal window-scrollbar to appear.
Fixes issue mentioned in https://www.reddit.com/r/RESissues/comments/4wl5k2/bug_horizontal_scrollbar_appearing_in_firefox/

subredditManager: Avoid overflow when zoomed in

---

.travis.yml

This is [undocumented](https://docs.travis-ci.com/user/deployment/releases), but it should work because you can [pass through options](https://github.com/travis-ci/dpl#github-releases) to Octokit, which [supports prereleases](https://github.com/octokit/octokit.rb/blob/f58728da197c6810b9187d4aa87606dd030d65c8/lib/octokit/client/releases.rb#L51).

Travis: mark GitHub releases as prereleases

---

lib/css/modules/_showImages.scss

re #3269
Otherwise we lose expando icons in comments with the native types (selftext, video):
And for `.comment > .parent > &.linkImg`:

showImages: ensure we set `display: inline-block` on `.commentImg`

---

.travis.yml
appveyor.yml

https://docs.npmjs.com/cli/cache
https://docs.travis-ci.com/user/caching/
https://www.appveyor.com/docs/build-cache
This should hopefully speed up builds without any risk of caching outdated deps in `node_modules`.

Cache the npm cache on CI

---

lib/css/modules/_hover.scss
lib/modules/hover.js
lib/modules/userInfo.js

The previous content was shown until the new one is ready, which is confusing when it takes several seconds to fetch new data. This instantaneously replaces it with a loading indicator until the new content is ready.

hover: Indicate loading on async HoverInfoCard

---

lib/modules/filteReddit.js

Fixes #3285.
Previously, the toggle was added in `always()` to preserve legacy behaviour, where the toggle showed up everywhere, even on pages where filteReddit doesn't run. But this doesn't make much sense, because you're unlikely to want to toggle the NSFW filter while browsing a wiki page or something.

filteReddit: only add the quick toggle when the module is enabled and running

---

lib/core/init.js

...to facilitate loading things in `beforeLoad` and using them in `go` without needing a global
e.g. before
```js
let foo, bar;
module.beforeLoad = async () => {
foo = await something();
bar = somethingElse();
};
module.go = () => {
doSomething(foo);
doSomethingElse(bar);
};
```
after
```js
module.beforeLoad = async () => {
const foo = await something();
const bar = somethingElse();
return { foo, bar };  
};
module.go = ({ foo, bar }) => {
doSomething(foo);
doSomethingElse(bar);
};
```

Init: pipe return values through each lifecycle method

---

.travis.yml
appveyor.yml

Reverts honestbleeps/Reddit-Enhancement-Suite#3278
There have been about 20 builds each on Travis and Appveyor, and there's no noticeable difference in build time. Still ~5:30 on Travis and ~4:30 on Appveyor. The install phase specifically is also still ~90s in Travis.
Closes #3282

Revert "Cache the npm cache on CI"

---

lib/modules/showImages.js

Using parseFloat sometimes resulted in values such as 0.0113E-6px, which CSS doesn't support.

moveMedia: Use parseInt instead of parseFloat

---

lib/modules/newCommentCount.js

...and only show threads that have been explicitly subscribed to.
https://www.reddit.com/r/Enhancement/comments/4ym1di/
This is effectively an implementation detail, so I'm not sure why this was visible in the first place. I suppose you could stop tracking new comments for a thread, but it's not like the `(x new)` text is very intrusive ¯\\\_(ツ)_/¯
Related to but not an implementation of #1330

newCommentCount: remove the option to show all tracked threads

---

lib/css/modules/_hover.scss
lib/css/modules/_neverEndingReddit.scss
lib/css/res.scss
lib/modules/hover.js
lib/modules/neverEndingReddit.js
lib/modules/selectedEntry.js
lib/modules/subredditManager.js
lib/utils/dom.js

- Stores page restoration data in `window.history` state, and as such does not rely on `location.hash`
- Starts loading restored page in `beforeLoad`
- Uses `loadPromise` instead of boolean `isLoading`
- Uses `SelectedEntry.selectInitial` to select last element, which awaits `loadPromise` and new entries
- `handleScroll` now only checks if current scroll position will trigger new page load
Fixes https://www.reddit.com/r/RESissues/comments/4vyhsc/bug_never_ending_reddit_reloads_last_page_if_user/
Closes #3112  [edit 2016-08-24 --andytuba ]
Closes: @allthefoxes bug.. did it not get filed? https://www.allthefoxes.me/img/08/19-a16e.gif

NER: Clean-up and returnToPrev refactor

---

lib/modules/keyboardNav.js
lib/modules/selectedEntry.js

Resolves two issues around hiding links with a keyboard shortcut.
**Issue 1:** 
Null reference on pressing hide shortcut shortly after hiding or when no element is selected (this causes keyboard navigation to stop working). Quite an old issue, there was a post [here](https://www.reddit.com/r/RESissues/comments/40irwi/bug_issues_with_hide_shortcuthiding_submissions/?st=islzf9j7&sh=c3e95dd3) but it was deleted.
**Issue 2:**
Scrolling to the next item does not work nicely when hiding items, since after the item has been hidden the page content moves and the content that was previously scrolled to moves off screen. I've adapted larsjonsen's code to select the nearest item without scrolling after a hide.
https://www.reddit.com/r/RESissues/comments/4qc4xc/bug_hide_select_new_5_second_delay_hides …

Fix issues with Keyboard Navigation when `fixHideLinks` is turned off.

---

lib/modules/neverEndingReddit.js

Fixes #3371
Also fixes issue where `pauseAfterEvery` pauses based on it's previous milestone, instead of the page the unpause occured.

NER: Fix pause triggers and notifications

---

lib/css/modules/_userTagger.scss

Fix z-index so user tagger dialog shows above expando images
fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3383

[Bugfix] Fix user tagger dialog being behind expandos

---

lib/modules/hosts/youtube.js

Stopping will stop further loading / buffering, and also cancel autoplay of playlist.
Appears to fix
https://www.reddit.com/r/Enhancement/comments/50qnyj/announcement_res_v500_release/d78js0p
https://www.reddit.com/r/RESissues/comments/50xux9/bugproblem_with_youtube_playlists_in_expandos/

YouTube: Stop instead of pause video on collapse

---

lib/modules/keyboardNav.js

By request, since a lot of people became accustomed to it being broken (it always opened the link).
Future feature: Create alt-mode for links, perhaps so it can be opened or toggled depending on `shift` is pressed.
https://www.reddit.com/r/RESAnnouncements/comments/50qer8/announcement_res_v500_release/d79m058

keyboardNav commentLink: Create option for whether to toggle expando instead of opening link

---

lib/modules/showImages.js

When replacing `element` instead of `player` with the fallback, the expando will recognize the box as empty since `element` now is parentless.
Fixes https://www.reddit.com/r/RESissues/comments/5162cs/bug_duplicatingstacking_gif_when_opening_more/

showImages video: Fix sourceErrorFallback replacing the wrong element

---

lib/modules/showImages.js
lib/templates/videoAdvanced.mustache

Also tweak `sourceErrorFallback` a little so that the error reason is available.

Completely hide the video advanced bar when showVideoControls is disabled

---

lib/modules/neverEndingReddit.js

The `handleScroll` function was invoked via `togglePause`.
This also hides the toggle pause floater if `autoLoad` is disabled, and fixes option dependencies.

neverEndingReddit: Fix auto load option not always being acknowledged

---

lib/modules/keyboardNav.js

- So that `Event.preventDefault` won't be invoked when `commentsLinkNumbers` is disabled
- Provide alternative mode to invert `commentsLinkToggleExpando` action (toggle expando vs open in new tab)
Fixes https://www.reddit.com/r/RESissues/comments/518czp/bug_commentslinknumbers_interferes_with_single/

keyboardNav: Generate commentsLinkNumbers dynamically

---

lib/css/modules/_dashboard.scss
lib/css/res.scss
lib/modules/betteReddit.js
lib/modules/dashboard.js
lib/modules/filteReddit.js
lib/modules/hosts/raddit.js
lib/modules/newCommentCount.js
lib/modules/showImages.js
lib/modules/userTagger.js
lib/templates/tabMenuLink.mustache
lib/utils/createElement.js

- Adds  `filter visited links` and `show images` buttons back to the dashboard.
- Limits running the dashboard module to when visiting `/r/dashboard`
- It also changes of the tab menu buttons a little, as they were too structurally different from the native ones to always work as intended.
- Clicking on the padding didn't trigger a `change` event 
Side effects:
- In the gear menu, `my dashboard` is below `RES console settings` (this is IMO preferable)
- In the dashboard, the tab items are a little reordered and has different styles (as the style is defined in the subreddit stylesheet).

dashboard: fix tabs

---

lib/modules/commentTools.js
lib/utils/Thing.js

Fixes #3426: if the reference element (e.g. "add a comment" text area on top-level comment) isn't inside a thing, use the first visible thing and assume it's the main thing, e.g. on a comments page, the original post.  May need refining later.
also some incidental fixups

If element is not inside a thing, fallback to first visible thing

---

lib/modules/neverEndingReddit.js

Seems like using a URL-fragment increases usability.
This PR also changes the trigger for initiating `returnToPrev` from navigation.type to the existence of `#res:ner-page=\d?`.
Resolves https://www.reddit.com/r/RESissues/comments/51ecbw/question_how_to_reactivate_the_page_number_in_the/

neverEndingReddit: Expose page in URL

---

lib/modules/keyboardNav.js
lib/modules/neverEndingReddit.js
lib/modules/selectedEntry.js
lib/modules/showImages.js

By removing the mediaBrowse logic from the `move` function, it can easier by invoked by other select functions.
Fixes https://www.reddit.com/r/RESissues/comments/51nu5e/bug_images_not_autoexpanding_next_post_after/?ref=search_posts

Move mediaBrowse logic to showImages

---

lib/modules/newCommentCount.js
lib/modules/subredditManager.js

Don't track visits incognito

---

lib/css/modules/_showImages.scss
lib/modules/hosts/wikipedia.js

They take up much vertical space, and generally are unimportant in the this context.

Wikipedia: Hide citations

---

lib/modules/dashboard.js

Fixes #3357
There's an issue in a very specific situation in Edge where the jQuery handler gets dropped (the native `addEventListener` handler is correctly added by jQuery, but when it fires, the `handlers` array in `dataPriv` for the element is empty).
I can't be bothered to expend any more effort trying to figure out what causes this; it's extremely resistant to reproduction. Copying the entire `attachEditComponent()` function verbatim to Codepen, same version of jQuery and everything else? Nope, it all works as expected. Unsurprisingly, trying to hand-code a minimal reproduction is right out. Stepping through with the debugger is unenlightening; I can watch the listener get added correctly and the event fire correctly (to an empty array of handlers), but something is messing with the …

dashboard: work around Edge issue with jQuery

---

lib/core/init.js

It should not be possible for document.body to be null here, but it is for some Chrome users.
This should not affect performance when it's non-null, because `nonNull()` has a synchronous fast path for the initial check.

init: add extra null check for document.body

---

lib/modules/hosts/youtube.js

Fixes #3353.
Making the watch/embed not optional fixes this. Also moved the youtu.be in the regex to accommodate for this change.
So far this regex still works on every link I have tested:
```
https youtu.be
http youtu.be
https youtube/watch
http youtube/watch
https youtube/embed
http youtube/embed
https m.youtube/watch
http m.youtube/watch
```
And fixes the issue on the following links (as far as I know these are the only channel links):
```
/c/
/channel/
/user/
/[username]
```

Make channels not recognized as YouTube expandos.

---

lib/modules/commandLine.js
lib/modules/quickMessage.js

These aren't opened on the vast majority of pageloads, so creating them up front is mildly wasteful.
Bonus: quickMessage now has no (visible) global state.

Don't generate dialogs until they're used

---

safari/Info.plist

Resolves #3480
~~Haven't (yet) tested if `.plist` allows comments but it's just a subset of XML and the internet says it will.~~

Add Icon.png to Safari build

---

lib/core/modules/modules.js

So that if a module was somehow disabled (or `alwaysEnabled` was set retroactively) it still won't act disabled.
Fixes https://www.reddit.com/r/Enhancement/comments/54m9gp/im_trying_to_copy_my_res_preferences_between/ and other reports.

Move alwaysEnabled check to init

---

lib/modules/hosts/derpibooru.js

Apparently there's been some sort of issue with Russia's regulatory agencies which resulted in Derpibooru having to deprecate their `.ru` vanity URL. The API no longer works when accessed through the `derpiboo.ru` domain, and instead yields this message:
Example: https://derpiboo.ru/api/v2/images/show.json?ids=0
This PR updates the Derpibooru media host to access the API through the `.org` url instead.
Haven't tested this yet as I'm having a bit of trouble getting the build to work, but it's a rather trivial change so I'm fairly confident it won't break anything.

Use derpibooru.org as canonical domain for Derpibooru links.

---

lib/modules/easterEgg.js

Add `moduleID` and `notificationID` to notification object. This is needed to generate a proper class, see #3513 and #2835.

Add moduleID and notificationID to Konami notification object

---

lib/modules/hosts/ppy.js

Allows link with the osu.ppy.sh/ss/<id> format to be displayed with expandos.
Tested with https://www.reddit.com/domain/ppy.sh.
See [this /r/Enhancement post](https://np.reddit.com/r/Enhancement/comments/51zk40/feature_request_osuppyshss_screenshots_expandos/) for the feature request.

host : added osu.ppy.sh/ss/ expando

---

lib/css/modules/_showImages.scss
lib/utils/expando.js

The auto-scroll is an edge-case which happens fairly seldom (only when the clicked expando is a duplicate of an iframe expando which still is active).
Resolves https://www.reddit.com/r/RESissues/comments/54eu2q/autoscrolling_upward_when_a_duplicate_video_is/

expando: Show a "return to originating expando" button after auto-scroll

---

lib/modules/showImages.js

I'm setting it as advanced for now and defaulting to `false` since there's been some resistance to having this implemented. Nevertheless, it is useful, especially in conjunction with `hide visited links`.
Resolves #2781

showImages: Advanced option to mark selftext links visited

---

lib/css/res.scss

On Microsoft Edge, cursor showing up was the one for text editing,
instead of the one for active elements.

Fix wrong cursor on Prev/Next arrows in RES gallery

---

lib/modules/showKarma.js

- new module option: showGold (Display gilded icon if current user has
gold status)
- new module function updateUserSpan (If the user has gold and would
like to, display the gilded-icon in the user span.)
- basically borrow a bunch of JS from various functions to make
everything work smoothly.
- new import needed for nice date on hover
- also comments for things :)
____________________________________
Screenshot of freshly built plugin:
Passes lint & unit tests. 
edit: 
closes #1915

Display gold status in userbar( Closes #1915 )

---

lib/css/modules/_commentPreview.scss
lib/modules/commentPreview.js

Not as glorious as a solution as using flexbox layout, but just an overriding option that swaps the functionality of the .BELeft and .BERight css classes
Fixes #2306

Add ability to swap the preview and editor when using the big editor for comments / text posts

---

lib/modules/saveComments.js

Seems like the permalink got a trailing slash, so that `saveID` always becomes an empty string.
Fixes https://www.reddit.com/r/RESissues/comments/58mjna/bug_cant_res_save_comments_under_comments_it/

saveComments: Update ID

---

lib/modules/filteReddit.js

Added an option to the filteReddit module to prevent filtering of own posts unless explicitly disabled.
Closes #3018

feat(filteReddit): do not filter own posts

---

lib/modules/betteReddit.js

Instead of giving them a negative amount of time with incorrect pluralization.

Tell user to reload when score has been revealed

---

lib/modules/announcements.js

This change ensures the Alert icon is only active if an annoucement is not browser specific, or if an  annoucement pertains to the user's current browser.

Mute announcement alerts if they are not relevant.

---

build/version.js
package.json

It's fine to use `require()` in simple standalone Node scripts.

Remove unneeded deps

---

lib/modules/keyboardNav.js
lib/modules/showImages.js
lib/utils/expando.js

Also adds an option for whether to auto-expand the first **visible** non-muted (video, etc) expando in self-text posts.
Using `image text gallery video` instead of `any` as default value may be desirable.
Lays groundwork for #2540 
Fixes #3422
Resolves #3508

showImages: Create option for which media types to auto expand

---

lib/modules/quickMessage.js

Don't show QuickMessage is modifier key is pressed

---

chrome/manifest.json
edge/manifest.json
lib/modules/hosts/xkcd.js
safari/Info.plist

The problem with the noembed API Is that it returns invalid HTML for
certain comics that include quotes in the alt text.
Example:
https://noembed.com/embed?url=http://xkcd.com/1726/
https://www.reddit.com/r/programming/comments/5a5tba/utf8_everywhere_now_please/d9e0jzn/
Unfortunately the noembed repository does not seem to be very active
anymore, so I think the best solution is to fix this on the RES side by
switching to the official XKCD API.
Edit(erikdesjardins): fixes #3384

Change XKCD expandos to use XKCD API instead of noembed

---

lib/modules/betteReddit.js

Settings URLs in comments should be opened in the same tab even if commentLinksNewTabs is set.
I think this addresses the issue but I might've misunderstood the scope of this change. 
Closes #2968

Open settings URLs in same tab

---

lib/core/migrate.js
lib/css/modules/_orangered.scss
lib/modules/orangered.js

<as previously discussed>&nbsp;
This was erroneously turned on by a migration for some users.
The only reason it exists was to preserve legacy behaviour: in the past reddit didn't show a message count, so RES had an option called `showUnreadCount` which would generate one. When this was implemented on reddit's side and removed from RES, the option was inverted to `hideUnreadCount`.
But it's kinda silly, and I can't imagine why you'd want to hide the message count alone (without, e.g. also hiding the orangered envelope).
So in lieu of trying to migrate it back, we'll just remove it.
If anyone still wants to hide the message count, they can use a CSS snippet: `.message-count { display: none !important; }`
Resolves #3348

Remove hideUnreadCount

---

lib/modules/neverEndingReddit.js

Otherwise it is run after the `click` event, which may cause `replaceState` to replace the wrong entry if a link was clicked.

ner: run setReturnToPage at beforeScroll

---

lib/css/modules/_accountSwitcher.scss

Currently, whenever a user has a large number of accounts, the overflow div becomes the height of all of those accounts, causing the list expand beyond never ending reddit. This PR fixes the issue by adding overflow to the account switcher div.

Account Switcher Overflow

---

lib/modules/hosts/youtube.js

Since it's not yet implemented in Edge
Fixes #3504

Replace URLSearchParams() with getUrlParams()

---

lib/utils/Thing.js

It previously returned the link flair.

Thing: Fix getUserFlairElement

---

lib/modules/hosts/graphiq.js

It appears the graphiq url's had changed slightly meaning the a lot of the new graphiq urls were no longer expandable. Have added a fix + also added a fallback for when the oembed api doesn't return any data for a url (which appears to happen occasionally)
Tested against: 
https://www.reddit.com/domain/graphiq.com/

Fix graphiq expando

---

.travis.yml
nightwatch.conf.js

Sauce Labs lets us run 5 sessions in parallel, so let's take advantage of that.
Also, run the Chrome tests by themselves first (which are faster) and don't run Firefox tests if they fail.

[experimental] Speed up integration tests with multiple workers

---

lib/core/profiling.js

So it will show up in the Chrome and Edge debugger timelines

record module profiling with the performance timing API

---

lib/modules/betteReddit.js
lib/modules/dashboard.js
lib/modules/keyboardNav.js
lib/modules/neverEndingReddit.js
lib/modules/showImages.js
lib/utils/index.js
lib/utils/watchers.js

By manipulating the new `siteTable` before attaching it to the document, it is earlier ready and the webpage is more usable while it is processed.
Typical before (@ #3518):
Typical after:

Improve neverEndingReddit performance

---

lib/modules/styleTweaks.js

Fixes #3536
Will work in concert with #3528; swapping out the header image is slower than removing the stylesheet (because it's parsed later), so if the header is huge there will still be a flash of misaligned content (with this PR alone).

Swap out the header image when disabling subreddit style

---

firefox/package.json
lib/css/modules/_floater.css
lib/css/modules/_pageNavigator.scss
lib/modules/floater.js
lib/modules/pageNavigator.js
lib/vendor/index.js
package.json
yarn.lock

[IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) provides a cheaper way to check whether things should be shown. Note that it is available only in Chrome and Firefox Nightly, so a polyfill is used elsewhere. The old approach checks `scrollY`, which usually causes layout trashing and janking.
Changes tested on Edge, Firefox 52 and Chrome.
Resolves https://www.reddit.com/r/RESissues/comments/5bqca2/bug_initial_scroll_lag_after_comment_page_load/

floater and pageNavigator: Use IntersectionObserver instead of checking scrollY

---

lib/modules/neverEndingReddit.js

Fixes #3371
Always having the correct description in the progress indicator bar (instead of just on the first pageload; fixed a while ago) should be enough to avoid confusion.

Only show NER notification when clicking on the pause button

---

lib/modules/showImages.js
lib/utils/Thing.js

- Unload video when outside of `bufferScreens`
- Start playing video when at least `visibleThreshold` (%) of it is visible
- It will only check while it is within `bufferScreens`
- `maxSimultaneousPlaying` can be set to only have to have a given number playing at any time.
- Prioritized by: 1. Thing is selected. 2. Visibility.  3. Nearest top.

showImages video: conserveMemory & defer play until visible

---

lib/modules/hosts/xkcd.js

Fixes #3505
This does not affect security, just ensures that html-like formatting will be displayed instead of getting sanitized out.

Escape XKCD alt-text

---

lib/modules/filteReddit/browseContexts.js

Filter posts if today is before or on/after a certain date(time). Useful for filtering noise leading up to an event such as an election or hiding spoilers around a release date.
I opted for plaintext since momentjs has an excellent parser. A future update could add a `datetime` builderField to settingsConsole.

Date custom filter condition

---

lib/modules/profileNavigator.js
locales/locales/en.json

Relies on #2916 ([diff](https://github.com/erikdesjardins/Reddit-Enhancement-Suite/compare/webpack...andytuba:profileNavigator))
Ignore the 🔍 button, it's only half-implemented and stashed

Profile navigator

---

lib/css/modules/_userTagger.scss

To prevent it from overflowing comment taglines:
Before:
After:
Introduced by #3470 changing `display: inline-block;` to `display: inline;`.

Shrink user tagger font slightly

---

firefox/background.entry.js

This shouldn't need to be imported to use `ioService.newURI`

Firefox: remove unnecessary import

---

lib/modules/filteReddit/Filter.js

Otherwise it will needlessly invoke `refreshThing` when restored.

Filterline filter: Always remove from storage when empty

---

firefox/background.entry.js

This is already the case in Chrome, since `all_frames` is not specified https://developer.chrome.com/extensions/content_scripts
And 99% of the time it's an ad frame, which is mildly wasteful.

Firefox: do not run in iframes

---

lib/modules/filteReddit/Filterline.js

The current matched filter was erroneously ignored when a filter later in the array invoked `refreshThing`.

Filterline: Fix filtersToTest

---

lib/modules/submitHelper.js

Might need to be checked over, but as is, it's showing me that a post submitted an hour ago as being 7 hours old (I'm PST time). Looking at the JSON, it appears that the create_utc actually gives the local time.

Fix for already submitted notification display wrong time

---

lib/core/options/stage.js

So all #3690 callbacks in a module don't fire every time you save.

Don't stage options that haven't changed

---

appveyor.yml

With it, we don't get any tags (unless the previous commit was tagged), so we don't get accurate information for #3698.
Will verify that it doesn't notably increase build time.

appveyor: remove clone_depth

---

lib/css/modules/_filteReddit.scss
lib/modules/filteReddit.js
lib/templates/filterline.mustache

Technically it's an upside-down beaker instead of filter/funnel https://thenounproject.com/term/filter/101890/
Would the "equalizer" Batch icon be more appropriate? a la https://thenounproject.com/term/filter/103807/

Replace filterline "for all" icon with "filter" (upside down beaker)

---

lib/modules/subredditManager.js

When the `getMultiCounts` request is not cached, it will have to have to wait for Reddit to respond on the API request, which may take several seconds and holds up the `go` phase.

subredditManager: Do not await manageSubreddits

---

lib/css/modules/_filteReddit.scss

Otherwise it looked like this when hiding the Filterline

Filterline: Fix tab CSS

---

lib/modules/showImages.js

Only auto manage videos which uses advancedControls, otherwise is it too hard to determine whether a video's pause is intentional. If the video is not unobserved upon manual pause, it will automatically be unpaused on next tick.

showImages: Fix pause on non-advancedControls videos

---

lib/modules/hosts/flickr.js

Add support for properly embedding and crediting staticflickr URLs.
Right now when people link directly to the CDN copy of a flickr image (i.e. http://c1.staticflickr.com/9/8345/8186873856_5d36a04f3e_k.jpg) it doesn't pass the detect regexes.
This code allows the photo oembed data to be retrieved by: 
- extracting the photoid embedded within the staticflickr URL
- encoding it to base 58
- rendering it into a Flickr short url for noembed to consume 
This ensures the image is shown and that the credit is preserved.

Support for properly embedding and crediting staticflickr URLs

---

lib/modules/showImages.js

Running it ignores the possibility that expandos are manually closed.

showImages: Don't force updateRevealedImages on refresh

---

README.md

For development of the chrome extension. I loaded the wrong folder and got a hard-to-comprehend error.

Emphasize RES should be run from /dist/chrome

---

lib/modules/showKarma.js

It's noisy and breaks some themes e.g. Naut.

Don't display gold icon in user bar by default

---

lib/modules/showImages.js

It can also delete expandos which has not yet been attached.

showImages: Do not run conserveMemory while loading a new page

---

lib/modules/keyboardNav.js

https://www.reddit.com/r/RESissues/comments/5haafb/bug_move_to_top_comment_navigation_key_doesnt/

moveToTopComment should scroll

---

lib/modules/betteReddit.js
locales/locales/en.json

That could prevent someone from successfully finding this key later.

Fix a typo in betteRedditShowTimestampPostsDesc key

---

lib/modules/betteReddit.js
locales/locales/en.json

Since "left" is a separate word, not a part of "time".

betteReddit: Capitalize "Left" in betteRedditScoreHiddenTimeLeftDesc

---

lib/modules/showImages.js

Otherwise Reddit's stylesheet overrides `max-width` on comments pages
Fixes https://www.reddit.com/r/RESissues/comments/5hrlwk/bug_inline_image_max_width_max_height_no_longer/

showImages: Set maxSize styles as important

---

lib/modules/customToggles.js

customToggles: add nbsp in place of empty toggles

---

lib/environment/ajax.js
lib/modules/dashboard.js

I'm not too big of a fan of `ajax`'s error handling; any ideas for improvement?

dashboard: Use local ajax over $.ajax; ajax: Create AjaxError

---

lib/core/init.js
lib/utils/__tests__/async.js
lib/utils/async.js
lib/utils/index.js

Mainly allows `afterLoad` to run if the `load` event has already fired, if that ever happens (it should be impossible, except perhaps when installing the extension).
_Not_ intended to fix the strange issue where nothing works when the extension updates in Firefox, which is probably caused by the background page crashing/not running.

Init timing tweaks

---

lib/css/modules/_pageNavigator.scss
lib/modules/pageNavigator.js

Using `outerHeight(true)` is expensive since it causes reflow of the whole document, which on larger comment pages takes > 100 ms.

pageNavigator showLink: Avoid jank on initialization

---

lib/modules/filteReddit/postCases.js

Otherwise there will be no operator by default, which when not changed will cause RES to crash when the filter is executed.

customFilters postAge: Set default comparison operator

---

lib/modules/accountSwitcher.js

Fixes #3822
As #3822 predicted, all we need to do is remove the cookie and new modmail will start a new session on next pageload.

accountSwitcher: clear `token` cookie for new modmail

---

lib/modules/hosts/streamable.js

Appears to use fastly with tokens to pull the images now. API docs are out of date.

Update streamable favicon, old CDN offline.

---

lib/modules/hosts/youtube.js

Using the `stop` command resets the playback position to 0 (not the position specified in the URL), which often is more of a pain than having to load the iframe content anew.

showImages YouTube: Remove iframe when collapsing

---

lib/modules/neverEndingReddit.js
lib/modules/selectedEntry.js

It resolved when the the next page was fetched, rather than when attached. One of the apparent issues this caused was `SelectedEntry selectThingOnLoad` not being able to select things on page ≥ 2.
PR also fixes the issue where the `returnToPrev`modal sometimes is not shown.

neverEndingReddit: Only resolve loadPromise after appending to siteTable

---

lib/modules/keyboardNav.js

Seeing commands that one cannot use is usually confusing.

keyboardNav: Show help only for possible commands for page

---

lib/modules/selectedEntry.js
tests/selectedEntry.js

The previously implementation verified that the new comment should be selected by matching a parent Thing. This matches `.sitetable` instead.
Fixes https://www.reddit.com/r/RESissues/comments/5le5xq/active_selection_resets_after_using_the_enter/

selectedEntry: Fix onNewComments on outermost "load more comments"

---

lib/modules/hosts/imgur.js

fixes #3635 
on another note, should the host module itself maybe always make sure the request is being made over https? or are there hosts that don't support it?
edit (@erikdesjardins): closes #3451

updated imgur host to always load gif/gifv/mp4 over https

---

lib/modules/search.js

With just `frameThrottle` it still feels laggy.

Add extra throttling to "search on type" to reduce lag

---

lib/modules/submitIssue.js

The diagnostic info is added after the user leaves the textbox, and is removed (or injected if appropriate) if the user changes the "submit to" to a subreddit that doesn't want diagnostics.

Defer add diagnostics to self-text on submit page

---

lib/modules/hosts/youtube.js
lib/utils/location.js

Gets YouTube embed of live streams following a `https://www.youtube.com/channel/CHANNELID/live` format, addressing #3810 
Edit(@erikdesjardins): fixes #3810

Add Expando for YouTube live stream URLs

---

lib/modules/settingsConsole.js
tests/settingsConsole.js

Reordering a table option stages options

---

lib/css/modules/_wheelBrowse.css
lib/css/res.scss
lib/modules/wheelBrowse.js
locales/locales/en.json

Inserts a little widget into the floater, which when scrolled upon will selected the next/previous entry or gallery piece.
When the selected entry has an expanded gallery:
When scrolling in the red-ish area, next/prev will act on the gallery. The area will disappear after reaching the end of the gallery, so the next scroll will select the next entry.

New feature: Browse by wheel

---

lib/modules/filteReddit.js
lib/modules/filteReddit/postCases.js
tests/filteReddit.js

This is a first cut at removing the custom filtering logic
for the basic filters. There is still a transformation phase
that converts the value input from the user into different
filters used by the custom filter engine (group, currentSub, etc.).
These transformations are cached and then run just like the custom
filters during the filtering phase
fixes #2839

Transform standard filters into 'engine' filters

---

lib/utils/Thing.js

Since `Thing.getSubreddit` may be invoked on every `Thing` by all subreddit filters, caching the result significantly reduces the time spent on filtering. (In my case 350 ms → 120 ms)

Thing: cache getSubreddit result

---

lib/modules/commentHidePersistor.js

Fixes #3897
Reddit URLs generally contain all the unique canonical bits in the pathname, and the pathname stays constant. Query parameters, anchors, and  subdomain shouldn't affect whether a comment is hidden. It's debatable whether comments should stay hidden i when focused on a comment but that's outside the scope of this fix

Fix comment hide persistor by tracking via simply pathname

---

lib/modules/showImages.js

Fixes #3904 
The lookup url should be escaped because of the query string parameters.

Escape the lookup url during reverse image search

---

lib/modules/commentNavigator.js

It did not work nicely with `onScroll` since that assumes that the posts are ordered from top to bottom; `popular` sorts posts by score.

commentNavigator: Fix sortType popular

---

lib/modules/neverEndingComments.js
locales/locales/en.json

Added a Never Ending Comments module that by default only auto-loads
the "load more comments" link at the bottom of the page. There is an
option to also load these links for any child comments. When this is
enabled all links that are in the viewport are loaded, started from
the top. This causes lower links to potentially be pushed out of the
viewport and then not loaded until the user scrolls them down into
view again. On the other hand, it allows for nested "load more comments"
links to be loaded automatically as they appear.
fixes #3432

Never ending comments

---

lib/modules/keyboardNav.js

Before:
After (`useGoMode` on):
After (`useGoMode` off):

keyboardNav drawHelp: Show goMode commands properly

---

lib/modules/keyboardNav.js

Non-"GoMode" callbacks will check for goModeActive being false before firing. This will allow the reuse of key bindings for GoMode navigation without firing both events.

Change to allow reuse of hotkeys for "Go Mode" without double firing

---

lib/modules/keyboardNav.js
locales/locales/en.json

Adds /r/all to the "Go Mode" navigation. 
Includes changes from commit #3909 as well to prevent the 'A' hotkey for /r/all also firing the "Upvote" default hotkey.

Adds /r/all to the "Go Mode" navigation

---

lib/core/init.js
lib/modules/betteReddit.js
lib/modules/filteReddit.js
lib/modules/hideChildComments.js
lib/modules/keyboardNav.js
lib/modules/menu.js
lib/modules/neverEndingReddit.js
lib/modules/newCommentCount.js
lib/modules/noParticipation.js
lib/modules/saveComments.js
lib/modules/selectedEntry.js
lib/modules/showImages.js
lib/modules/singleClick.js
lib/modules/sourceSnudown.js
lib/modules/spamButton.js
lib/modules/subredditManager.js
lib/modules/subredditTagger.js
lib/modules/userHighlight.js
lib/modules/userTagger.js
lib/modules/voteEnhancements.js
lib/modules/xPostLinks.js
lib/utils/Thing.js
lib/utils/async.js
lib/utils/index.js
lib/utils/watchers.js

New watcher functions:
- WatchForThing: Used for enhancement which are Thing-centric
- WatchForElements (replaces `WatchForElement`): Used when changes doesn't act on Thing
Performance improvements:
- All callbacks are organized and executed based on visibility / distance from viewport on the initial execution, so that only things which can be seen are prioritized.
- KeyboardNavigation move functions are available earlier, and are more responsive
Minor bugfixes:
- SelectedEntry: If several selects occurred during 1 frame, listeners was invoked with the wrong `old` Thing
- scrollType `middle` didn't always scroll when transitioning to/from a collapsed Thing
- userHighlight `highlightFirstCommenter` and `autoColorUsernames` caused severe jank due to chunking
- newCommentCount only indicated …

Centralized batching

---

lib/modules/showImages.js

```
<andytuba> oh boo i can’t X to open a dupe expando?
<andytuba> i .. wait, this is weird
<andytuba> https://www.reddit.com/r/nononono/comments/5pw77s/ill_just_gracefully_hop_over_th_umphh/dcufk4b/?context=2&depth=3
<andytuba> vs https://www.reddit.com/r/nononono/comments/5pw77s/ill_just_gracefully_hop_over_th_umphh/dcudemn/?depth=3
<andytuba> the second version, if you select hedgecore’s comment then select db2’s parent comment you can’t X to open
<andytuba> on the first version you can’t X to open initially
```
It checked whether the expando was opened in the entire Thing element, which includes any child comment. Fixed by changing the scope to `entry`.

showImages: Fix toggleThingExpandos duplicate scope

---

lib/modules/newCommentCount.js
lib/types/reddit.js
lib/utils/Thing.js
locales/locales/en.json

Requested in Issue #3622 
If a user has subscribed to new comment notifications on a post, and the post has been edited since the last visit to that page, then a notification should show. This is optional and off by default.
NOTE: I've already pull requested this (#3764) but due to some issues with my organization, I'm doing it again.

Notify if subscribed post is edited

---

.travis.yml

This should be possible now that travis-ci/travis-ci#6720 and yarnpkg/yarn#1576 are both fixed. See also the [official Travis blog post about yarn](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn).

travis: Cache yarn (built-in) and node_modules

---

lib/core/module.js
lib/modules/RESTips.js
lib/modules/filteReddit.js
lib/vendor/guiders.css

FeatureTips are multi-step guiders which may (given they're configured to do so) show guiders the first time the feature appears.
- Refactors RESTips so that only the one to be shown is generated at initialization (this improves the first-run start-up time with > 1s)
- The first guider "About RES" attaches (as intended to) to the settings cog
- Guiders for Filterline

Clean-up RESTips, featureTips guiders (for filterline)

---

lib/core/host.js
lib/modules/showImages.js

For media hosts which need context like the post ID for
requesting preview images for posts.

mediahost.detect(mediaUrl, thingContainingLink)

---

lib/core/options/table.js

`key` has taken the role `name` had (#3842), so this needs to be updated.
I noticed the issue when `valueIdentifiers` was
```
{
"moduleID": "filteReddit",
"notificationID": "everyThingHidden"
}
```
and the function `getMatchingValue` returned
```
[
"filteReddit",
"filterSubreddit",
false,
false,
0
]
```
instead of `null`.

core options/table: Match 'key' instead of 'name'

---

lib/modules/commentHidePersistor.js
lib/modules/keyboardNav.js

Check if comment can be collapsed before collapsing it

---

lib/css/modules/_subredditManager.scss
lib/modules/subredditManager.js

I was working on a larger change, to add first-class support for `/r/`, `/me/m/`, and `/` prefixes, but find myself at a nice stopping point.

Hide subreddit shortcut alphabetize button when unusable

---

lib/modules/commentTools.js

This avoids matching textareas like the customFilters description, etc.

commentTools: inclusive rather than exclusive commentTextareaSelector

---

lib/modules/commentQuickCollapse.js
lib/modules/selectedEntry.js

Override the `from` element. Otherwise it will automatically be set to the hidden child element, which `scrollToElement` cannot determine the position of.
Video of the error https://www.youtube.com/watch?v=Ncw_2STgeYs&feature=youtu.be
@KetillG 
The reason this bug emerged, is that SelectedEntry listeners now receive the correct `unselected` Thing (i.e. the one last painted) instead of the one last selected.

commentQuickToggle: Fix wrong scroll when the selected thing is child of the collapsed

---

lib/modules/commentTools.js
lib/types/reddit.js
locales/locales/en.json

I've added a feature (requested in #3785) that enables the users to get autocomplete for wiki pages belonging to the subreddit they are currently on.
It works similarly to /r/ and /u/ autocomplete. For example, typing `/wiki/bette` on /r/Enhancement will result in `/index/ui/betteReddit` being suggested. If the user wants to link other's subreddit's wiki, they can write `/r/subredditname/wiki/...` to get the result from this wiki. 
As links to wiki are working in a slightly more complicated way than `/r/...` and `/u/...` links (plain /wiki/ won't work without prepending subreddit link), along with autosuggest item "shortLabel" (the one being displayed), I now pass url in `data-label` attribute.
It is then sent to a function that pastes autosuggestion into an input field. This function, …

Add autocomplete for wiki pages of current subreddit

---

webpack.config.babel.js

Oh yes, you read that right. The API itself. Not Firefox.
And I'm not talking about some fancy object rest destructuring. Oh no. Just plain old array destructuring. You know, the kind that Firefox 45 ESR has supported for the past 11 months.
😡

Workaround the AMO API's lack of support for destructuring

---

lib/modules/RESTips.js

On initial boot of RES, both featureTips and dailyTip are triggered. Since dailyTip is shown in `afterLoad`, but the Filterline featureTip is shown in `go`, the dailyTip hides the featureTip. This PR delays featureTips so the conflict is avoided.

RESTips featureTips: Avoid race condition with dailyTip

---

lib/modules/keyboardNav.js

`activeElement` may have default behavior which causes the RES to ignore the keypress, and as such not prevent it.
Fixes #3992

keyboardNav: Always blur if keypress has shortcut

---

.travis.yml

This probably won't make very much of a difference, since yarn packages are being cached, but it'll help with intermittent network issues for new packages.

travis: Install yarn in before_install

---

lib/modules/showParent.js

The vote score in the parent hover was moving in the wrong direction.

showParent: Fix the vote score after upvoting/downvoting

---

lib/utils/async.js

This so that `watchForThing` / `watchForElement` listeners will run even when the page is opened in the background.

frameThrottle: Run as ordinary throttle (via setTimeout) if document is hidden

---

lib/css/modules/_neverEndingReddit.scss
lib/modules/neverEndingReddit.js
lib/modules/selectedEntry.js

Reduces the time to return to prev page significantly, at the cost of ~0.4 MB per 100 loaded listings. 
Before:
After:
Closes #3402 
Closes #690

ner: Cache prevPage

---

.flowconfig
build/buildToken.js
chrome/environment.js
firefox/beta/package.json
firefox/package.json
lib/constants/localStorage.js
lib/core/init.js
lib/core/metadata/index.js
lib/environment/common/listeners.js
lib/environment/i18n.js
lib/modules/troubleshooter.js
locales/index.js
locales/locales/en.json
package.json
yarn.lock

This eliminates the effect of translations on bundle size (and hence parse/compile performance), at the cost of slow init on the first (ever) pageload on each domain or when switching languages.
Each dictionary is 64-100k, so we have quite a bit of localStorage headroom.

Move translations to background page; cache on foreground in localStorage

---

lib/css/modules/_submitIssue.scss
lib/css/res.scss
lib/modules/submitIssue.js
lib/templates/submitIssueDefaultBody.mustache
lib/templates/submitWizard.mustache

* Standard post selftext template for all RES subreddits: "what's up" and follow-up questions
* Move pre-edit wizard to guider attached to self-post
* Refactor current known issues and feature requests into "fetch yaml" and "render link list in guider template"

Submit Issue refactor and rephrase

---

lib/modules/showImages.js

Fixes https://www.reddit.com/r/RESissues/comments/5x1z8v/bug_clickjack_warning_on_video_expandos/ and other no-script warnings since elementResizeDetector won't be applied on iframes.

showImages: Don't apply elementResizeDetector when media is independent

---

lib/modules/voteEnhancements.js
locales/locales/en.json
tests/voteEnhancements.js

~~Since the uncertainty becomes extreme as the upvote percentage approaches 50%.~~
Edit: Actually, that still appears to have an unwarranted amount of precision.
We know that the one post had ~12k points and 51% upvotes indicated, but only ~50k votes overall. This means either upvotes are weighted ~1.5x higher than downvotes or upvote percentage is skewed by ~10% (probably a combination of both).
Either way, trying to calculate vote totals could definitely be called "misleading", even for posts with a more usual vote percentage. (They're so far from the real vote counts that no remotely accurate conclusions can be drawn.)
So we're just going to remove them.

voteEnhancements: remove misleading post vote estimation

---

lib/utils/keycode.js
package.json
webpack.config.babel.js
yarn.lock

It appears that this issue only occurs when an array containing a spread is immediately destructured.

Switch to targeted workaround for AMO API destructuring issue

---

lib/modules/userHighlight.js

This fixes a bug in userHighlight, where collapsed posts were still showing the highlighted color instead of gray. 
Originally, the selector used was `.tagline .collapsed`, when it should be `.collapsed .tagline`.
I also refactored a small part of the code.

userHighlight: change highlight color when collapsed

---

lib/css/res.scss

Small CSS addition to make it more obvious which module is selected in the settings console. (attempting to fix #4048.
Also, first pull request on an open source project ever, so let me know if I'm doing something wrong!

Add border to selected module in settings console

---

lib/modules/hosts/youtube.js

[https://redd.it/60jq6g](https://redd.it/60jq6g)
just appends "rel=0" to end of youtube embed links so the related videos bar doesn't come up when the video gets paused.

add "rel=0" to end of youtube embeds to get rid of related videos

---

lib/modules/subredditManager.js

Relevant issue: With long shortcut bars, the left scroll button appeared to be unresponsive. The math being done to find the shift distance could create a possible fractional value (0 < marginLeft < 1). Since marginLeft would have to be <= 0 to trigger the shift, it would fail in this case.
Tested in browser: Chrome 57.0.2987.110 (Arch Linux)

Fix shortcut bar left scrolling by using integer value

---

lib/modules/neverEndingReddit.js

The `Init.go` handler executed before `await Init.bodyReady` in `appendPage` was resolved. Since `appendPage` doesn't itself invoke the watchers, but relies on `Init.go` for that, the page must be appended before the `Init.go` handler is invoked.

ner returnToPrevPage: Fix watchers not being invoked on restored page

---

lib/environment/alert.js
lib/environment/index.js

Tested in browser: firefox 54.0a2
This was only used by the old Firefox backend, so is unnecessary after #4116

remove environment/alert.js

---

chrome/background.entry.js
edge/background.entry.js
firefox/background.entry.js
firefox/manifest.json
lib/environment/download.js
lib/environment/index.js
lib/modules/showImages.js

Relevant issue: fixes #3527
Tested in browser: chrome 59, firefox 54
This can't be used for the backup file download, because it doesn't work for blobs in Firefox. Ugh.

Use chrome.downloads for downloading in Firefox

---

lib/modules/keyboardNav.js
lib/modules/showImages.js

Relevant issue: `andytuba [8:21 PM] oh hmm keynav expando on a host which needs permissions doesn’t fire the permissions request dialog`
Tested in browser: chrome 59

showImages: trigger permission dialog on keynav expansion

---

chrome/manifest.json
edge/manifest.json
firefox/manifest.json
lib/core/init.js
lib/modules/about.js
lib/modules/hosts/codepen.js
lib/modules/hosts/deviantart.js
lib/modules/hosts/fiveHundredPx.js
lib/modules/hosts/gyazo.js
lib/modules/hosts/makeameme.js
lib/modules/hosts/onedrive.js
lib/modules/hosts/ppy.js
lib/modules/hosts/redditbooru.js
lib/modules/hosts/snag.js
lib/modules/hosts/tumblr.js
lib/modules/hosts/xkcd.js

Tested in browser: Chrome 59, Firefox 54
Many more details in commit messages, but basically:
- stop running on:
`http://redditenhancementsuite.com/*` (currently useless)
`http://reddit.com`, `http://*.reddit.com` (impossible)
`https://reddit.com` (redundant)
The mandatory permissions for these URLs are kept, so this is reversible.
- irreversibly remove some unused, http-only mandatory permissions:
`http://*.flickr.com/photos/*`
`http://img.photobucket.com/*`
`http://noembed.com/embed?url=*`
There's no reason we would use these in the future (over their https counterparts), especially now that adding optional permissions for hosts is trivial. Removing these means that users will only have to accept permissions for reddit.com and res.com when they install, which should placate some …

Cleanup permissions

---

.travis.yml

Closes #3624
It appears that Travis now installs yarn before the `install`/`beforeinstall` phases, so we aren't overwriting it anymore.

Remove explicit yarn installation

---

lib/utils/string.js

Elements must be owned by the current document for images to be preloaded.
Tested in browser: chrome 59, firefox 54, edge 15

Fix expando preloading

---

lib/modules/commentDepth.js
lib/modules/newCommentCount.js
lib/utils/__tests__/location.js
lib/utils/index.js
lib/utils/location.js

Relevant issue: #4128 
Tested in browser:  Chrome
Treats post-to-profile comments pages as regular comments pages, and some incidental cleanup.

Support r2-rendered post-to-profile comments page

---

lib/core/init.js

Tested in browser: Chrome 59, Firefox 54, Edge 15 (and this would totally break integration tests, so +1 each for Chrome and Firefox)

documentElement is always present at load

---

lib/core/init.js

Short-term hack until real compatibility is built.
Related to #4128

Disable RES if not running on r2

---

chrome/beta/manifest.json
chrome/manifest.json
edge/manifest.json
firefox/manifest.json
lib/modules/hosts/pixiv.js

...since loading an image 403s if it doesn't have a pixiv referer, which we can't easily spoof (and which wouldn't be particularly nice to do).
I suspect that this was always the case, and I fooled myself since the images were cached. Interestingly, even with a hard refresh + disabling the cache in the console, loading a cached image doesn't 403--it takes a full browser restart.

Pixiv: switch back to iframe embed

---

.travis.yml
appveyor.yml

Yarn 0.23.x changes the way integrity checking works, which breaks our CI install, but it also adds `--frozen-lockfile`, which is the behaviour we were emulating with the integrity check.
(I'm not sure if it was added earlier, so I doubt this will work in appveyor, but if so we can continue to use integrity checking there)

CI yarn install: switch to --frozen-lockfile

---

firefox/firefox.entry.js
firefox/manifest.json
lib/vendor/index.js

...since Chrome and Edge support it.

Move IntersectionObserver polyfill to firefox-only

---

lib/modules/subredditManager.js
locales/locales/en.json

Relevant issue: fixes #4127
(there are no situations where those links are displayed but the subreddit bar can't be found)

Update subreddit manager for front->home renaming

---

lib/modules/hosts/deviantart.js

e.g. http://ryanbullivant.deviantart.com/art/MLNCLY-676017093
...somehow these are different from normal images ¯\\\_(ツ)_/¯

deviantart: support "link" images

---

lib/modules/hosts/streamable.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/66vgh3/bug_controls_are_invisible_in_streamable_videos/
A few people are complaining about invisible controls, which I can't reproduce, but regardless, we can sidestep the issue by using their API directly.
As a bonus, we get nicer initial sizing and resizing.

streamable: use the API instead of iframe embed

---

build/deploy.js

It turns out there's no way to submit an Opera extension without review (unlike Firefox), and we now know that release automation works, so disable this for the moment to not inundate the reviewers.

Disable opera beta deployment

---

lib/modules/RESTips.js

Allowing both causes a conflict on first run.

RESTips: Avoid concurrent daily- and feature tips

---

lib/modules/keyboardNav.js

keyboardNav: Set followLinkTabFocus as unadvanced option

---

lib/modules/notifications.js

The fade was canceled when moving the cursor from the notification.
Fixes https://www.reddit.com/r/RESissues/comments/5j612x/notification_close_bug/

notifications: Fix manual close being disregarded

---

lib/modules/hosts/clyp.js
lib/modules/hosts/hastebin.js
lib/modules/hosts/jsfiddle.js
lib/modules/hosts/pastebin.js
lib/modules/hosts/soundcloud.js

Relative sizes stopped working back when iframe media was changed to `position: absolute`.

iframe: Use absolute width

---

.eslintrc.json
lib/modules/hosts/onedrive.js

Fixes #4180.
Change OneDrive API to [Shares API](https://dev.onedrive.com/shares/shares.htm), makes us resilient to URL changes and auth issues.
Tested on Edge 15.
(@erikdesjardins: and Chrome 60)

Swap OneDrive API

---

lib/css/modules/_filteReddit.scss
lib/modules/RESTips.js
lib/modules/filteReddit/Filterline.js
tests/RESTips.js

Opens the `filterlineVisible` featureTip guider

Filterline: Add 'show help' button

---

browser/background.js
lib/environment/ajax.js
lib/environment/xhrCache.js

This was only used before #4203 for onedrive, and it's a very strange thing to do. (Normally you don't care where the redirect is, as long as you get the content)

ajax: remove 'redirect' request type

---

lib/modules/neverEndingReddit.js

Relevant issue: Fixes #4200
Otherwise, both `firstLen` and `lastLen` would be from the same post, so we'd never add the CSS.

neverEndingReddit: check rank width before appending new sitetable

---

browser/background.js
chrome/beta/manifest.json
chrome/manifest.json
edge/manifest.json
firefox/manifest.json

Relevant issue: https://www.reddit.com/r/RESissues/comments/69nemw/subreddit_style_toolbar_button_tooltip_remains/

Give subreddit style pageAction correct titles

---

lib/modules/showImages.js

Unnecessary to resize when hidden, and `clientHeight` seemingly becomes unreliable.
Should fix https://www.reddit.com/r/RESissues/comments/69jdn8/expando_collapsed_after_fullscreen_youtube_with/
Tested in browser: Chrome 59, Firefox 55

showImages: Don't resize when child element is fullscreen

---

browser/foreground.js
lib/core/migrate/migrate.js
lib/environment/storage.js
lib/modules/RESTips.js
lib/modules/backupAndRestore.js
lib/modules/commentTools.js
lib/modules/onboarding.js
lib/modules/quickMessage.js
lib/modules/troubleshooter.js
lib/modules/userInfo.js
lib/modules/userTagger.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/69ljqu/firefox_reddit_sluggish_and_unstable_since_res/
`chrome.storage.local.set` is _absurdly_ slow in Firefox WebExtensions (the profile below would take just 30ms with `JSON.stringify`)
To mitigate this, store tags under individual keys, so all tags don't need to be saved at once.
As a bonus, we also don't need to _load_ all tags at once, bringing init improvements to all browsers.

Revenge of the Firefox Storage APIs 3: Tokyo Drift (tag sharding)

---

lib/utils/Thing.js
tests/hideChildComments.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/69soho/res_561_hide_child_comments_button_gone_after/
Tested in browser: Chrome 60, integration tests

Thing.getNumberOfChildren: support languages where the number of comments comes after the word

---

lib/core/migrate/migrate.js

Split off from #4221 so that the latter is non-destructive (in case something goes wrong with migration).

Migrator to remove old tag object

---

lib/modules/userTagger.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/69v2x3/my_user_tags_dashboard_has_ignored_symbols/

Fix reversed ignore icons on dashboard tags page

---

browser/foreground.js
lib/environment/id.js
lib/environment/index.js
lib/modules/version.js

Avoid concurrent installs warning for updates in Firefox

---

lib/utils/string.js

Relevant issue: fixes #4222, closes #4231
I don't think it's likely that we'll need the extra functionality afforded by `<template>` (lone `<tr>`, etc.), since `<tr>` will generally be embedded in another template rather than rendered standalone.

Fix mediaControls in Firefox

---

lib/modules/keyboardNav.js
lib/modules/neverEndingReddit.js
lib/modules/selectedEntry.js

When nothing is currently selected, auto select the top-most visible thing. When something is selected, and there are no further entries, load the next page.

keyboardNav move(Down|Up): Fix handling when nothing is selected / no target

---

lib/modules/neverEndingReddit.js

...like RES or Toolbox settings links.

NER: avoid clobbering non-NER URL hashes

---

lib/core/migrate/migrate.js
lib/modules/filteReddit.js
lib/modules/filteReddit/Filter.js
lib/modules/filteReddit/Filterline.js
lib/modules/keyboardNav.js
lib/modules/selectedEntry.js
lib/modules/showImages.js
lib/modules/userTagger.js
lib/modules/wheelBrowse.js
locales/locales/en.json

Moves `move` functions to selectedEntry
Moves mediaBrowse completely to showImages (as both wheelBrowse and keyboardNav invokes it)
Relevant issue: Closes #4246
Tested in browser:  Chrome 59

keyboardNav: reduce coupling with showImages and selectedEntry

---

lib/modules/subredditManager.js

**Relevant issue:** The hover menu for the subreddit manager gets reused after it's first creation, but doesn't update it's 'click' action references to the edit and delete button which tells it which subreddit to modify. So if you are trying to edit or delete subreddits, it will always populate the Edit window with the first subreddit that was hovered. 
**Tested in browser:** Chrome 59

Fixed referenced object on reused hover element

---

lib/modules/hosts/mixer.js

Beam is now called Mixer, Keep beam.pro domain for backwards compat.
Tested: Edge 15

Update Beam to Mixer

---

lib/environment/ajax.js
lib/modules/backupAndRestore/providers/GoogleDrive.js
lib/modules/betteReddit.js
lib/modules/dashboard.js
lib/modules/filteReddit.js
lib/modules/hosts/aarli.js
lib/modules/hosts/codepen.js
lib/modules/hosts/derpibooru.js
lib/modules/hosts/deviantart.js
lib/modules/hosts/flickr.js
lib/modules/hosts/futurism.js
lib/modules/hosts/giphy.js
lib/modules/hosts/graphiq.js
lib/modules/hosts/gyazo.js
lib/modules/hosts/photobucket.js
lib/modules/hosts/pornbot.js
lib/modules/hosts/redditbooru.js
lib/modules/hosts/steamcommunity.js
lib/modules/hosts/supload.js
lib/modules/hosts/tenor.js
lib/modules/hosts/tumblr.js
lib/modules/hosts/twitter.js
lib/modules/hosts/vidlit.js
lib/modules/quickMessage.js
lib/modules/showImages.js
lib/modules/sourceSnudown.js
lib/modules/submitHelper.js
lib/modules/subredditManager.js
lib/utils/thingMetadata.js

...instead of overloading `data`, which prevents you from adding query params for non-GET requests.
It should also be a bit more intuitive that a param called `query`, rather than `data`, affects the URL.

ajax: use separate `query` param for query params

---

.gitignore

Ignore npm5 package lock

---

lib/modules/subredditManager.js
locales/locales/en.json

So this does three things; two feature additions, of which I've been doing for a while with a hack and a stylesheet tweak, and one bug fix. 
1. Option to highlight a multi on the subreddit manager bar if at any of it's nested subreddits. So if I have a `Gaming` multi the target of `overwatch+leagueoflegends+dota2+heroesofthestorm`, if I'm on any of those subreddits, `Gaming` will get highlighted as if it were the current sub. For people that utilize the multi's mainly for the dropdown, this should make it more intuitive for them if they want to enable it. Also makes the next thing more useful. Example: https://gfycat.com/HatefulFalseFlicker
2. Allows for an alternative use of the dropdown to act as a normal, single subreddit with "related subs" in the dropdown. In use, it looks like this: …

Subreddit manager features

---

edge/background.entry.js

Tested in browser: Edge 15
This makes automatic backups feasible in Edge.
It's actually much less annoying than I thought it would be.

Edge: emulate noninteractive auth with a background tab

---

lib/modules/userTagger.js

The async operation is long and yields empty results far more often than not, so it makes more sense to load the user tag icon by default since adding them in often shifts around the whole page layout, then swapping it out for a tag if it exists.
The user tag icon appears anywhere between 500ms - 1500ms faster doing it this way from my tests. Makes the page feel fully loaded much more quickly.
Tested in Chrome 60

Slight change to help speedup user tag loading

---

browser/utils/auth.js
chrome/background.entry.js
chrome/beta/manifest.json
chrome/manifest.json
edge/background.entry.js
edge/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/environment/auth.js
lib/modules/backupAndRestore/providers/Dropbox.js
lib/modules/backupAndRestore/providers/GoogleDrive.js
lib/modules/backupAndRestore/providers/OneDrive.js

Part of a saga (#4280). This, more-or-less, is the solution I was looking for.
For some inexplicable reason, Chrome's implementation of `chrome.identity.launchWebAuthFlow` runs the flow in a separate context which doesn't preserve cookies across browser restarts. This makes noninteractive auth pretty much useless, because it's only noninteractive for the current session (so you might as well just store it in memory...).
Normally, you couldn't use `fetch` to resolve the redirect, since the hash is not exposed in the response. However, we're an extension, and we have access to `webRequest.onBeforeRedirect`, which _can_ read the hash from redirect URLs. So that's exactly what we do.
Doing it this way also allows us to use res.com for all …

Emulate auth flow in Chrome to fix logout after browser restart

---

lib/core/migrate/migrate.js
lib/css/modules/_newCommentCount.scss
lib/environment/storage.js
lib/modules/newCommentCount.js

This should prevent that one instance overwrites another, as sometimes can be seen by `updateCommentCountFromMyComment` sometimes being ineffective.

newCommentCount: Clean-up and concurrency fix

---

browser/utils/__tests__/messaging.js
browser/utils/messaging.js
lib/environment/storage.js

So now we get (somewhat) proper stack traces from the background page. Every browser has a fun nonstandard `Error` implementation, but this works in all of them (at least, it's no worse than it was before).
Before:
After (stack):
After (no stack):

Messaging: stop wrapping errors

---

lib/core/migrate/migrate.js
lib/modules/commandLine.js
lib/modules/menu.js
locales/locales/en.json
tests/menu.js

Changed the Settings gear icon's click action to open the settings panel, not toggle the hover state of the menu. No other hover menu appears to have this behavior and I find it unintuitive and find myself accidentally closing the hover menu trying to click the cog.
Relevant issue: UX consistency 

Settings gear icon click action change for consistency

---

lib/utils/__tests__/location.js
lib/utils/location.js

Since filteReddit naively uses the first matching regex, which for duplicates pages was `subreddit`, that subreddit's filterline was applied — which I've found in most cases is undesirable

new location: duplicates

---

lib/core/migrate/migrate.js
lib/modules/commentHidePersistor.js
lib/utils/Thing.js

Like in #4298, fixes multiple instances overwriting each other.

commentHidePersistor: Simplify logic, convert to watchForThing

---

lib/modules/betteReddit.js
lib/utils/thingHide.js

Moves rewriting the `hide` / `unhide` text to `thingHide.js` (which Filterline uses), so that the text always matches the current state.
From #4191

Use common interface for hide/unhide

---

lib/modules/RESTips.js
lib/modules/filteReddit.js
lib/modules/filteReddit/Filterline.js
lib/vendor/guiders.css

The guider refers to functionality in the dropdown, so it is nice being able use it without closing the guider.
From #4191

RESTips: Increase z-index so that dropdowns are above guider

---

lib/css/_zindex.scss
lib/css/modules/_userTagger.scss
lib/modules/userInfo.js
lib/modules/userTagger.js
locales/locales/en.json

This is particularly useful for anyone that wants to disable `showTaggingIcon`, but still wants to be able to easily tag someone. With this change, the _Tagging_ icon will appear on the _User Info_ popup, even if `showTaggingIcon` is disabled.
Required a little _z-space_ adjustment of the popups to prevent the _Tagging_ popup appearing below the _User Info_ popup.

Allows userTagger to be used within userInfo popup

---

browser/background.js
lib/environment/storage.js
lib/modules/backupAndRestore.js
lib/modules/backupAndRestore/providers/Dropbox.js
lib/modules/backupAndRestore/providers/File.js
lib/modules/backupAndRestore/providers/GoogleDrive.js
lib/modules/backupAndRestore/providers/OneDrive.js
lib/modules/backupAndRestore/providers/Provider.js

Relevant issue: closes #4309
Tested in browser: Chrome 60, Firefox 53
Two main things:
- set the timestamp forward locally first, and store it in the backup (instead of using the host's metadata), so the remote doesn't spuriously get "ahead" of the local time (FTR: this is basically @larsjohnsen's original implementation)
- CAS the last check timestamp so definitely only one tab will be restoring (this, combined with the previous point, is simpler and should be equally sound as doing it on the background page)
Also go to the options page if the user cancels restoration.

automatic backups: make backup/restoring fail-safe

---

lib/modules/hosts/wikipedia.js

The Unicode renderings and LaTeX code for math symbols in Wikipedia articles are removed from the HTML that is rendered by the Wikipedia expando, leaving just the fall-back images. This makes it easier to read and is less cluttered.
This is what it looked like before:
This is what it looks like with the patch applied:
Relevant issue: #4319 

Fixes Wikipedia expando issue with LaTeX for math formulas 

---

chrome/beta/manifest.json
chrome/manifest.json
edge/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/core/init.js
lib/core/modules/modules.js

So that we run nothing at all on those pages. I should've done #3795 this way originally.

Use exclude_matches instead of cancelling init at runtime

---

lib/modules/showImages/expando.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/6iw03n/two_media_expandos_per_post/
Only the two selector changes will be backported for the hotfix.

Expandos are no longer direct children of .entry

---

lib/modules/commandLine.js
lib/modules/keyboardNav.js
locales/locales/en.json

Closes #2211 
Tested in browser: Firefox 54.0, Chrome 59.0.3071.109
This PR adds:
1. A "/" keybinding to focus the cursor on the search box anywhere on Reddit.
2. Two new commands on the RES Command Console
The two new commands are
1. `s[earch]: <query>` - Search current subreddit (if any) or all of Reddit for "query"
2. `sr: <query>` - Search all of Reddit for "query"
Any thoughts?

Add Search Keybinding & RES-Console Commands

---

lib/modules/backupAndRestore/providers/GoogleDrive.js
package.json
yarn.lock

`atob` doesn't support unicode
Fixes #4353

GoogleDrive: Use external lib to decode Base64

---

lib/core/migrate/migrate.js
lib/modules/commentHidePersistor.js
lib/modules/newCommentCount.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/6nn2kb/does_580_feel_slower_to_you/; related to #4348 (this is a more aggressive implementation)
~~Note: not yet tested, at all~~

newCommentCount: use sharded storage only for comment counts, not subscriptions

---

lib/modules/styleTweaks.js

Relevant issue: fixes #4352 
Tested in browser: Chrome version 59 on Linux
The redditname class name is there for the h1 in in the subreddit page and but not in the user page.

Don't show use subreddit style checkbox on user pages

---

edge/edge.entry.js
lib/modules/floater.js
lib/modules/pageNavigator.js

Fixes https://www.reddit.com/r/RESissues/comments/6po6q2/how_do_i_get_rid_of_this_bar_it_wont_go_away/
The issue may have been due to `entries[0].intersectionRatio === 0` not being sufficiently precise to determine intersection.

Fix showLinkTitle and floater not hiding on creeping intersection

---

lib/modules/stylesheet.js

Reddit fixed the issue on their end; the old implementation is faster and simpler. It's fine if we don't cache as long as we don't hammer the endpoint (which won't happen unless there's a default value).

Revert stylesheet loading changes

---

lib/utils/async.js

Firefox 55 implemented `requestIdleCallback`, but it does not work from the extension's environment.
`TypeError: 'requestIdleCallback' called on an object that does not implement interface Window.`
Fixes https://www.reddit.com/r/RESissues/comments/6sqk1x/update_to_firefox_55_breaks_message/
Tested in browser: Firefox 55, Firefox 57

Fix selectedEntry in Firefox > 54

---

lib/css/modules/_nightMode.scss

Fixes part of #4385 
When selected:
When not-selected:

Nightmode for xposts

---

lib/modules/neverEndingReddit.js

When clicking the widget, the action being initiated can viewed, so it is scrolling to the widget is unnecessary.

ner: Don't scroll when clicking on load next page

---

lib/modules/userHighlight.js

Adds highlight support to names on xpost module.
For admins the A is coloured reddit side.
Fixes part of #4385

Add user highlight to new xpost system

---

lib/css/modules/_nightMode.scss

Fixes #4381 
`!important` is required because of its use on reddit's side.

Add nightmode support for pinned video

---

lib/modules/subredditTagger.js

The crosspost pulls the inner html from the .thing to construct the recommended title. Moving it outside of the <a> tag fixes the problem. 
http://i.imgur.com/jqm3ttc.png

Fixed sub-tagger interfering with new "crosspost" function

---

lib/modules/accountSwitcher.js
locales/locales/en.json

Prompts the user for a PIN if 2FA is marked enabled for the selected account.
Closes #4403

accountSwitcher: Add 2FA support

---

firefox/beta/manifest.json
firefox/firefox.entry.js
firefox/manifest.json

Remove URLSearchParams shim in Firefox

---

lib/modules/hover.js

Fixes #3494.
Due to the extra padding on the selected navbar item, the hover div overlaps the selected item div when it is visible. This causes the `mouseleave` event to be fired (as seen [here](https://jsfiddle.net/1LwqLdsm/1/)). To fix this, I added a check before calling Hover.close() from the `mouseleave` event, as well as remove other unnecessary calls to Hover.close().
Relevant issue: #3494

Prevent Hover from closing when mouse is inside selected item

---

lib/modules/hosts/gfycat.js

Relevant issue: Updating regex for parsing gfyid from details page.
Tested in browser: Chrome 61.0.3163.91

Gfycat detail route regex.

---

lib/core/migrate/migrate.js
lib/css/_zindex.scss
lib/css/modules/_hover.scss
lib/css/modules/_userInfo.scss
lib/css/modules/_userTagger.scss
lib/modules/RESTips.js
lib/modules/commandLine.js
lib/modules/commentTools.js
lib/modules/hover.js
lib/modules/troubleshooter.js
lib/modules/userInfo.js
lib/modules/userTagger.js
locales/locales/de.json
locales/locales/el.json
locales/locales/en.json
locales/locales/en@lolcat.json
locales/locales/en@pirate.json
locales/locales/en_CA.json
locales/locales/en_GB.json
locales/locales/es.json
locales/locales/es_419.json
locales/locales/he.json
locales/locales/it.json
locales/locales/pl.json
locales/locales/pt.json
locales/locales/pt_BR.json
locales/locales/pt_PT.json
tests/RESTips.js
tests/userInfo.js
tests/userTagger.js

- When modifying a users tag, change is reflected on all instances of that tag
- `votes` is splitted into `votesDown` and `votesUp`, so it will be more useful for a future `userVoteWeight` filter
- VoteWeight is more useful: The opacity is the proportional to the ratio of the sum of votes to total number of votes.
- Utilizes `Hover.infocard` for tagging dialog
- `Tag` can be reused for a future subredditTagger module
- Performance improvement by cloning exisiting tag icon
- Always show voteWeight tooltip - remove minimially useful option
- Make the 'saveSourceLink' option useful
- Fix tagging via cli
Tested in browser: Chrome 61

userTagger: Clean-up, split votes into ups and downs

---

lib/utils/dom.js

Relevant issue: Fixes #4420 
This changes `getViewportSize` to use `document.documentelement.client[Width|Height]` instead of `getBoundingClientRect`, which was sometimes giving the size of the entire document instead of the size of the viewport.
I chose the new technique based on [this Stack Overflow answer](https://stackoverflow.com/questions/1248081/get-the-browser-viewport-dimensions-with-javascript/8876069#8876069). However, I'm pretty apprehensive about the change, since there appear to be a few different approaches and they don't seem to be terribly well documented.

Fix inaccurate viewport size in certain subreddits

---

lib/constants/sessionStorage.js
lib/core/migrate/migrate.js
lib/modules/RESTips.js
lib/modules/pageNavigator.js
lib/modules/selectedEntry.js
lib/modules/showParent.js
locales/locales/en.json

Since several modules now depend on `selectedEntry`, it's probably best to set it to `alwaysEnabled` in order to reduce complexity.
A new style `line` is added, as a less obtrusive alternative to outline and highlighting:
Users that earlier have disabled the module will be migrated to use it.
Tested in: Firefox 57, Chrome 62
Re-creating the PR since I accidentally deleted the branch so #4355 became closed.

selectedEntry: Set always enabled, add style "line"

---

locales/locales/en.json

Relevant issue: Previously was "Convert Gifsto Gfycat" fixed to "Convert Gifs to Gfycat"
Tested in browser: Not tested

Small language fix

---

lib/modules/usernameHider.js

Hey there. I noticed that if you tag yourself (which i started doing so i could find my comments more easily), and you have user-name hiding enabled, the normal margin between the name and the tag is missing:
Simply copying the `margin-right` value from reddit's own `a.author` rule seems to fix it.
Tested in browser: Firefox 56

Give hidden user names the same right margin as non-hidden ones

---

edge/edge.entry.js
edge/remove-fetch.js
package.json
yarn.lock

Tested in browser: Edge 16 (16257)
Effectively closes #4096, we'll remove the remaining individual polyfills as necessary

Edge 16: remove unnecessary polyfills

---

edge/edge.entry.js
lib/utils/async.js

Tested in browser: Chrome 60, Firefox 55
It appears that requestIdleCallback now works in extension context in Firefox

Move requestIdleCallback shim to be Edge-specific

---

edge/edge.entry.js
edge/remove-fetch.js
package.json
yarn.lock

Tested in browser: Edge 16
re #4431
As it turns out, `fetch` was only fixed on the background page, not the foreground...

Edge polyfill fixes

---

lib/modules/betteReddit.js

Since it wouldn't be done otherwise, sometimes letting audio continue playing in the background.
Relevant issue: https://www.reddit.com/r/RESissues/comments/73ie7w/videos_keep_playing_after_hiding_the_post/

hideLink replacement: Collapse native expando manually

---

lib/modules/hosts/imgur.js
locales/locales/en.json

- Add new imgur option to use gif in place of gifv for imgur links
- Update imgur host to use new option to either request gifv or gif
Relevant issue: fixes #1803

imgur: option to prefer gif over gifv (#1803)

---

lib/css/modules/_showImages.scss

Made the selector stricter so that only expandos that are siblings of NSFW/spoiler post title divs will get candystripe.
Relevant issue: fixes #4016

Don't add candystripe inside spoiler selfpost text

---

lib/modules/hosts/wikipedia.js

When parsed by jQuery it would start fetching images which quite often wouldn't be displayed.
Tested in browser: Chrome 63, Firefox 56

showImages: Don't preload Wikipedia resources on handleLink

---

lib/modules/noParticipation.js

Manually reverting a vote shouldn't trigger the No Participation notification.

Don't notify No Participation when reverting vote

---

chrome/beta/manifest.json
chrome/manifest.json
edge/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/modules/hosts/onedrive.js

Tested in browser: Chrome 60, Edge 16
After #4203 we no longer need to use non-CORS endpoints.

Remove now-unnecessary onedrive.live and 1drv permissions

---

lib/modules/keyboardNav.js
locales/locales/en.json
tests/commentNavigator.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/72i8hf/feature_request_keyboard_navigation_shortcut_to/
Potentially conflicts with the goMode shortcut (go to your own profile) for users that have disabled the prompt, but thanks to @larsjohnsen we now have the capability to deconflict it.

Keyboard shortcut to navigate to author's profile

---

CONTRIBUTING.md

Relevant issue: None. Was going through Contributing doc as a new contributor and saw that the path to get to Chrome extensions had changed from Menu -> Tools -> Extensions to Menu -> More tools -> Extensions.

Update Contributing doc to match new Chrome menus (Tools -> More tools)

---

chrome/background.entry.js
edge/background.entry.js
firefox/background.entry.js
firefox/beta/manifest.json
firefox/manifest.json
lib/constants/localStorage.js
lib/environment/auth.js
lib/modules/backupAndRestore.js
lib/modules/backupAndRestore/providers/Dropbox.js
lib/modules/backupAndRestore/providers/GoogleDrive.js
lib/modules/backupAndRestore/providers/OneDrive.js
lib/modules/backupAndRestore/providers/Provider.js

As mentioned in #4376 , currently when there's more than one Google account logged in, RES does not remember which account it should use to backup to Google Drive, constantly asking you.
This PR fixes this issue by adding a `login_hint` field in the auth request. This requires an additional `https://www.googleapis.com/auth/userinfo.email` scope in the auth request.
The user's Google email address used to backup or restore for the first time is saved to local storage and re-used for subsequent backups or restores.
If the user logs out of the Google email address saved in local storage, then the local storage email address cache is invalidated and then re-written after the user re-authenticates with a Google account.
Relevant issue: Fixes #4376 
Tested in browser: Firefox 56, Chrome 61, …

Google Drive backup provider: Remember which account to use if there are multiple Google accounts logged in

---

lib/modules/commentNavigator.js
lib/modules/userInfo.js
locales/locales/en.json

Relevant issue: Adds feature and resolves #1442
Tested in browser: Firefox Developer Edition (Aurora, 57.0b8)
This change adds a setting, Auto-IAmA (`true` by default), which is dependent on Comment Navigator's `showByDefault`. When both are enabled, Comment Navigator appears automatically set to the IAmA setting when the user is browsing comments on r/IAmA or r/casualiama.
Notes:
- I had some issues running Flow check. I'm hoping someone can help if the Travis CI build fails.
- I hope my method of preventing auto-scroll-to-first-comment on page load is not too janky.
- Can someone confirm if I should just copy my new user facing strings as-is to the other localization files?

Adding Comment Navigator feature - "Auto-IAmA"

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/modules/showImages/expando.js

- Sets the height of the button to match the line-height in order to avoid mismatched line-heights
- Makes it resist subreddit-style `float`.
Tested in: Firefox 58, Chrome 63

showImages inline expando button: Improve positioning

---

lib/modules/keyboardNav.js
lib/modules/selectedEntry.js
locales/locales/en.json

Shortcut: Ctrl+Z
I fairly often see something interesting just after starting to press the jump to the next comment thread-shortcut, so it's nice to have a way to quickly return to that position.
Tested in browser:  Chrome 63

keyboardNav: Move to the previously selected thing

---

lib/modules/keyboardNav.js
locales/locales/en.json

This resolves #2466.
Tested in browser: Firefox Developer Edition (57.0b10).
Pressing 'e' triggers the edit button under a selected comment or self-post, currently enabled on comment and profile pages.
I am not all that familiar with the codebase, so I may have missed things. I hope it doesn't break existing functionality. Do the current integration tests support any way of testing features that require the user to be logged in?

Adding keyboard shortcut to edit selected comment or self-post

---

lib/modules/commentPreview.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/75zy7i/live_preview_locks_to_first_reply_never_updates/
Reddit appears to clone to the top-level textarea, so if we've already added a preview box there, initialization would bail out and no listeners would be added for the child textarea.

Fix commentPreview getting stuck with top-level textarea contents

---

lib/css/modules/_userTagger.scss

re #4382
Tags either get a specific color as an inline style (which works) or `color: "inherit"`, which makes them grey in taglines, since .RESUserTag (the parent) inherits the tagline color.
@larsjohnsen if reverting this line breaks something else, there are other ways I could fix this

userTagger: move color back to parent element

---

firefox/background.entry.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/78iyos/new_ushiftu_shortcut_opens_a_user_profile_in_a/
Tested in browser: Firefox 56, Firefox 58.0a1 (2017-10-22)

Firefox: open new tabs in the same container

---

browser/background.js
lib/utils/Cache.js
lib/utils/index.js

Since the `LRUCache` doesn't need all of the methods of `Map`, and has some type differences, it seems to make more sense to use composition over inheritance.

Cache: Rename to LRUCache, and make typing stricter

---

.eslintrc.json

Relevant issue: fixes #4461 
I added a `no-restricted-syntax` value with an AST selector that looks for object property names with spaces in them.
Running the lint there are ~60 errors thrown. Some of them seem reasonable, like test names.
Is there a good way to restrict this rule to only directories where we care about not having spaces in property names?

added custom lint rule for property name spaces

---

lib/modules/sourceSnudown.js

Since this button is created for every thing, it is a lot faster to have it cloned than parse-generated.

sourceSnudown: Optimize button generation

---

lib/modules/commentNavigator.js

Relevant issue: fixes #4512 
Tested in browser: Chrome, Firefox
When you upvote something it changes css classes from 'up' to 'upmod'. I added a new sort type that gets all the upmod classes in  the commentNavigator class. I build it in chrome and firefox, and it behaved the same as the image and video navigator in my dev environment.
Let me know if there is anything I can do to improve the quality of my contribution.

Added upvoted sort type to the navigator sortTypes class

---

.flowconfig
browser/foreground.js
chrome/beta/manifest.json
chrome/manifest.json
edge/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
flow/stub/scss.js
lib/core/init.js
lib/css/index.js
lib/environment/getUrl.js
lib/environment/index.js

Tested in browser: Chrome 64, Firefox 55, Edge 16
This change may be backed out of Chromium; it does make !important rules more powerful, but it makes non-!important rules much less useful.
Won't be merged until shortly before 64 goes stable (probably).

Prepare workaround for potential extension CSS precedence change

---

lib/modules/nightMode.js

The problem was, that we were displaying the message about user denying location permission in case of ANY geolocation error. As a result, I - being in a high speed train at the moment - have received 865898 false alerts about denying location permission.
We need to decide how we should handle other kinds of errors. So far, I have just placed switch() in order to make it easy to implement.

Show nightModeAutomaticNightModeDenied message only when the user actually denied permission

---

lib/css/modules/_userTagger.scss
lib/modules/userTagger.js
locales/locales/en.json

Relevant issue: #4500 
Tested in browser:  Chrome, Firefox
I tried to use css but the max-width: 30ch; Did not seem to work well with anchor tags.

Truncate user tags if too long. (#4500)

---

lib/css/modules/_nightMode.scss

Relevant issue: #4530 
Tested in browser: Chrome 62.0.3202.75 (Official Build) (64-bit)

Fix "Prominent comment" nightmode colour

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/modules/showImages/templates.js

Useful for when a slideshow isn't suitable, like when there's a lot of text to each piece and the total height of the text and image exceeds the viewport height.
The `🎞` button to the right:
Edit: Changed character
Tested in browser: Chrome 63, Edge 16

gallery: Add button to switch from slideshow to filmstrip

---

lib/modules/presets.js
lib/modules/settingsConsole.js

Relevant issue: presets.cleanSlate should show prompt("Reload?") instead of notification (fixes #2711)
Tested in browser: Chrome and Firefox
This shows optionName instead of a blank field on the reload prompt. It should be fixed, but I wasn't able to figure out how to fix it.

Applying a preset will prompt the user to reload (#2711)

---

lib/modules/hosts/youtube.js
lib/utils/Thing.js

Tested in browser: Chrome 62, Firefox 56
YouTube URLs with "/attribution_link" do not get an expando. 
This particular example is from the /r/videos subreddit. Post: https://www.reddit.com/r/videos/comments/7ce3ws/
`https://www.youtube.com/attribution_link?a=iAZ-qdJA3J0&u=%2Fwatch%3Fv%3D2a0DQWmVmL4%26feature%3Dshare`
When clicked, this URL should redirect to: `https://www.youtube.com/watch?v=2a0DQWmVmL4&feature=share` but that doesn't matter to the host detection.
/attribution_link
| Key | Value |
|---|---|
| a | iAZ-qdJA3J0 |
| u | /watch?v=2a0DQWmVmL4&feature=share |
If you need to find an example post for testing or whatnot, you can run this code in the console to jump to one:
`(() => { let v = document.querySelectorAll('a.title[href*="attrib"]'); v.length ? (v[0].scrollIntoView(), …

Add /attribution_link in YouTube host

---

lib/utils/watchers.js

It's more accurate. Also, since it's memoized, calling it at this stage avoids it causing a reflow when otherwise invoked at a later stage in the init.

watcher: Use utils.getViewportSize when determining sort order

---

firefox/background.entry.js
firefox/beta/manifest.json
firefox/manifest.json

Relevant issue: fixes #4514 
Tested in browser: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0`
Edit(erikdesjardins): fixes #4230
Edit(mc10): fixes #190

Use openerTabId with openNewTabs on Firefox

---

browser/foreground.js
lib/core/modules/modules.js
lib/core/options/options.js
lib/environment/storage.js
lib/modules/newCommentCount.js
lib/modules/saveComments.js
lib/modules/settingsConsole.js
lib/modules/troubleshooter.js
lib/modules/userTagger.js

Tested in browser: Chrome 64; existing integration tests exercise module enabled state / options
Primarily adding `Storage.wrapBlob`, and not exporting some complex storage operations at the root (you should probably use a wrapper instead)

Storage refactoring/minor cleanup

---

lib/modules/hosts/poly.js

A small, pretty straightforward implementation of a media host for Google's new Poly 3D model catalog.
As far as I know Poly doesn't have an API, but it's pretty straightforward to just embed the viewer with an iframe.
Tested in Chrome 62.
Try it out here: https://www.reddit.com/domain/poly.google.com/

Add support for Google Poly media host

---

lib/css/modules/_userTagger.scss

- Fixes height when there's color but no text
- Fixes some circumstances where it was misaligned with the username / voteweight.
Tested in browser: Firefox 57, Chrome 64

userTagger: Improve tagger alignment

---

lib/css/res.scss

Settings, especially on non-English locales, tend to get messy. In Polish, often short setting names must be longer to make ANY sense. As a result, settings may look like this:
(and I couldn't be bothered to find the worst case)
After the fix, settings behave like so:
* Label takes 20%, but not less than 200px,
* Setting takes 20%, grows when necessary in some special cases
* Description takes whatever is left
and it looks like that:

Fix settings layout to enhance clarity

---

lib/utils/dom.js

[`visualViewport`](https://developers.google.com/web/updates/2017/09/visual-viewport-api) contains the same size data as `getBoundingClientRect`, but reflow is not necessary to obtain it.
Currently is `visualViewport` only available in Chrome.
Tested in browser: Firefox 59, Chrome 64, Edge 16

utils getViewportSize: Use window.visualViewport when available

---

lib/modules/showImages.js

Fixes:
- Image / video being slow to restore when scrolling fast / collapsing threads
- Forced reflow when refreshing
Tested in browser: Chrome 64, Firefox 58, Edge 16

showImages conserveMemory: Use IntersectionObserver

---

lib/css/modules/_showImages.scss

Reducing its size to 0.8x avoids it covering the lines above/under in some circumstances.
Tested in browser: Firefox 57, Chrome 64

Make inline expando button smaller

---

lib/modules/hideChildComments.js
lib/modules/keyboardNav.js
locales/locales/en.json

"C" by default.
Fixes #1274.
Tested in Chrome and Firefox.
I have the feeling that one shortcut should serve to expand comment trees, collapse them and load more comments—instead of two shortcuts (C and Enter) plus navigation to "load more comments."
With "show/hide child comments" for nested comments enabled, the present change allows to use one shortcut to expand top-level comments (if collapsed by default) and collapse trees of child comments.
However, I also think that child comment trees that were deliberately collapsed should be highlighted visually, like it happens now with Enter—because I use this regularly to find comments that I just read but didn't think to save or leave a reply.  Not sure how this is best done, yet.

Added a shortcut to show/hide child comment trees on the comment page.

---

lib/modules/userHighlight.js
locales/locales/en.json

Maybe ok for fixing #1666 ... "Me" also gets highlighted when the friends highlighting is active. That avoids having to create an extra option just for that.
Edit(erikdesjardins): fixes #1666

Add user highlighting for current user

---

lib/core/migrate/migrate.js
lib/core/migrate/migrators.js

Relevant issue: closes #4346
It's possible that some other options could have been saved as numbers, but this covers everything that could be broken by default (and other things should have more obviously broken when a user changed them).

Migrate text options saved as number to string

---

lib/modules/orangered.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/7i99t5/orange_icon_on_browser_tab_with_res_enabled/

Remove other favicons to prevent Chrome from switching to them

---

lib/modules/orangered.js
locales/locales/en.json

The current red notification doesnt work well with the orange background of the new favicon.
This changes to periwinkle to stay somewhat onbrand. Also adds the ability to customise for user preference.

Change favicon notification colour

---

lib/core/modules/modules.js
lib/modules/showImages.js
locales/index.js
webpack.config.babel.js

re #4591, includes part of #4059
It doesn't really do anything if Babel is still converting everything to commonjs modules.
I had intentionally left the commonjs transform enabled because webpack used to generate massive `WEBPACK_IMPORTED_MODULE_...` identifiers for ES6 imports, making them a net negative, even with module concatenation (some execution time saved, but more spent to parse hundreds of KB of useless text). But it appears that was changed recently, so it is now actually a benefit. :tada:

Make webpack module concatenation work

---

lib/core/metadata/index.js
package.json
yarn.lock

Update exec-loader for ES6 imports

---

lib/modules/userTagger.js

Discovered while working on a feature with similar code for vote tracking #4560 
Actual: When upvoting then downvoting a post, it was counting as a negative downvote and incrementing the total vote weight. (up = 0, down = -1)
Expected: (up = -1, down = 1)

Fix userTagger vote click when downvoting after upvoting

---

.travis.yml
appveyor.yml

In fact, a future version of `yarn` will actually pass `--` to scripts.
Delay this until `yarn` on Travis reaches v1.0.0, or if we switch back to version pinning for Yarn.

ci: Remove now-unneeded `--` in yarn scripts

---

lib/modules/neverEndingReddit.js
lib/utils/index.js
lib/utils/user.js

Relevant issue: #4219
Tested in browser:  Chrome 63.0.3239.84
"learn more" button on "could not load NER page" links to [wiki about NER](/r/Enhancement/wiki/faq/never_ending_reddit), which includes [troubleshooting steps for that error](/r/Enhancement/wiki/faq/never_ending_reddit#wiki_could_not_load_the_next_page.3A_page_loaded_was_not_for_current_user).

NER: verify "next page" belongs to current user, fix "try again" link

---

lib/modules/commentNavigator.js

Relevant issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2147
Tested in browser: Chrone
Thought I'd try contributing by starting to tackle a smaller task.
I Took a look at #2147. Since it was filed, we now include the comment count pertaining to each filter. However, we still include all the filters with a count of (0). This PR filters those filters (ha!). 
Before:
https://i.imgur.com/2GKUmr9.gif
After:
https://i.imgur.com/2nOMRXH.gif
(GIFS too large to embed)

Filter empty comment context navigation options

---

lib/css/modules/_commentNavigator.scss
lib/css/modules/_filteReddit.scss
lib/modules/commentNavigator.js
lib/modules/filteReddit.js
lib/modules/filteReddit/Case.js
lib/modules/filteReddit/Filterline.js
lib/modules/filteReddit/LineFilter.js
lib/modules/filteReddit/cases.js
lib/modules/filteReddit/commentCases/CommentContent.js
lib/modules/filteReddit/commentCases/CommentLength.js
lib/modules/filteReddit/commentCases/Depth.js
lib/modules/filteReddit/commentCases/IsDeleted.js
lib/modules/filteReddit/commentCases/IsRead.js
lib/modules/filteReddit/commentCases/index.js
lib/modules/filteReddit/postCases/Expando.js
lib/modules/filteReddit/postCases/UserAttr.js
lib/modules/neverEndingReddit.js
lib/modules/readComments.js
lib/modules/selectedEntry.js
lib/modules/showImages.js
lib/modules/showImages/expando.js
lib/utils/Thing.js
lib/utils/async.js
lib/utils/dom.js
lib/utils/index.js
locales/locales/en.json
tests/readComments.js

Like on listing pages, things which don't match the filters are hidden. For parents of non-hidden things it only restricts height and reduces opacity instead of hiding them completely, unless a parent is selected, in which case that comment is shown normally.
New comment-specific cases:
- Comment length (words / characters)
- Comment depth
- Comment content
- IsRead (comment has been selected earlier)
Filter by submitter and a given string:
Hide read comments the next time the page is loaded (comments are marked read by selecting them):
Nice-to-haves for future implementation:
- Filter when page is rendering (by listen to mutations), as currently the whole page must load before filtering is initiated — which can take a while on larger comment pages
- Options how much of hidden parent …

Comment filters

---

lib/modules/betteReddit.js

Recently, Reddit started to show their video times on video thumbnail:
So, I'm proposing to move RES's video duration to thumbnail as well:
(in this illustration, all video info options enabled: videoTimes, videoUploaded and videoViewed)

Implement native Reddit duration overlay on video thumbnail

---

lib/modules/neverEndingReddit.js

Things were hidden by neverEndingReddit as they had been seen registered before, and thus handled as duplicates and removed.
Fixes https://www.reddit.com/r/RESissues/comments/7pmglm/5100_dashboard_bug/, https://www.reddit.com/r/RESissues/comments/7pljpr/res_v5100_broke_the_refresh_all_button_in_my/

Fix refreshing in dashboard

---

lib/css/modules/_showImages.scss

Should make it harder to accidentally click. (reddit's css was overriding the margin before, at least in comments)

res-gallery-to-filmstrip: increase specificity and margin

---

lib/modules/filteReddit.js

`registerThing` is only invoked for comments on comment pages.
Relevant issue: https://www.reddit.com/r/Enhancement/comments/7r26ku/filtereddit_is_not_working_correctly_since_the/

filteReddit: Fix allowNSFW being ignored on comment page

---

lib/modules/sourceSnudown.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/7rc3ps/res_510x_removed_the_source_button_from_the_inbox/

sourceSnudown: handle buttons without li.first

---

build/deploy.js

Moves edge beta deploy to a single ring compared to Internal and Public. Separate rings are no longer required. 
@erikdesjardins can you please validate the flightId for the beta release is still the same via the API?

Move Edge deploy to single beta release.

---

.sass-lint.yml
lib/css/modules/_subredditManager.scss

Currently when the user scrolls to the bottom of the subreddit list the whole page scrolls down, this moves this subreddit list up causing some confusion. [`overscroll-behavior`](https://wicg.github.io/overscroll-behavior/) is a new property to deal with this, it's supported in chrome as of 63 (the current stable release) and will be available in firefox come version 59

Contain subreddit list scrolling

---

lib/modules/filteReddit/postCases/NewCommentCount.js

Filter newCommentCount: If not opened, use comment count in comparator

---

lib/modules/accountSwitcher.js
locales/locales/en.json
tests/accountSwitcher.js

Adds the ability to type in the password every time you switch to a different account, instead of having to store it in RES settings (which is not terribly secure, as a note in the module description warns.)
Based on an old [feature request](https://www.reddit.com/r/Enhancement/comments/13pkfn/feature_request_prompt_for_a_password_when/).
Tested in browser: Firefox 57.0.4

Allow option to prompt for password when switching accounts

---

lib/modules/commandLine.js
lib/modules/commentNavigator.js
lib/modules/filteReddit/LineFilter.js
lib/modules/filteReddit/cases.js
lib/modules/hideChildComments.js
lib/modules/keyboardNav.js
lib/modules/selectedEntry.js
lib/modules/userInfo.js
lib/utils/Thing.js

- New ways to determine posts to browse: `getThings` and `conditions`.
- Adds a `navigate by` button to filter popups which sets conditions for posts to browse.
- Navigates to `Thing`s instead of elements
- More resilient to loading new comments (by keeping track of a `Thing` instead of an index)
- Set default navigation to browse popular comments 
Relevant issue: Closes #1327, closes #787

 commentNavigator: Use filteReddit cases

---

lib/css/modules/_commentNavigator.scss
lib/css/modules/_nightMode.scss
lib/modules/commentNavigator.js

Keeps the commentNav `popular` sort a little less annoying when used along with other keyboard navigation.
Makes the widget a less intrusive, especially in dark mode:

CommentNav tweaks

---

lib/modules/singleClick.js
lib/utils/Thing.js

Relevant issue: #4423 
This is a simple stopgap to address #4423, which may have some issues beyond the control of RES. The comments link will now only open once.

followLinkAndCommentsNewTab no longer opens duped tabs.

---

lib/modules/showImages.js

By starting to load media on `mousedown`, the likelihood that it is ready on first paint after `click` significantly increases.

showImages: Make expando click snappier

---

lib/modules/showImages.js

showImages: Fix wrapper being resized on media unload

---

lib/modules/showImages.js

The `stopEventPropagation` handler was not removed when restoring media.

showImages: Fix unloading media breaking resize events

---

lib/modules/hideChildComments.js
lib/modules/keyboardNav.js
locales/locales/en.json

uses shift-C as the command
Relevant issue: fixes #4677 

add "Hide all child comments" functionality to keyboard navigation

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
locales/locales/en.json

Option added to the showImages module to hide pinned Reddit-hosted videos on comment pages. 
Relevant issue: #4644
Tested in browser: Firefox 58

Hide pinned reddit videos

---

.eslintrc.json

This prevents ESLint from looking for `eslintrc` files above this directory.

eslint: Mark as root config

---

lib/modules/usernameHider.js

I messed up a little with #4446: I actually added a margin to some instances of the hidden user name where there shouldn't be one (like in the top header). I just moved the margin rule out so that it only affects `a.author` — this seems to fix the main thing i was worried about before, without breaking anything else.
Tested in browser: Firefox 59

Fix right margin on hidden user names (round 2)

---

edge/edge.entry.js
lib/modules/commandLine.js
lib/modules/commentPreview.js
lib/modules/commentTools.js
lib/modules/keyboardNav.js
lib/modules/quickMessage.js
lib/modules/settingsConsole.js
lib/modules/subredditManager.js
lib/utils/alert.js
lib/utils/index.js
lib/utils/keycode.js

There are a few `keyCode` instances that I did not change, as they were trickier to modify correctly.

Use event.key over event.keyCode/which

---

lib/modules/keyboardNav.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/800v14/how_to_disable_upvote_shortcut_on_archived_posts/

Disable voting keyboard shortcuts on archived posts

---

lib/modules/hosts/vlipsy.js

Tested in browser: 
Firefox
Chrome

Add Vlipsy Host

---

package.json
webpack.config.babel.js

This avoids the need to pass in `--env.production` to the `webpack` script.

webpack: Replace env.production with argv.mode

---

tests/selectedEntry.js

I can't reproduce the issue myself, but I think, like the [comment describes](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/tests/selectedEntry.js#L14), the reddit built-in usertip might be overlaying the `loadMoreChildrenOfSticky`. So I reordered so they'd work top to bottom to hopefully avoid that issue.

Reordered test actions to avoid issues with built-in userinfo

---

lib/modules/orangered.js
locales/locales/en.json

Could have made it not dependant on `showUnreadCountInFavicon`, but it would have made it uglier and I don't think it matters much.

Added option to use legacy Reddit favicon

---

lib/modules/keyboardNav.js

To match the other filters, will only show hotkeys that are enabled options, specific to the page, etc. Previously was showing every option on every page, despite the options having `include` set for specific pages.
~~Changed the names of all the 'Go to' hotkeys to start with "goto[Inbox|Frontpage|etc]" so it was more obvious which ones were linked with the Go-Mode function, based on it's description.~~
*Reordered the options so that all the 'Go to' hotkeys and options were grouped together at the bottom.*
Also made the popup show the friendly name.

Update go-mode hotkey filter

---

lib/css/modules/_showImages.scss
lib/modules/betteReddit.js
lib/modules/filteReddit/postCases/Expando.js
lib/modules/hosts/twitter.js
lib/modules/showImages.js
lib/modules/showImages/expando.js
lib/modules/wheelBrowse.js
tests/showImages.js

- Convert media elements into classes
- Remove coupling between hosts and `Expando`
- Removed `.res-expando-box` class `.res-media-host-${host}`
- Added attribute `data-host=${host}` to it, as the button has

showImages clean-up

---

lib/modules/nightMode.js

The multicasted functions were invoked on all tabs, also those where the nightmode module was not running (d2x pages).

nightmode: Don't change global state on load

---

lib/modules/customToggles.js
lib/modules/filteReddit/browseCases/Toggle.js
lib/modules/stylesheet.js

-  CLI available by `toggle` followed by the name of the toggle (the text which is displayed in the menu)
- Multicasting switches toggle on all active tabs
Closes #4494, resolves #4454

 customToggles: Refactor, add multicasting, add CLI

---

lib/modules/customToggles.js
lib/modules/filteReddit/browseCases/Toggle.js
lib/modules/settingsConsole.js
lib/modules/stylesheet.js

There has been some confusion about what the `toggleName` column does, and entering the wrong text there prevents the snippet from working.
This changes the option from `text` to `enum`. The value remains the same.

stylesheets: display available customToggles

---

lib/modules/customToggles.js
lib/modules/filteReddit.js
lib/modules/nightMode.js

- NSFW mode applies to all active tabs when toggled
- `nsfw` command no longer needs to have `on` or `off` specified
- `ls` command for toggling nightMode is removed

Use toggle interface for nightMode and NSFW mode

---

lib/modules/keyboardNav.js
locales/locales/en.json

Option available under http://reddit.com/#res:settings/keyboardNav/linkNumberAltModeModifier
Relevant issue: Closes #4251
Tested in browser:  Chrome 65

keyboardNav linkNumbers: Add option to change/reject altMode modifier

---

lib/core/module.js
lib/css/modules/_hover.scss
lib/css/modules/_userTagger.scss
lib/modules/settingsConsole.js
lib/modules/userTagger.js
locales/locales/en.json

Relevant issue: resolves #1270 closes #1263
Screenshots -
UserTagger options:
A few presets:
UserTagger dialog:
~~Is calling it `preset` fine, or should it be called something else?~~ 
Changed it to `presetTags` to avoid any confusion with the existing `presets` module

UserTagger preset tags

---

lib/modules/profileRedirect.js

Currently pressing the "Back" button after being redirected by profileRedirect will result in going back to the same page. Using location.replace prevents this behavior.

profileRedirect: use location.replace to avoid continuous redirect

---

lib/modules/commentNavigator.js

Using the keyboard shortcuts for move up and down did not call `initialize`, which is required for having an accurate array of matching posts.

commentNav: Fix initializion when moving without opening widget

---

lib/modules/nightMode.js

nightmode: Fix automatic night mode handling from outdated tabs

---

lib/css/modules/_nightMode.scss

i.e. don't leak into redesign
It may be worth adding tooling later to distinguish between app types for "new profiles" and "redesign", depending on the expected lifetime of "new profiles" and how much redesign tooling gets backported to it.
* https://www.reddit.com/r/redesign/comments/8d0185/every_single_thread_i_open_across_all_of_reddit/
* https://new.reddit.com/r/beta/comments/8ctbjn/just_got_into_the_new_reddit_alpha_why_cant_i/

Restrict "new profile" darkmode to correct layout

---

package.json
yarn.lock

The `scroll` strategy which was used does not work when animations are globally disabled, causing media to not flow properly. The other available strategy, `object`, does not have this issue. 
Replaces #4759 
@erikdesjardins Can you fork the repo [larsjohnsen/resize-observer-lite](https://github.com/larsjohnsen/resize-observer-lite) to the organization, like is done with jquery.tokeninput?

Use resize-observer-lite fork which uses different strategy

---

lib/environment/foreground/ajax.js
lib/modules/accountSwitcher.js
lib/types/reddit.js
lib/utils/index.js
lib/utils/user.js

1. fixed logged-in check prerequisite for logout
1. fetch modhash as prerequisite for logout
tested in chrome

Fix account switcher on redesign

---

lib/modules/showImages.js

Necessary since the wrapper stretches vertically only, causing the viewport (+ `bufferScreens` margin) to not intersect with it any longer when zooming and scrolling too far horizontally.

showImages conserveMemory: Don't unload when scrolling horizontally

---

lib/modules/showImages.js
lib/utils/Thing.js

`Thing#isContentVisible` adds the additional check that the comment itself is not collapsed.
Relevant issue: https://www.reddit.com/r/Enhancement/comments/8kgszp/videos_in_comments_keeps_playing_after_i_close/

Fix videos not pausing when collapsing containing comment

---

lib/modules/commentNavigator.js
lib/modules/readComments.js
lib/utils/Thing.js

Necessary in order for CommentNav not to navigate to partially filtered comments.

Tweak usage of Thing#isContentVisible

---

lib/modules/commentStyle.js

Relevant issue: resolves #4787
Tested in browser: Chrome v67

Enable the commentStyle module for the comment link list page

---

edge/edge.entry.js

References: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12156111/
Appears to correctly function in Edge 17 per the following test, implemented in Edge 16 (polyfilled in 15): http://bl.ocks.org/nolanlawson/raw/bf31e883ca28579bc063c97fa5d1882b/

Remove Edge isIntersecting polyfill

---

lib/environment/utils/__tests__/messaging.js

I think this can be safely done, as `Promise.resolve().then()` should just return the internal `Promise` and resolve to whatever that `Promise` resolves to.

messaging tests: Simplify nested promises

---

lib/modules/hosts/deviantart.js

Relevant issue: https://www.reddit.com/r/RESissues/comments/8uijew/expandos_no_longer_work_on_deviantart_links/
https://www.reddit.com/r/Enhancement/comments/8uhhid/res_does_not_display_expandos_for_new/

Support new deviantart urls

---

lib/modules/showImages.js

Relevant issue: Fixes https://www.reddit.com/r/RESissues/comments/8uea0e/imgur_link_with_audio_double_plays_upon_expando/

showImages gallery: Propagate collapse events

---

lib/core/migrate/migrate.js
lib/core/module.js
lib/css/res.scss
lib/modules/filteReddit.js
lib/modules/filteReddit/Case.js
lib/modules/filteReddit/ExternalFilter.js
lib/modules/filteReddit/Filter.js
lib/modules/filteReddit/Filterline.js
lib/modules/filteReddit/LineFilter.js
lib/modules/filteReddit/browseCases/CurrentMulti.js
lib/modules/filteReddit/browseCases/CurrentSub.js
lib/modules/filteReddit/browseCases/CurrentUserProfile.js
lib/modules/filteReddit/browseCases/Date.js
lib/modules/filteReddit/browseCases/LoggedInAs.js
lib/modules/filteReddit/cases.js
lib/modules/filteReddit/commentCases/CommentContent.js
lib/modules/filteReddit/postCases/Domain.js
lib/modules/filteReddit/postCases/LinkFlair.js
lib/modules/filteReddit/postCases/PostAfter.js
lib/modules/filteReddit/postCases/PostTitle.js
lib/modules/filteReddit/postCases/Subreddit.js
lib/modules/filteReddit/postCases/UserFlair.js
lib/modules/filteReddit/postCases/Username.js
lib/modules/settingsConsole.js
tests/Filterline.js

- The builder is less coupled with customFilter options (`ondemand`)
- Custom options is necessary for future comment filter options which diverges from post options
- ondemand name field is now visible

Restructure builder (customFilters) to accept custom options

---

lib/modules/userTagger.js

Relevant issue: N/A (found the bug myself)
Previously the userTagger wouldn't watch expanded selfTexts like [this.](https://www.reddit.com/by_id/t3_99dz4z/)

userTagger watches expanded selfText

---

lib/core/migrate/migrate.js

This has been throwing errors for me when `customFiltersP` or `customFiltersC` is null, so I added an additional check. 
Relevant issue: Unknown
Tested in browser: Yes

Fixes error for when `customFiltersP/C` is null

---

lib/modules/showImages.js

Suggested by [/u/dracho](https://www.reddit.com/user/dracho) in [this post](https://www.reddit.com/r/RESissues/comments/94chjf/please_make_the_save_image_button_save_the_image/). 
This is my first time contributing to open source, so excuse any mistakes. I wasn't sure if there should've been a module option for this, but I don't see any reason to have this feature turned off.

showImages: Downloading an image/GIF sets filename to post title

---

lib/modules/showImages.js
lib/modules/userTagger.js

Relevant issue: fixes #4792
Usernames should be 3-20 characters in length so I updated userTagger to ignore usernames that are out of bounds as well.
Edit: I see the importance in making new branches for PRs now. Ignore all those extra commits.
Edit 2: Now I know more about regex so I only needed to change the RE in the first place 😃 
This change also allows the userInfo module to ignore invalid usernames since the RE is exported.

userTagger and userInfo ignore invalid usernames

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/modules/showImages/templates.js

Since the nightly / betas of Firefox and Chrome no longer provides a granular volume control in their video controls, we might as well integrate it.
Basic volume controller:
- Icon has four levels: muted / low / middle / high
- Slider displays on hover, clicking the icon toggles mute
- Volume is stored globally when changed (it might be more desirable to have a setting)
Relevant issue: Closes #799, 
Tested in browser: Chrome 68, Firefox 62

showImages video: Add volume control

---

lib/modules/hosts/imgur.js

Relevant issue: fixes #4826
I only really had [this example](https://www.reddit.com/r/DDLC/comments/99yss1/oh_no/) to go off of, although it should fix most cases in the meantime.
Even though it's returning an endpoint with 'gallery' in it, the imgur API still uses 'gallery' for single subreddit images.

 added support for imgur subreddit links

---

lib/environment/background/ajax.js
lib/environment/foreground/ajax.js
lib/utils/user.js

new.reddit.com always routes to the new reddit web desktop service (desktop2x). Unlike www.reddit.com, api (.json) requests are not routed to the reddit api public service. Thus, sending ajax requests to, e.g. `/api/login` from new.reddit.com will 404.  To fix this, when sending an ajax request to the reddit api from new.reddit.com, that request will now be sent to www.reddit.com and sent via the background page, including credentials.
Tested on Chrome 68 and Firefox 61. Was not tested with Firefox's third-party cookies option disabled.
nb: new.reddit.com/....json?embedded=true currently selects r2, i.e. the public reddit API. (This is currently leveraged by first-party ajax api requests from new.reddit.com/message/inbox). However, I decided against it for RES as that routing may be …

Fix account switcher and other ajax requests to Reddit API from new.reddit.com

---

.travis.yml

re #4827
On second thought, it's annoying to have to wait for the job to timeout (or cancel it) when we know it's going to fail.

Temporarily disable FF integration tests

---

lib/modules/hover.js
lib/modules/messageMenu.js
lib/modules/multiredditNavbar.js
lib/modules/profileNavigator.js
lib/modules/showParent.js
lib/modules/subredditInfo.js
lib/modules/userInfo.js

Mainly fixes a issue in the redesign's lightboxes where `position: absolute` cannot be used to keep the hover container relative to a given target. 
- If a target parent has `position: fixed`, also set `position: fixed` on the hover container
- Closes at once if target is in a lightbox which is scrolled, as to prevent position mismatch with the target

hover: Support fixed positioning

---

lib/modules/hosts/xkcd.js

Fixes [this bug](https://www.reddit.com/r/RESissues/comments/9asuvg/res_doesnt_display_xkcd_alt_texts_with_emojis/) found by [/u/DonaldLovesJong](https://www.reddit.com/user/DonaldLovesJong) and [/u/LevelSevenLaserLotus](https://www.reddit.com/user/LevelSevenLaserLotus).
Examples:

Fix faulty XKCD alt text

---

.babelrc
package.json
webpack.config.babel.js
yarn.lock

Flow can't parse this syntax so we can't use it anyways.
Also, the equivalent syntax:
`export Foo from './foo'` -> `export { default as Foo } from './foo'`
isn't much longer and is clearer IMO (i.e. does the first one export something called `Foo` or the default export?)

remove @babel/plugin-proposal-export-default-from

---

lib/css/res.scss
lib/modules/search.js
lib/modules/settingsConsole.js

- Updates search field when opened externally
- Blurs search field when closing settingsConsole
- Fixes navigation when searching
- Removes throttle on search (by memoizing results)
- Avoids reinitalizing console on every search / changing module

settingsConsole search fixes

---

appveyor.yml

This fixes the current AppVeyor build failures.

appveyor: Set image to Visual Studio 2017

---

lib/environment/utils/__tests__/messaging.js
lib/modules/backupAndRestore/__tests__/serialization.js
lib/utils/__tests__/array.js
lib/utils/__tests__/async.js

This suppresses the two messages from `console.error` and `console.warn` that show up on all test runs.

tests: Suppress console.error/warn more robustly

---

lib/modules/filteReddit.js
lib/modules/filteReddit/Filter.js
lib/modules/filteReddit/Filterline.js
lib/modules/filteReddit/LineFilter.js
tests/Filterline.js

There was really no good reason to limit deleting default filters, as they can easily be reinstated via the dropdown.
Right click will now disable filter if active, or remove filter if inactive.

Filterline: Make all filters deletable & tweak right click behavior

---

lib/css/modules/_accountSwitcher.scss
lib/modules/RESTips.js
lib/modules/accountSwitcher.js
lib/modules/dashboard.js
lib/modules/filteReddit.js
lib/modules/filteReddit/Case.js
lib/modules/search.js

Minor fixes

---

.gitignore

Relevant issue: N/A but I would be happy to create one if that necessary.
Tested in browser: N/A
I noticed when running `npm install` that I got an error locally and an `npm-debug.log.1039210921` was generated. I'm not sure what happened to generate that although it seems to happen when my wifi connection is having issues.
This PR just updates the `.gitignore` file to match Githubs Node.gitignore for logs as can be seen [here](https://github.com/github/gitignore/blob/master/Node.gitignore#L4).

chore(gitignore): ignore npm and yarn debug logs

---

lib/vendor/README.md

This file should be linked to from the "Notes to Reviewers" section of the extension details on AMO.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Third_Party_Library_Usage
> To complete the review process at addons.mozilla.org (AMO), reviewers must be able to verify the code in your extension. You might include third-party libraries in your extension. In that case, when you upload your extension to AMO, you will need to provide links to the library source code.
> You can add the links to the “Notes to Reviewers” section of your extension’s details on AMO.

Document source and purpose of files in lib/vendor/

---

lib/css/modules/_nightMode.scss

Relevant issue: Fixes #4786 
Tested in browser: Yes (In Firefox 63 on macOS (High Sierra))
Before:
After:

Issue-4786: Made dismiss pinnable tooltip easier to see in night mode

---

lib/modules/commentDepth.js
lib/modules/filteReddit/postCases/CommentCount.js
lib/modules/newCommentCount.js
lib/utils/Thing.js

Keeps track of the comment count locally in order to avoid:
- Don't updating the entry to 0 when it is not found, as may happen when noCtlF is applied
- Commenting multiple times causing false-positive subscription notification
Relevant issue: https://www.reddit.com/r/RESissues/comments/98ezk5/bug_comment_count_broken_when_no_ctrlf_is_on/

newCommentCount: Make more robust

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js

Prevents the generated CSS being unnecessarily nested.

 showImages css: Simplify video selectors

---

lib/utils/Thing.js

Otherwise it breaks when a post has no comment (fixes regression from #4853)

Thing#getCommentCount: Default to 0 when element exists

---

lib/modules/userHighlight.js
lib/modules/userTagger.js
locales/locales/en.json

Relevant issue: #4822
Here are WIP changes for implementing the feature described in #4822 .
Still on the to-do list:
- ~Need to add descriptions and titles to [locales](https://github.com/honestbleeps/Reddit-Enhancement-Suite/tree/master/locales/locales) (How is this usually done? Is there a tool?)~ Added to English locale.
- What default colors should be used for the highlights? I went with brown since it seems to have not be used yet. 
- ~Still needs to be tested.~ Tested in Chrome 69.

Highlight users mentioned in self-posts

---

lib/modules/commentNavigator.js

Makes the comment navigator better tolerate changes in what comments are visible.
Tested in browser: Firefox 63, Chrome 72

commentNavigator: Don't reset when collapsing current comment thread

---

lib/css/modules/_filteReddit.scss
lib/modules/filteReddit/Filterline.js
lib/utils/Thing.js

It would sometimes return wrong result, causing commentNavigator to browse to a hidden comments.
This can be used to check that it returns correct results:
`Array.from(things).filter(v => v.isComment() && v.isVisible() === !v.element.offsetParent).length == 0`
Tested in browser: Firefox 64, Chrome 71

Fix `Thing#isVisible` when parent comment is filtered

---

lib/core/migrate/migrate.js
lib/css/modules/_filteReddit.scss
lib/css/modules/_userTagger.scss
lib/modules/filteReddit.js
lib/modules/filteReddit/Case.js
lib/modules/filteReddit/Filter.js
lib/modules/filteReddit/Filterline.js
lib/modules/filteReddit/LineFilter.js
lib/modules/filteReddit/cases.js
lib/modules/subredditInfo.js
lib/modules/userTagger.js
locales/locales/en.json
tests/Filterline.js

- userTagger ignore states have been migrated to a list in filteReddit
- Filtering of users are now as quick as other filteReddit filters (i.e. no additional FOUC while waiting for tags to load)
- Makes ignoring users work with redesign when filteReddit becomes ported
- Ignoring will no longer generate placeholders. To show content, power off Filterline / disable the `Users` filter
- Ignore button in dialog is moved to header
- `hardIgnore` is removed; ignoring users now hides the post but not its replies, so if complete hiding is desired the user must be blocked (#2865) or a customFilters manually created
Fixes #4088 
Fixes #2399 (by disabling the filter via Filterline in the sub and saving the configuration as default)
Obsolete issues: Closes #1125, closes #2326, closes #4036 
Improves …

userTagger: Use Filterline to hide ignored users

---

lib/css/modules/_newCommentCount.scss
lib/css/modules/_nightMode.scss
lib/modules/newCommentCount.js
locales/locales/en.json

By default enabled since it is useful to track comment pages which has been opened, but has no new activity.

newCommentCount: Optionally show count when there's no new comments

---

lib/core/module.js
lib/core/options/stage.js

Relevant issue: NA
Tested in browser: chrome, firefox
This PR adds a module-level hook (onSaveSettings) that runs when the module's options are changes in RES settings console

On-save-settings hook

---

lib/core/migrate/migrate.js
lib/css/modules/_filteReddit.scss
lib/css/modules/_nightMode.scss
lib/modules/filteReddit.js
lib/modules/filteReddit/Case.js
lib/modules/filteReddit/ExternalFilter.js
lib/modules/filteReddit/Filter.js
lib/modules/filteReddit/Filterline.js
lib/modules/filteReddit/LineFilter.js
lib/modules/filteReddit/cases.js
lib/modules/hover.js
lib/modules/selectedEntry.js
lib/modules/showImages.js
lib/utils/Thing.js
tests/Filterline.js
tests/readComments.js

- Filterline sideEffects (highlight, propagate) are now generalized, and not dependent on whether a thing is hidden. Since Filterline now is not just about hiding things, a lot of class member are updated to reflect that.
- Adds a `lastUsed` value to the Filterline storage, for future pruning of unused filterlines.
Tested in browser: Firefox 64, Chrome 71

 Filterline: Refactor effects and simplify widget

---

lib/modules/hosts/mixer.js

API now supports muted on embed.
Relevant issue:  N/A

Mixer Mediahost - Muted as default

---

lib/modules/hover.js

Otherwise the Filterline widgets may still be mutated if any input / select elements are focused.

hover: Blur when closed

---

lib/modules/userHighlight.js
lib/modules/userInfo.js
lib/modules/userTagger.js
lib/utils/index.js
lib/utils/user.js

username clean-up: Move selector and getUsernameFromLink to utils

---

lib/css/modules/_subredditManager.scss

It's a simple fix to a bug that keeps annoying me.
z-index: 1 is chosen to match night mode
Relevant issue: #1740

Fixed "add subreddit" control overlay on top of expanded images

---

lib/modules/betteReddit.js

* Previously, `videoUploaded` and `videoViewed` would only work if `videoTimes` was enabled. **FIXED**
* Also made the `videoUploaded`/`videoViewed` text a little bit more distinguishable from the title.
**Comparison Screenshot:**
**EDIT:**
* Replaced date-stamp with `<time class="live-timestamp">` field to make it more feature rich (as described below)
* Added a fields parameter to the Youtube API query to minimize the return data to just the essentials.

Small fixes / adjustments to video info stats

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/modules/showImages/templates.js
locales/locales/en.json

The option is confusing (disabling it removes RES' controls, but adds the browser's controls), and probably little used. 
Tested in browser: Firefox 64, Chrome 70

showImages: Remove option 'showVideoControls'

---

lib/modules/hosts/gfycat.js

Example URL: https://www.reddit.com/r/HighQualityGifs/comments/a309fe/the_ultimate_siege_engine/

gfycat: Add support for "ifr" URLs

---

lib/modules/filteReddit/ExternalFilter.js
lib/modules/filteReddit/Filter.js
lib/modules/filteReddit/Filterline.js

- Don't run filter engine when there's no active filters
- Prevent cases from observing when they're not active
Tested in browser: Chrome 70, Firefox 64

Optimize Filterline

---

lib/core/init.js
lib/modules/betteReddit.js
lib/modules/dashboard.js
lib/modules/filteReddit/commentCases/CommentContent.js
lib/modules/neverEndingReddit.js
lib/modules/pageNavigator.js
lib/modules/selectedEntry.js
lib/modules/showImages.js
lib/modules/showImages/expando.js
lib/modules/userTagger.js
lib/utils/Thing.js
lib/utils/async.js
lib/utils/index.js
lib/utils/watchers.js
lib/utils/watchers_d2x.js

- Reduces the amount of callbacks in the first chunk, so that the first draw after `go` is performed earlier
- Removes forced reflow on init, since sorting callbacks by distance from viewport in most cases isn't worthwhile
- `siteTable` is renamed `page` (scans whole page on initial load, and later sitetables provided by dashboard and ner)
- `newComments` is removed (use Thing watcher instead)
- `selfText` is now invoked on comment pages (when applicable)
- Thing callbacks can be invoked for all Thing types by using `null` as the first argument
Tested in browser: Firefox 64, Chrome 70

r2 watcher: Simplify interface and adjust callback aggregation

---

lib/modules/commentTools.js
lib/modules/troubleshooter.js
lib/modules/userTagger.js

- Only display users on the current page, in addition to those whom have been tagged or upvoted earlier, because otherwise the list gradually becomes very noisy
- Retrieve users only once, since loading the tag storage is slow, especially on Firefox

username autocompletion: Improve performance, restrict selection to upvoted / tagged / on page

---

package.json
yarn.lock

Relevant issue: NA
Tested in browser: NA
Runs the flow, lint, and unit test commands before every `git push`
Mainly useful for WIP PRs - simple errors will now be caught locally instead of in the CI stage

Added a pre-push hook that will run flow, lint, and test scripts

---

lib/modules/RESTips.js

Most tips are for features not ported to the redesign.
Tested in browser: Firefox 65, Chrome 71

redesign: Don't display (broken) RESTips

---

lib/utils/location.js

/r/mod can be filtered to by certain types of moderation actions
(reports, unmoderated, etc). When this is done, the url changes to
`/me/f/mod/about/<type>`. This change expands the modqueue regex to include
the `/me/f` file path.
Relevant issue: #4864 

Add /me/f/mod/about to the modqueue pagetype, fixes #4864

---

lib/css/modules/_accountSwitcher.scss
lib/css/modules/_floater.scss
lib/css/modules/_neverEndingReddit.scss
lib/css/modules/_orangered.scss
lib/css/modules/_pageNavigator.scss
lib/css/modules/_wheelBrowse.scss
lib/modules/floater.js
lib/modules/menu.js
lib/modules/pageNavigator.js

I am a little unsure about this solution's robustness, but this works by pushing the element `.header-user-dropdown` to the left by adding a margin. The margin may at some point be overwritten, which would cause to floater to overlay the profile button, though I didn't see that happen at any time while testing. It may be desirable to get a assigned element up there though.
The `belowFixedNavbar` style is kept as fallback in case the class name is changed.

Better intergrate floaters in redesign

---

lib/css/modules/_hover.scss
lib/css/res.scss
lib/modules/filteReddit/Filterline.js
lib/modules/filteReddit/LineFilter.js
lib/modules/hover.js
lib/modules/messageMenu.js
lib/modules/multiredditNavbar.js
lib/modules/profileNavigator.js
lib/modules/subredditInfo.js
lib/modules/userInfo.js
tests/subredditInfo.js
tests/userInfo.js

- Always close when mouse movement occurs outside of the hover container, in case `mouseleave` is lost due to race conditions or some other reason
- Modifies several consumers to open infocard on `mouseenter` instead of `mouseover` in order to avoid potentially triggering a hover multiple times
- Modifies Filterline hover trigger to fix issue where the wrong infocard is shown after moving the cursor across other filters in order to reach the infocard
- Make fade out CSS based, and stop fade when moving cursor back 
Tested in browser: Chrome 71, Firefox 65

hover: Make closeOnMouseout more reliable

---

lib/css/modules/_menu.scss
lib/css/modules/_nightMode.scss
lib/css/res.scss
lib/modules/RESTips.js
lib/modules/accountSwitcher.js
lib/modules/announcements.js
lib/modules/commandLine.js
lib/modules/contribute.js
lib/modules/customToggles.js
lib/modules/dashboard.js
lib/modules/filteReddit.js
lib/modules/hover.js
lib/modules/menu.js
lib/modules/nightMode.js
lib/modules/search.js
lib/modules/settingsNavigation.js

- Defers building the menu items till menu is displayed in order to improve performance
- Adds `order` parameter to menu interface in order to ensure stability
- The menu cog is now added to the floater when the r2-header is not available
Tested in browser: Chrome 71, Firefox 65

menu: Clean-up, defer building items

---

lib/css/modules/_neverEndingReddit.scss
lib/modules/accountSwitcher.js
lib/modules/keyboardNav.js
lib/modules/neverEndingReddit.js
lib/modules/showImages.js
lib/utils/Thing.js

- Cleans up code by segregate UI logic from page load logic
- Fixes UI bug where widget and endNER appears simultaneously
- Fixes next/prev disappearing from subreddit section on search pages
- Improves performance on initial load
Tested in browser: Chrome 71, Firefox 65

ner: Separate load logic from UI, simplify

---

lib/modules/commandLine.js
lib/modules/customToggles.js
lib/modules/menu.js
lib/modules/settingsNavigation.js
tests/accountSwitcher.js

Fixes some instances where the dropdown doesn't close when it makes sense that it should.

 menu: Close dropdown by default on action

---

lib/modules/userHighlight.js

It seems that having many separate style elements makes style calculations quite expensive.
Tested in browser: Chrome 71, Firefox 65

Optimize userHighlight highlightFirstCommenter

---

lib/modules/disableChat.js
locales/locales/en.json

Reddit's chat is quite resource heavy, so it's nice with an option to prevent it from loading.
On my laptop it takes more than 200 ms only just to evaluate the main bundle:
Tested in browser:  Chrome 71, Firefox 65

New module: Disable chat

---

firefox/beta/manifest.json
firefox/manifest.json
lib/css/modules/_nightMode.scss
lib/environment/background/permissions.js
lib/environment/background/permissions/prompt.entry.js
lib/environment/background/permissions/prompt.html

Firefox requires that optional permissions requests are initiated from an included page (among a small set of other options). This provides such a page.
Tested in browser: Firefox 63, Chrome 71
Closes #4471

Optional permissions in Firefox

---

lib/css/modules/_showImages.scss
lib/modules/showImages.js
lib/types/events.js
lib/utils/watchers_d2x.js

- Adds expandos to comments and selftext when the comment page / lightbox
- The catch-all expando (`video`) button is not native to d2x, so I just added a placeholder button

 redesign: Add expandos in comments

---

lib/environment/foreground/auth.js
lib/modules/backupAndRestore/providers/Dropbox.js
lib/modules/backupAndRestore/providers/GoogleDrive.js
lib/modules/backupAndRestore/providers/OneDrive.js

This fix also removes the browser permission prompt when the providers just requires user login (and not browser permissions).
Tested in browser: Firefox 66, Chrome 71

firefox: Fix backup providers requesting unneed browser permissions

---

lib/constants/sessionStorage.js
lib/core/modules/index.js
lib/core/modules/modules.js
lib/modules/settingsNavigation.js
lib/options/options.entry.js

Chrome's "block 3rd party cookies" blocks localStorage and sessionStorage from being accessed on embedded pages, which RES requires to work properly
Relevant issue: https://www.reddit.com/r/RESissues/comments/ah1j0u/res_settings_wont_open_after_update_to_latest/

settingsConsole: Redirect to standalone page when embedding fails

---

lib/modules/filteReddit.js
lib/modules/filteReddit/Case.js
lib/modules/filteReddit/cases.js
lib/modules/filteReddit/commentCases/CommentContent.js
lib/modules/filteReddit/postCases/Domain.js
lib/modules/filteReddit/postCases/LinkFlair.js
lib/modules/filteReddit/postCases/PostTitle.js
lib/modules/filteReddit/postCases/Subreddit.js
lib/modules/filteReddit/postCases/UserFlair.js
lib/modules/filteReddit/postCases/Username.js

The time spent creating and evaluating a list filter of 40000 users on 100 posts is reduced from multiple seconds to a few hundreds ms.
- Reconciles entries of same type at an earlier stage, to avoid creating a `Case` object for every entry
- Class `PatternCase` which extends `Case`, since many cases have a lot in common
- By deferring the string-to-regex build, it is easier to build more more performent regexes
- The resulting `/^(a|b|c)$/` is must faster than the previous `/^a$|^b$|^c$/`
Tested in browser:  Chrome 71, Firefox 65

Filter list optimization

---

lib/modules/hosts/peertube.js

Add peertube

---

lib/modules/showImages.js
lib/modules/showImages/templates.js
locales/locales/en.json

It might not be as granular as might be desired, but nevertheless fulfills a frequent request for v5.14.
Tested in browser: Chrome 72, Firefox 65

showImages: Option for muting videos by default

---

lib/modules/dashboard.js

If the user is on the redesign, My Dashboard will redirect to old.reddit.com/r/dashboard
*GIF for the dashboard*
Relevant issue: fixes #5085 
Tested in browser: Chrome 72, Firefox 65

fix: Add old Reddit dashboard link

---

lib/modules/commentPreview.js
lib/modules/saveComments.js
lib/modules/sourceSnudown.js
lib/modules/userTagger.js
lib/utils/dom.js
lib/utils/index.js

r2 Reddit in some cirumstances clones elements, e.g. when replying or editing a post, including RES elements.
The `preventCloning` interface removes elements that have a specific attribute (`res-prevent-cloning-...`), but have not been registered.
Relevant issue: Fixes #4310 
Tested in browser: Firefox 67

Prevent Reddit cloning RES elements

---

lib/modules/filteReddit/browseCases/Date.js
lib/modules/newCommentCount.js
lib/utils/localization.js
package.json
yarn.lock

Dayjs is modular and extendable. By being selective with what methods and locales are imported, we get a dependency that is less than 20 kB (in contrast to momentjs' 300 kB)
Tested in browser: Chrome 73

Replace momentjs with (much leaner) dayjs

---

lib/modules/hosts/vlive.js

VLive is a livestreaming service (with VODs too) for Korean-based celebrities (Kpop, makeup/beauty, etc...)
This should add embed support for VLive videos as an expando. You can test [here](https://www.reddit.com/domain/vlive.tv/) 
Tested in browser: Chrome 72

Add VLive to media hosts

---

lib/modules/userTagger.js

*Before*
*After*
Relevant issue: fixes #5068
Tested in browser: Chrome 72, Firefox 65

Prevent duplication of user tags when navigating posts

---

lib/modules/tableTools.js

Relevant issue: fixes #4973 
Tested in browser: Google Chrome 74.0.3729.108 (Official Build) (64-bit)
Tables in redesign are now identified by RES and behave like in old Reddit.
Before to this PR only tables in wikis used to work on redesign, now all tables in posts and comments are identified by RES..
Table in post
Table in comment
Tested in [this post](https://www.reddit.com/r/tabled/comments/abq1ou/test/).
Due to redesign not using a class name like user-text for both posts and comments content, it was necessary to work around by looking for both post and comments in separated callbacks based in the class names _Post_ and _Comment_ which are the only consistent class names in the redesign.

Scanning for tables in redesign (#4973)

---

lib/modules/stylesheet.js

Stylesheet: set textContent of <style> nodes directly to avoid escaping > in  `.parent > .child`

---

chrome/beta/manifest.json
chrome/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/modules/hosts/twitter.js
lib/modules/requestPermissions.js

Tested in browser: Chrome 76, Firefox 66
From #4471. Now that we have optional permissions in Firefox (#4989), we can change this permission.
This doesn't actually change the user prompt (it still looks like you're granting permission for all of api.twitter.com), but oh well.

Limit api.twitter.com permission to the only endpoint we use

---

.babelrc
package.json
webpack.config.babel.js
yarn.lock

Tested in browser: Chrome 76
Now that Edge is slated to use Chromium, all supported browsers support this natively. Hopefully all the tools we use do too.

Remove object-rest-spread transform

---

lib/modules/neverEndingComments.js
lib/utils/async.js
tests/selectedEntry.js

More comments are now started loading instantly (after scrolling), and only one at a time (as loading may otherwise crash).
Tested in browser: Firefox 67, Chrome 76

neverEndingComment: Use IntersectionObserver, improve loadChildComments

---

lib/modules/keyboardNav.js
locales/locales/en.json

Adds an option to scroll back to the top of an inline gallery image when using keyboard navigation.
This has always been a small annoyance for me when when browsing galleries of large-ish images (e.g. comics). Hopefully this will be useful for other users as well.
Maybe a few issues to consider:
- Should this default to *on* as it is now? Because it only scrolls *up*, most users will probably not experience any change in behavior for fully visible galleries.
It may cause some confusion if a user has a post w/ gallery selected, but then continues reading further down the page, before attempting to browse a gallery (without selecting the correct comment first).
- I have chosen to scroll to the top of the `.res-gallery-pieces` container, which contains the image + caption (if the user has …

keyboardNav: Scroll to top of inline gallery on browse

---

lib/css/modules/_nightMode.scss

Tested in browser: Microsoft Edge Version 76.0.167.1 (Official build) dev (64-bit)
Night mode was displaying a white background on link posts on old profiles. Tested fixed.

Fix nightmode issue with links on old reddit profiles.

---

lib/modules/hosts/ppy.js

Relevant issue: https://www.reddit.com/r/Enhancement/comments/c8fpw6/bug_expandos_for_osuppyshss_no_longer_working/
Tested in browser: Chrome 75
Recent `https://osu.ppy.sh/ss/` links have begun adding a short hash onto the end of the URL. This PR supports both new and old `https://osu.ppy.sh/ss/` links.
An example of a "new" link is `https://osu.ppy.sh/ss/13467161/573f` from [this](https://redd.it/c8f25n) reddit thread - refer to [the domain listing for osu.ppy.sh](https://www.reddit.com/domain/osu.ppy.sh/) for more examples.  
An example of an "old" link is `https://osu.ppy.sh/ss/6135901` from [this](https://redd.it/53l422) reddit thread.

host: fix osu.ppy.sh/ss/ expando

---

chrome/beta/manifest.json
chrome/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/css/modules/_nightMode.scss
lib/css/res.scss
lib/foreground.entry.js

Relevant issue:  #5126
Tested in browser: Firefox and Chrome
Does exactly what it says in the title. Only activates in redesign embedded pages to prevent issues with other iframes.
I have tested a variety of functions: 
- Tagging
- User hover popup
- Neverending reddit
All of those appear to be working fine. 
As is visible in the screenshot there is one small visual issue with `.blueButton` which I haven't fixed yet as I don't know if there are guidelines about specificity. When changing the selector to `.res .blueButton` it did show up fine.

Activate RES in redesign embedded iframes. Fixes  #5126

---

lib/modules/autoHide.js
lib/modules/betteReddit.js
lib/modules/filteReddit.js
lib/modules/filteReddit/Filterline.js
lib/modules/readComments.js
lib/utils/async.js
lib/utils/thingHide.js
locales/locales/en.json
tests/readComments.js

When the bottom (the buttons-row) of a post is shown for more than 2 s continuously, the post gets hidden. This may be tweaked in the future to reduce false negatives / false positives, e.g. by adjusting the IntersectionObserver margins / target, or improving the detection heuristic.
By default only comments are marked as read (via readComments), as comments are hidden by RES and can easily be made visible again. Link posts are hidden via thingHide, equivalent of clicking the 'hide' button. Changes are sent every 5 seconds, and flushed on `beforeload`.
Tested in browser: Chrome 77, Firefox 68

New module: autoHide for hiding seen posts

---

lib/core/migrate/migrate.js
lib/modules/onboarding.js

Previously the type was determined simply by checking if the version was beta, minor or a major, independent of the previously installed version. If the user upgrades directly from 5.16.10 to 5.18.2, now the "major" notification type will be used.
This also prevents the notification from being shown on first run.
Tested in browser: Chrome 77, Firefox 68

onboarding: Update notification type depends on last version installed

---

firefox/beta/manifest.json
firefox/manifest.json

It seems that ResizeObserver was pushed back to 69 due to regressions: https://bugzilla.mozilla.org/show_bug.cgi?id=1555786
We could also revert #5132 but we can probably just wait 3 weeks for FF69

Set Firefox min version to 69 for ResizeObserver

---

lib/css/modules/_styleTweaks.scss
lib/modules/styleTweaks.js
locales/locales/en.json

Relevant issue: fixes #4924
Relevant Reddit post:  https://old.reddit.com/r/Enhancement/comments/9xmmg7/force_user_flair_to_be_text_only/
Tested in browser: Firefox (63.0.3)
Option was placed in the Style Tweaks module:
Before and after example from r/soccer:

Flair emojis as text option #4924

---

lib/css/res.scss
lib/modules/dashboard.js
lib/modules/filteReddit/LineFilter.js
lib/options/settingsConsole.js
lib/utils/caseBuilder.js
lib/utils/dom.js
lib/utils/index.js
lib/vendor/index.js
lib/vendor/jqueryPlugins.js
package.json
yarn.lock

jquery-sortable is broken in the settings console, and is no longer maintained. Sortablejs appear to work fine with minimal configuration.
Tested in browser: Chrome 73, Firefox 65

Replace jquery-sortable with sortablejs

---

lib/modules/hosts/twitchclips.js

Relevant issue: #5147
Tested in browser: Chrome v77.0.3865.90, Firefox v69.0.1
Test case:
1. Go to Reddit linkpost that uses the form "twitch.tv/<CHANNEL>/clip/<CLIP_NAME>". [Here](https://redd.it/d8zx51) is an example as of this PR.
2. Click expando under post title.
3. Observe expanded media element.
Before this change, the channel's livestream player would be expanded. After this change, the linked clip's player should be expanded.

Add expando support for channel-based Twitch clip URL scheme

---

lib/css/res.scss

Minor CSS adjustment to fix alignment of buttons on url-scheme multireddits
**Example link:** `https://old.reddit.com/r/news+worldnews+politics`
**Before and after:** https://i.imgur.com/hAYwKUm.gifv
**Tested in browser:** Chrome, Firefox

Minor CSS fix for button alignments on multis

---

lib/css/modules/_nightMode.scss

Fixes https://www.reddit.com/r/RESissues/comments/dskthl/white_background_for_comments_that_are_children/
Tested in MS Edge Version 80.0.320.3 (Official build) dev (64-bit)

Fix Nightmode issue with removed comments

---

lib/modules/hosts/streamvi.js

This pull request fixes a bug that is preventing Streamvi links from being loaded from RES.
RES incorrectly loads the video, image, and logo from Streamvi links in Chrome and Firefox. For example, video requests were being sent to `https://cdn.streamvi.com/uploads/watch.php.mp4` instead of `https://cdn.streamvi.com/uploads/{id}.mp4`.
Streamvi is a popular site for hosting soccer clips on the r/soccer subreddit, and this bug is currently affecting 4/10 top posts on the subreddit right now.
Tested in browser: *Chrome*, *Firefox*

Fix Streamvi link expansion

---

lib/css/modules/_accountSwitcher.scss
lib/modules/accountSwitcher.js

Currently, the page just sits and appears to be doing nothing when you choose an account to switch to. This change makes the cursor spin while the ajax request is being made and resets the cursor after the ajax request is complete. 
Tested in chrome 78

Added visual indication of account switching

---

lib/utils/browserDetect.js

Fix browser detect for new Edge

---

lib/modules/nightMode.js
lib/modules/submitIssue.js
lib/modules/userTagger.js
locales/locales/en.json

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
Tested in browser: Firefox 71, Chrome 79

nightMode: Add option to follow media query 'prefers-color-scheme: dark'

---

lib/css/modules/_nightMode.scss

Fix nightmode on copyright takedowns.

---

lib/environment/background/auth.js
lib/modules/backupAndRestore.js
lib/modules/backupAndRestore/providers/OneDrive.js
locales/locales/en.json

Fixes #5184
After this change, OneDrive backups in Firefox are separate from OneDrive backups in other browsers. Microsoft requires that all redirect URIs for an application are on the same domain. In Firefox 75 and later we are forced to use a Mozilla domain like f6be6623b0b4ed4e84464ff8b07afff3c421e497.extensions.allizom.org, which of course is different from redditenhancementsuite.com. So there is now a separate "Reddit Enhancement Suite (for Firefox)" OneDrive application used in Firefox.
Tested in browser: Firefox 75

Use getRedirectURL in Firefox to fix backups in 75 and later

---

lib/modules/showImages.js

Per chromium code, ~ is a illegal character and will not allow downloads if this is in the filename.
https://github.com/chromium/chromium/blob/master/base/i18n/file_util_icu.cc#L81
Relevant issue: https://www.reddit.com/r/RESissues/comments/fzv2x4/media_download_fails_when_title_contains_certain/
Tested in browser: Edge Version 80.0.361.111 (Official build) (64-bit)

Add ~ as defined illegal character.

---

.travis.yml

We dont publish to Opera anymore as the version 2 years ago is still pending review.

Remove opera creds

---

lib/css/res.scss

Swap text colour to make it clear on addrow button

---

lib/modules/showImages.js

Chrome gets funny with Emojis blocking downloads, theres no way to know which ones so this just removes all emojis from the title on save.
One potential issue is if images have an only emoji title.
Tested in browser: Edge 81

Remove Emojis from image downloads

---

package.json

They are mismatched against buildservers and can take ages to complete preventing pushes and causing poor UX with the RES repo.

Remove Husky pre-push checks.

---

chrome/beta/manifest.json
chrome/manifest.json
lib/modules/backupAndRestore/providers/GoogleDrive.js

The Google OAuth token retrieval did an additional redirection before landing at `redditenhancementsuite.com`, which was unnecessary and not support by our system.
Relevant issue: Fixes #5212
Tested in browser: Chrome 84, Chrome 75

backupAndRestore: Fix Google Drive token retrieval

---

lib/css/modules/_nightMode.scss

Update nightmode so the COVID alert box isnt like a shining star.
Tested in browser: Edge 81.0.416.72

Update nightmode for happening now box.

---

chrome/beta/manifest.json
chrome/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/modules/hosts/twitter.js

Twitter's got a new oEmbed API endpoint. This updates RES to use it.
This will prompt a new twitter api permissions request.
Tested on Edge 83/Firefox 76.

Update Twitter API

---

lib/modules/hosts/twitch.js

Fixes #5123 
Twitch changed their API requirng the domain location in the URL. This adds www and old. We dont touch redesign so can ignore new as Reddit handle that natively. They said they won't support wildcard (*.) so if anyone uses subdomains like np. they are out of luck.
https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956

Update Twitch with latest API changes.

---

lib/modules/hosts/strawpollcom.js

URL no longer works on www. and causes error. Corrects to right URL for detection.

Fix Strawpoll URL redirect loop.

---

lib/modules/hosts/vreddit.js
lib/modules/showImages.js
locales/locales/en.json
package.json
yarn.lock

Allows inlining v.redd.it links, and to replace the native player for faster and improved user experience.
- Uses the dash.js library
- Since it is fairly large, it's loaded separate from the foreground bundle and only on demand
- When `forceReplaceNativeExpando` is enabled, Reddit's video player script is no longer loaded
- Improves load times a little
Relevant issue: Fixes #4745
Tested in browser: Firefox 79, Chrome 85

showImages: Support embedding all v.redd.it videos 

---

chrome/beta/manifest.json
chrome/manifest.json
firefox/beta/manifest.json
firefox/manifest.json

It looks like we dont use cookies at all and identity is only used on FF. Chrome team rejected RES due to cookies and identity perms when not used.

Remove unused permissions

---

package.json
yarn.lock

Relevant issue: fixes #5253
Tested in browser: Chrome 87, Firefox 82
See commit message.
Before:
After:
The other 262k buffer is from fast-levenshtein.

Update snudown-js to 3.2.0

---

lib/modules/showImages/templates.js
lib/utils/table.js

Relevant issue: None, I just did this without creating one
Tested in browser: Chrome 85 on Windows 10

Added support for screen readers to gallery view and tables

---

CONTRIBUTING.md

I got this error when I ran `yarn` with node version 8.

Update node version requirement in CONTRIBUTING.md

---

.travis.yml
webpack.config.babel.js
yarn.lock

Removes Firefox beta since we don't use them anymore and adds Opera with no source map per their request and Edge for ease.

Cleanup build releases.

---

lib/environment/background/auth.js
lib/modules/hosts/twitchclips.js

Twitch has started appending hyphen + random string to the end of their auto-generated clip names, causing the twitchclips regex to not match anymore.
Fixes the issue mentioned in /r/Enhancement:  
[[Request] Twitch recently changed the format of their clips URLs which has affected functionality.](https://reddit.com/r/Enhancement/comments/lhk8hq/request_twitch_recently_changed_the_format_of/)
Tested in browsers:
* Firefox 85.0.1
* Chrome 88.0.4324.150

Update twitchclips regex for new clip names.

---

lib/modules/hosts/twitchclips.js

Twitch has a few additional formats for the clip names, including double
hyphens and also ending with a hyphen. Relaxed the Regex for twitch clip
name matching so that the hyphen character will be treated as one of the
characters in the randomly generated string.
This means this will now match any additional string appended that uses
the hyphen or the characters from the \w set (A-Za-z0-9_).
Relevant issue: Fixes #5284 
* Firefox 85.0.2
* Chrome 88.0.4324.182

Relax regex on twitch clip names.

---

lib/modules/nightMode.js

The settings console doesn't run in the reddit.com-context, and requires that an additional permission to geolocation is provided in the manifest-file and granted by the user. Since automatic nightmode isn't really that useful for the settings console, the easiest solution is to just ignore the issue.
Relevant issue: #5290
Tested in browser: Firefox 87, Chrome 88

nightmode: Silence geolocation permission issue in settings console

---

lib/modules/backupAndRestore/providers/File.js

Saw this request popup on https://www.reddit.com/r/Enhancement/comments/nqq7dw/backup_file_names_to_include_leading_0s_in_date/ which seemed sensible and easy to add.
Effectively just tweaking the save filename so that it includes leading 0's on filename date for easier sorting of backup files.
Previous output was: `RES-2021-6-2-1622657669-xxx.resbackup`
New output is `RES-2021-06-02-1622657669-xxx.resbackup`
Relevant issue: Not yet logged.

[Minor] Include leading zeros on RES backup filename

---

lib/modules/showParent.js

The <kbd>Shift</kbd>-<kbd>P</kbd> shortcut which shows parent posts is currently broken—it does nothing when pressed.
Luckily the fix was simple. `Hover`'s `watch` method doesn't return anything, and the `hover` variable was always assigned `undefined` instead of the `HoverInfoCard` object that was intended.
(Chromium: 91.0.4472.124)

showParent: Fix Shift-P not working

---

lib/modules/subredditManager.js

Resolves #5360 by waiting for the child element that isn't getting loaded in time instead of the parent, then passes parent to `createSubredditBar()`

Resolves #5360 and restores Home button

---

lib/css/modules/_subredditInfo.scss

Relevant issue: No issue, but quite a few times I've clicked on 'Filter' and accidentally selected the text on the button, rather just clicking it. This resolves that entirely!
Tested in browser: Edited the CSS manually in Chrome to verify that `.subredditInfoToolTip .bottomButtons` is a selector and `user-select: none;` is the rule.

Disable mouse selecting on subreddit info buttons

---

lib/modules/showImages.js

Relevant issue: #5354
Tested in browser: Chrome version 97.0.4692.71

trimmed title for image download to prevent leading whitespace

---

lib/modules/hosts/redgifs.js

This change is safe to make as RedGIFs are always muted even if they have audio.
Relevant issue: #5233

#5233: RedGIFs expandos do not expand when clicking "Show Images"

---

lib/modules/userTagger.js

Relevant issue: #5351 
Tested in browser: Chrome 97

Display user tags that have a colour without any text

---

lib/modules/showImages.js

In old.reddit.com, a reddit gallery's title link can be misleadingly set to the source link in the gallery's caption instead of the normal reddit.com/gallery/\<id\> URL. The only reliable indication that a post is a reddit gallery is by checking the "data-is-gallery" attribute in the Thing element.
An example of reddit gallery post with a mangled title link: https://old.reddit.com/r/manga/comments/stv143/disc_sir_liebe_von_trapp_ch_4_5_by_isiyumi/

Reliably detect reddit gallery posts with a caption link

---

lib/modules/hosts/youtube.js

Relevant issue: #5364
Tested in browser: Firefox 90.0.1/99.0.1
No pause/play commands were defined for YouTube. This PR adds such commands, accessible through the [iframe API](https://developers.google.com/youtube/iframe_api_reference)

Fix YouTube's video pausing

---

lib/modules/showImages.js

Google added a required `client` parameter to this type of reverse image search, noted at https://webapps.stackexchange.com/questions/167766/reverse-google-image-search-via-url-after-2022-switch-to-google-lens

Update showImages.js to fix google reverse image search URL

---

lib/css/modules/_nightMode.scss
lib/modules/commentStyle.js

Relevant issues: 
fixes #5419, see https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/5419
fixes #5415, see https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/5415
Tested in browser: Chrome, Firefox
Solutions:
#5419, added a selector to target the specific element and to correctly modify its color to match other header links
#5415,  included the 'profile' page type into the commentStyle module to gain access to the relevant stylings that the comment page has.

Fix styling issues for subreddit names and fixed an issue with comment styles on profile overview page

---

lib/modules/hosts/pixiv.js

Seems that pixiv changed the embed code URL. There's an API which generates an iframe URL which can be accessed at the URL: `https://embed.pixiv.net/oembed.php?url=https%3A%2F%2Fwww.pixiv.net%2Fen%2Fartworks%2F94743400` (94743400 being an example ID)
This returns back:
`"html": "<iframe width=\"600\" height=\"315\" src=\"https://embed.pixiv.net/oembed_iframe.php?type=illust&id=94743400\" frameborder=\"0\"></iframe>",`
The only thing is that the embed no longer seems to size the images it turns any more, it's usually a "part" of the image.
Example from here: https://github.com/medjedqt/kiyobot/issues/16
So it seems like this is intentional so may have to suffice.

Update pixiv.js to new embed URL

---

lib/modules/hosts/youtube.js

Tested in browser: Firefox Nightly 113.0a1
This adds support for embedding YouTube videos from a shorts URL.

Embed YouTube Shorts

---

lib/utils/watchers.js

Fix did not resolve dupes in NER and caused further breakage. The dupe issue appears to be Reddit API side from what I can tell.

Revert ID change to 9 and 10

---

lib/modules/hosts/redditgallery.js

Reddit posts with multiple images can also have selftext, which is replaced by expandos / doesn't display in post list views.
Pass through the selftext_html as per #5444.
Tested in browser: Chrome 111.0.5563.147

Add captions to reddit gallery expandos

---

lib/modules/hosts/ireddit.js
lib/modules/hosts/vreddit.js
lib/types/reddit.js

A crosspost doesn't copy selftext but it can be retrieved via `crosspost_parent_list`.
It was a bit of a pain specifying the exact type of the list but I think this is the right way and `yarn flow check` is happy.
Relevant issue: https://www.reddit.com/r/RESissues/comments/zqvuis/inline_image_viewer_missing_text/jfb22mn/
Tested in browser: 111.0.5563.147

Get captions for crossposted reddit media

---

lib/modules/hosts/wikipedia.js

Relevant issue: Often these errors appear because a notelist appears in the article but not in the lede. 
Tested in browser: Waterfox with [this post](https://www.reddit.com/r/todayilearned/comments/14awpft/til_that_gerard_way_started_my_chemical_romance/)

Also clear cite errors in Wikipedia

---

build.js
firefox/beta/manifest.json
firefox/manifest.json

Need 120 for https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request. Keeping main at 115 for ESR.

Firefox Mobile needs min 120 due to API support

---

chrome/beta/manifest.json
chrome/manifest.json

It says you cant, but testing says you can. Avoid disable and permission prompt. Will test in beta.

Move Geolocation to optional

---

lib/modules/hosts/twitter.js

MV3 no longer allows remotely hosted code - https://developer.chrome.com/docs/extensions/develop/migrate/improve-security#remove-remote-code
This aligns with Firefox and fixes RHC error.

Remove twitter external script

---

lib/modules/hosts/twitter.js

Relevant issue: The Twitter rename to 𝕏 means that any  `𝕏.com` links won't be detected for e𝕏pandos--this is a quick fi𝕏 to resolve the issue.
Tested in browser: chrome, firefo𝕏, arc

Add support for twitter e𝕏pandos on 𝕏.com links (twitter rename)

---

lib/modules/showImages.js

Appears to resolve https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/5511
Tested in Chrome and Firefox.

Remove showImages onInit

---

lib/modules/showImages.js

It seems like the issue resolved in #5512 did more than just improving performance. In some cases it also prevented Reddit's video player from being initialized in the background, causing audio being played.
This PR reworks the reverted code by caching the setting value in localStorage and thereby letting us avoid having the `undo` logic (which is incompatible with manifest V3).
Relevant issue: Fixes #5519 
Tested in browser: Chrome 124

showImages: Fix audio being played in the background

---

lib/modules/keyboardNav.js
lib/modules/showImages.js
locales/locales/en.json

This adds a keyboardNav bind (default 'o') to toggle mute/unmute on the current most visible video expando.

Feature: Add keyboard shortcut to toggle mute on expando videos

---

lib/modules/hosts/imgur.js
locales/locales/en.json

- Fixes video retrieval (the API no longer contains the property `gifv`)
- Removes option `useGifOverGifv` which seemingly is broken
- Removes redundant protocol replacement, as Imgur now always responds with https
Relevant issue:  https://www.reddit.com/r/RESissues/comments/1exm5b7/imgur_gifgifvmp4_expandos_broken/
Tested in browser: Chrome 128

showImages/hosts: Update Imgur

---

lib/core/migrate/migrate.js
lib/modules/commentTools.js

I noticed the links in the reddiquette macros were hitting a landing page with a manual redirect. This PR just updates the links to go directly to the reddiquette page in its new location.

Reddiquette links

---

lib/environment/background/permissions.js

`window.screen` is not available in manifest v3, causing the prompt window fallback method to fail. This uses the web extension API to find the coordinates to place the popup.
The fallback method is ordinarily not needed in Chrome, but other extensions may interfere (see #5531) Chrome's detection of user initiated permission requests.
Relevant issue: #5531 
Tested in browser: Firefox 130, Chrome 128

environment/permissions: Fix permission popup not showing

---

chrome/beta/manifest.json
chrome/manifest.json
firefox/beta/manifest.json
firefox/manifest.json
lib/modules/hosts/bluesky.js
lib/modules/hosts/index.js

Noticed a post in /r/hockey that had a bsky.app link but didn't have an expando. Wanted to be the change I wanted to see in the world so I added support for it. Implemented it similarly to the Twitter/X module. Here it is:
I believe any video playing is just related to what bluesky offers in the embed, so unfortunately you still need to navigate to the page to view the video player.
Tested in browser:  Firefox

Added support for bluesky expandos

---

lib/modules/hosts/redditpoll.js

Relevant issue: Poll expandos currently redirect to the comments.

Fix: reddit poll expando redirects to comments
