honestbleeps/Reddit-Enhancement-Suite

- lib/css/modules/_nightMode.scss
https://www.reddit.com/r/Enhancement/comments/59ee29/blue_links_in_night_mode_theme_are_very_tough_to/
> Nightmode styling for source-url

- lib/modules/pageNavigator.js
- lib/utils/Thing.js
> Use improved Thing methods for PostNavigator ShowLink

- lib/modules/hosts/archiveis.js
Allows the image in linked archive.is pages to be expanded via RES.
Tested against https://www.reddit.com/domain/archive.is
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1008
> Archive.is expando

- lib/modules/hosts/getyarn.js
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3580
Examples: https://www.reddit.com/domain/getyarn.io/
> Add getyarn mediahost

- .travis.yml
...~~if~~since it makes the overall build noticeably faster
> [maybe] break up Travis CI build into multiple jobs

- .travis.yml
...to keep everything in one place.
~~Not sure if we want to do this yet.~~
> Move Travis CI secure env vars from web config to .travis.yml

- lib/modules/filteReddit/postCases.js
- lib/modules/showImages.js
This avoids creating filters which cannot be evaluated.
> filteReddit: parsing improvements

- lib/modules/sourceSnudown.js
- tests/sourceSnudown.js
Fixes https://www.reddit.com/r/RESissues/comments/5cjzta/bug_cant_use_source_more_than_once_in_any_given/
> Fix viewing source multiple times on one page

- lib/modules/showImages.js
Avoids trashing in order to determine viewport(Width|Height).
> showImages: Set mediaMaxSize as internal style

- lib/modules/showImages.js
> showImages video: Fix fallback to image

- lib/core/modules/modules.js
- lib/modules/RESTips.js
- lib/modules/messageMenu.js
- lib/modules/multiredditNavbar.js
- lib/modules/notifications.js
- lib/modules/presets.js
- lib/modules/saveComments.js
- lib/modules/search.js
- lib/modules/settingsConsole.js
- lib/modules/settingsNavigation.js
- lib/templates/settingsConsoleModuleSelector.mustache
Splits #3584 
TODO:
~~Fix search (changes broke it)~~
~~Implement changes for module options.~~
> i18n Module Framework

- lib/css/modules/_userTagger.scss
- lib/modules/showParent.js
- lib/modules/userTagger.js
Tagging is still functional for when the option is off, but the tagging tool must be accessed through vote tracker.
> userTagger: Add option for whether to show tagging icon

- lib/modules/showImages.js
Preloads `browsePreloadCount` number of expandos when using mediaBrowseMode (keyboard navigation).
> Preload media when using mediaBrowseMode

- lib/modules/showImages.js
Pretty much just a code style change.
> showImages: Remove duplication in findAllImages()

- lib/modules/commentTools.js
> change the selector used for finding the textarea

- lib/css/modules/_nightMode.scss
- lib/css/modules/_styleTweaks.scss
- lib/modules/styleTweaks.js
Fixes [#3129](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3129)
I couldn't find the resupdates.css though so I only added this in the nightmode file.
There are 2 commits because on my first push the code formatting wasn't correct.
> Added max-width and max-height to #header-img-a (nightmode)

- lib/modules/hosts/imgur.js
> imgur: when fetching gallery fails, try falling back to album

- lib/css/modules/_nightMode.scss
- lib/css/res.scss
- lib/modules/subredditInfo.js
- lib/modules/subredditManager.js
adds a count badge to the right hand SR info area and the subreddit info popover seen when hovering over a SR link
fixes #3047
> add a count of multis a SR is in next to the subscribe button

- lib/modules/nightMode.js
> /r/all, /r/friends, and /r/mod are nightmode compatible

- lib/css/modules/_neverEndingReddit.scss
- lib/modules/neverEndingReddit.js
> Completely remove dupes when hideDupes is set to 'hide'

- lib/css/modules/_nightMode.scss
- lib/css/modules/_subredditManager.scss
- lib/modules/subredditManager.js
> Rebase and update #2389: Shortcuts Easy Delete

- lib/modules/nightMode.js
...instead of just on pageload, and only in focused tabs.
Fixes #2502
Closes #2503
> Check for automatic nightmode every 5 minutes

- lib/modules/showImages.js
> showImages gallery: Fix filmstrip

- lib/css/modules/_commentStyle.scss
- lib/css/modules/_nightMode.scss
> commentBoxes: restore pink background for removed child comments

- lib/modules/commentHidePersistor.js
- lib/modules/commentTools.js
- lib/modules/dashboard.js
- lib/modules/newCommentCount.js
- lib/modules/selectedEntry.js
- lib/modules/showImages.js
- lib/modules/showParent.js
- lib/modules/subredditInfo.js
- lib/modules/subredditManager.js
> Replace $.fn.data with $.fn.attr for reading data-attributes

- lib/modules/commentPreview.js
> Remove inline wiki images with external URLs

- lib/core/host.js
- lib/css/modules/_showImages.scss
- lib/modules/hosts/coub.js
- lib/modules/hosts/dailymotion.js
- lib/modules/hosts/eroshare.js
- lib/modules/hosts/getyarn.js
- lib/modules/hosts/iloopit.js
- lib/modules/hosts/livecap.js
- lib/modules/hosts/oddshot.js
- lib/modules/hosts/qwipit.js
- lib/modules/hosts/streamable.js
- lib/modules/hosts/twitch.js
- lib/modules/hosts/twitchclips.js
- lib/modules/hosts/uploadly.js
- lib/modules/hosts/vidlit.js
- lib/modules/hosts/vimeo.js
- lib/modules/hosts/youtube.js
- lib/modules/showImages.js
- lib/templates/iframe.mustache
Compared to previous solution, this accepts keyboard navigation and moving the iframe.
> showImage: Reuse common move/resize functions for iframes

- lib/css/modules/_userTagger.scss
- lib/modules/userTagger.js
> Rebase and update #2437: Enhance UX for ignoring users

- lib/css/modules/_styleTweaks.scss
> styleTweaks: Fix vertical alignment on subreddit style toggle

- lib/core/options/options.js
- lib/environment/permissions.js
- lib/environment/storage.js
- lib/modules/RESTips.js
- lib/modules/announcements.js
- lib/modules/commentHidePersistor.js
- lib/modules/commentTools.js
- lib/modules/dashboard.js
- lib/modules/filteReddit/Filter.js
- lib/modules/neverEndingReddit.js
- lib/modules/newCommentCount.js
- lib/modules/nightMode.js
- lib/modules/notifications.js
- lib/modules/onboarding.js
- lib/modules/quickMessage.js
- lib/modules/saveComments.js
- lib/modules/showImages.js
- lib/modules/styleTweaks.js
- lib/modules/subredditManager.js
- lib/modules/troubleshooter.js
- lib/modules/userTagger.js
For (more-or-less) type safety at storage boundaries
> Storage.wrap

- lib/modules/filteReddit.js
- lib/utils/__tests__/async.js
- lib/utils/async.js
- lib/utils/index.js
Depends on #3679
Now, regardless of your combination of external filters and filterline filters (and as long as storage isn't _really_ slow), posts will only be processed once on pageload. (Previously they would be processed once by external filters and once again by filterline filters in the next tick)
> Filter init optimization

- lib/modules/commentNavigator.js
> commentNavigator: Fix onScroll

- .travis.yml
so we get coverage info back from coveralls faster
> run unit tests before building

- lib/core/module.js
- lib/core/options/options.js
> options: add onChange callback

- lib/modules/filteReddit.js
> Leverage reddit's native /r/all filters

- lib/modules/hosts/loophouse.js
Loophouse is a new service to make & share short video clips.
> Add Loophouse.tv as media host

- lib/core/host.js
- lib/css/modules/_showImages.scss
- lib/modules/showImages.js
- lib/templates/videoAdvanced.mustache
https://www.reddit.com/r/RESissues/comments/5fx8vd/captions_not_showing_up_in_imgur_gallery/
> Video captions

- build/getChanges.js
- firefox/beta/package.json
- firefox/package.json
- package.json
- yarn.lock
Closes #3444
Creates a CHANGES file in the root dir with a link to https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/v5.0.3...v5.1.9 or https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/v5.0.3...v5.1.8-4-g52dcf24 if you're not on a tag (which also works fine).
> Link to diff in firefox package

- lib/core/migrate.js
https://www.reddit.com/r/RESissues/comments/5gg07i/bug_multireddit_submenu_contains_instead_of_in_a/darz290/
https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/6e951b68b4222cb3e542c9c4e1c87cda78ba9f54
> Reset ../ to ./ in multireddit nav menu section links

- lib/modules/hosts/eroshare.js
Thank you for the suggestions on the previous pull request.
> Eroshare host file updated to exclude subdomains.

- lib/modules/voteEnhancements.js
https://www.reddit.com/r/RESAnnouncements/comments/5go2xd/announcement_res_v520_release/datq9kt/
> run voteEnhancements on profile and inbox pages

- lib/utils/Thing.js
> Accommodate fancy scores

- lib/modules/filteReddit.js
Fixes #3716 
`applyList` is lower-cased.
> filteReddit: Fix case issue in filtersMatchString

- lib/modules/multiredditNavbar.js
https://www.reddit.com/r/RESissues/comments/5gqupy/bug_multireddit_navigation/
> Run multiredditNavbar on all pages that have the multireddit sidebar

- lib/modules/subredditManager.js
> Add title to multi-count

- lib/css/res.scss
- lib/modules/announcements.js
> announcements: replace orangered bell with goldenrod megaphone

- lib/utils/expando.js
> showImages expando: Do not concern itself whether attached to document

- lib/modules/subredditManager.js
- locales/locales/en.json
#3747 
Can't merge this yet cause we need other languages to be updated
> localize multi-count title

- lib/modules/easterEgg.js
Still getting a hang of the typing system.
> easterEgg: Add types to a few things

- lib/core/migrate.js
- lib/core/modules/modules.js
- lib/modules/stylesheet.js
Fixes https://www.reddit.com/r/RESissues/comments/5ihx26/bug_modmail_beta_res_night_mode_style_applies/, because no top-level code in modules will run if init doesn't run, so the multicast handler won't get added.
> Don't import modules if init doesn't run

- lib/modules/hosts/gfycat.js
- locales/locales/en.json
> Add low-resolution (mobile) option for loading gfycat links

- lib/modules/hosts/miiverse.js
- lib/modules/hosts/twitter.js
- lib/modules/showImages.js
> showImages expando: Set host ID as data attribute

- lib/modules/nightMode.js
- locales/locales/en.json
> Add nightMode.js strings to i18n

- lib/utils/__tests__/location.js
- lib/utils/location.js
- tests/sourceSnudown.js
https://www.reddit.com/r/RESissues/comments/5j77zi/comment_source_not_showing_correctly/
> commentsPermalink regex should allow unicode characters in title stub

- lib/modules/keyboardNav.js
The description strings weren't converted
> keyboardNav drawHelp: Fix i18n issue

- nightwatch.conf.js
- tests/i18n.js
- tests/menu.js
- tests/saveComments.js
- tests/search.js
- tests/settingsConsole.js
- tests/sourceSnudown.js
> nightwatch: set default timeout, remove explicit timeouts

- lib/css/modules/_filteReddit.scss
- lib/templates/filterline.mustache
The features appears to be working as expected now.
> Filterline: Remove beta notice

- lib/modules/pageNavigator.js
- locales/locales/en.json
> Add option to page navigator to scroll to comment box

- lib/modules/search.js
- locales/locales/en.json
Start searching for options immediately after the user starts typing in the search box.
Mad progrmming skillz.
Also vastly improved search drawing performance by switching to pure JavaScript:
> Implement search as you type, search performance improvements

- lib/modules/commentDepth.js
- lib/modules/settingsConsole.js
- locales/locales/en.json
> Add minimum comment count to enable custom comment depth

- appveyor.yml
> use Appveyor's native Yarn

- lib/core/migrate.js
- lib/modules/userTagger.js
- locales/locales/en.json
Split off from #3809 for @jakewilson / changelog convenience.
Part of #3755
Closes #3800
> UserTagger: hardIgnore by default, add i18n

- lib/modules/xPostLinks.js
- tests/xPostLinks.js
https://www.reddit.com/r/test/comments/5lbdav/xpost_longest_ever_xpost_subreddit_the_reddit/ (they haven't even reported this yet 😜)
> xPostLinks: limit the length of subreddit names

- lib/modules/commentQuickCollapse.js
- lib/utils/Thing.js
- locales/locales/en.json
Split off from #3809 for @jakewilson / changelog convenience.
Closes #3809 
Closes #3798
> CommentQuickCollapse

- lib/css/modules/_floater.css
- lib/css/modules/_neverEndingReddit.scss
- lib/css/modules/_orangered.scss
- lib/css/modules/_pageNavigator.scss
> floater: Fix alignment of items

- lib/css/modules/_commentNavigator.scss
- lib/css/modules/_newCommentCount.scss
- lib/css/modules/_nightMode.scss
- lib/modules/commentNavigator.js
- lib/modules/commentPreview.js
- lib/modules/commentTools.js
Pushing down the sitetable is disrupting as it happens ~0.5 s after it is visible.
Fixes #3625 
Resolves #2309
Edit (@erikdesjardins): closes #3627 (superseded)
Before:
After:
> comments page: Avoid having enhancements push down sitetable

- .flowconfig
- lib/core/metadata.js
- lib/core/metadata/index.js
- lib/core/metadata/packageInfo.js
- tests/onboarding.js
http://redditenhancementsuite.com/latest/
Shows the latest release/pre-release with contribute info and have you been here before info.
> Update RES update page to new /latest/ page.

- lib/css/modules/_accountSwitcher.scss
- lib/modules/accountSwitcher.js
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1828
> Add link in account switcher dropdown to the accounts profile page

- lib/modules/notifications.js
> Fix notification sticking around after clicking [X] 

- lib/modules/search.js
- tests/commandLine.js
- tests/search.js
> Fix command line settings search

- lib/modules/commentTools.js
Fixes https://www.reddit.com/r/RESissues/comments/5n9kp7/bug_ctrlenter_no_longer_submits_posts/
> commentTools: add ctrl-enter listeners in go()

- tests/filteReddit.js
Otherwise, they might erroneously pass if the test string was lowercased.
re #3881
> make some case-insensitivity tests more rigorous

- lib/css/res.scss
- lib/modules/settingsConsole.js
- lib/templates/settingsConsoleModuleSelector.mustache
> Add Module descriptions to settings console

- flow/lib/lodash.js
- lib/modules/filteReddit.js
- lib/types/reddit.js
- lib/utils/__tests__/async.js
- lib/utils/async.js
- lib/utils/index.js
- locales/locales/en.json
This somewhat abuses reddit's API, so it may not be a viable solution.
We really need a batch subreddit info endpoint.
> [experimental] sync the 100 most popular subreddits to native /r/all filters

- lib/modules/hosts/youtube.js
- lib/utils/location.js
> youtube: use insertParams

- lib/modules/search.js
- lib/templates/optionLinkSnudown.mustache
- tests/search.js
e.g. right now https://www.reddit.com/#res:settings/search/inlinein errors if you try to export the link for Inline Image Viewer
> search: fix exporting links to modules

- lib/css/modules/_showImages.scss
- lib/modules/showImages.js
> Add "warning" candystripe overlay to spoiler expando buttons

- lib/css/modules/_nightMode.scss
Now it's orange to correspond to candy stripes!
> Update spoiler nightmode

- lib/core/host.js
- lib/modules/hosts/gfycat.js
- lib/modules/showImages.js
Adds a reversed option and runs reverse() when reversed is true. closes #3399
> Add reversed option for gfycat

- lib/modules/hideChildComments.js
- locales/locales/en.json
> Rebase and update #3267: Allow hiding children of nested comments

- webpack.config.babel.js
Oh no, more build special cases :(
> Workaround Edge bugs with arrow function destructuring

- lib/modules/hideChildComments.js
- lib/modules/userHighlight.js
- lib/utils/Thing.js
- tests/userHighlight.js
> Fix highlightFirstCommenter highlighting all repliers instead of only top level

- lib/modules/selectedEntry.js
- tests/keyboardNav.js
and add some keyboard nav tests.
> Fix loss of keynav outline after j/k in quick succession

- lib/core/migrate.js
- lib/modules/styleTweaks.js
> Enable hideUnvotable by default

- lib/modules/keyboardNav.js
- lib/modules/selectedEntry.js
- lib/utils/dom.js
Adopts the `from` element's position relative to the viewport when scrolling to the new element.
@KetillG
> scrollStyle adopt

- lib/css/res.scss
- lib/modules/settingsConsole.js
- lib/modules/userTagger.js
- lib/templates/settingsConsole.mustache
- lib/utils/createElement.js
Closes #3908 
I'm not too sure what to do about the changing width, or if these changes mess anything else up 😶
> Change up the toggles to move text to the right

- .babelrc.json
- firefox/beta/package.json
- firefox/package.json
- package.json
> remove transform-es2015-block-scoping

- lib/utils/dom.js
Fixes viewport bounds compensation
> scrollStyle adopt fix

- lib/css/modules/_pageNavigator.scss
> Nightmode for pageNavigator showLink

- lib/modules/accountSwitcher.js
- tests/accountSwitcher.js
…instead of breaking completely
Fixes #3937
> accountSwitcher: display the username when loading userInfo fails

- lib/modules/filteReddit/postCases.js
- lib/utils/Thing.js
Edit(@erikdesjardins): Fixes #3894
> "Post is spoiler" custom filter

- lib/modules/hosts/liveleak.js
https://www.reddit.com/r/Enhancement/comments/4e8416/feature_request_a_dropdown_video_player_for/
~~Alas, Liveleak has zero HTTPS support, so this doesn't work. As soon as they do, it should.~~
Closes #3837 (superseded)
> Liveleak host

- lib/modules/pageNavigator.js
> Don't show jump to add comment if add comment form is missing

- lib/modules/settingsConsole.js
- tests/settingsConsole.js
This was exacerbated/revealed by #3946
> SettingsConsole: don't modify an option's field definition's default value

- lib/modules/showImages.js
> Remove data-inbound-url attribute

- lib/css/modules/_neverEndingReddit.scss
- lib/css/modules/_wheelBrowse.css
- lib/modules/floater.js
- lib/modules/wheelBrowse.js
> wheelBrowse: Reduce visual impact

- lib/modules/keyboardNav.js
- lib/modules/notifications.js
- locales/locales/en.json
This will show a prompt when encountering a shortcut which has a goMode callback in addition to some other callback.
Closes #3753 
Lays groundwork for #949
> keyboardNav: prompt on ambiguous shortcut

- lib/modules/commandLine.js
- lib/modules/submitHelper.js
https://en.reddit.com/r/Enhancement/comments/5pu994/feature_request_make_post_from_command_line/
> Command line "submit post"

- lib/modules/hosts/ireddit.js
- lib/types/reddit.js
- lib/utils/Thing.js
- lib/utils/thingMetadata.js
> Create new i.redd.it mediahost

- lib/modules/hosts/ireddit.js
> i.redd.it host: only handle .gifs

- flow/lib/suncalc.js
- lib/core/migrate.js
- lib/modules/nightMode.js
- locales/locales/en.json
- package.json
- yarn.lock
As requested in #3657.
It needs some works around descriptions, user preferences migration and error handling. I won't have time to do this so if you want, feel free to finish this :)
fixes #3657
> Add automatic Night Mode based on geolocation and suncalc

- lib/modules/filteReddit/ExternalFilter.js
- lib/modules/filteReddit/Filter.js
- lib/modules/filteReddit/Filterline.js
- locales/locales/en.json
It's probably not too uncommon among users to add a filter which causes every post to be hidden, without realizing what they've done or knowing how to remove it.
> filteReddit: notification when everything is filtered out

- lib/modules/commentTools.js
...instead of waiting for a field to be focused.
Fixes #3988
> commentTools: add length counters and autocomplete during go

- lib/modules/nightMode.js
Fixes https://www.reddit.com/r/Enhancement/comments/5siw9g/can_you_make_it_so_automaticnightmode_doesnt/
> nightMode: reject invalid automaticNightMode values instead of falling back to user-defined

- lib/modules/hideChildComments.js
Fixes https://www.reddit.com/r/Enhancement/comments/5sk097/how_do_i_unhide_all_the_child_comments_in_one_go/
https://www.reddit.com/r/RESissues/comments/5shr9s/is_res_now_literally_hiding_all_child_comments/
> hideChildComments: Fix automatic hiding all nested comments

- lib/css/modules/_nightMode.scss
- lib/css/res.scss
- lib/modules/showImages.js
> Set `.visited` on Thing

- tests/keyboardNav.js
> keyboardNav blur test

- lib/modules/selectedEntry.js
- lib/modules/sourceSnudown.js
- lib/modules/spamButton.js
- lib/modules/userHighlight.js
- lib/utils/Thing.js
- lib/utils/watchers.js
Resolves #4003 
This doesn't do anything about /r/.*/about/message/inbox/ or /r/.*/message/moderator/unread/ having wrong pageType, though.
> Support Thing.message

- lib/modules/betteReddit.js
> fixHideLinks fix

- lib/utils/__tests__/location.js
- lib/utils/location.js
> inbox pageType for more modmail pages

- lib/modules/settingsConsole.js
- tests/settingsConsole.js
https://www.reddit.com/r/RESissues/comments/5sveiv/unable_to_turn_off_browse_by_wheel_wheelbrowse/
> Fix disabling modules with no options

- lib/modules/sourceSnudown.js
LinkPosts don't have any source.
Closes #4010
> sourceSnudown: Ignore Thing.linkPost

- tests/sourceSnudown.js
> sourceSnudown: test for ignoring link posts

- lib/modules/about.js
Start to consolidate information to the website.
> Point contributors URL on about to website.

- lib/modules/showImages.js
> showImages: Fix stopping non-looping videos

- lib/css/modules/_neverEndingReddit.scss
- lib/modules/neverEndingReddit.js
https://www.reddit.com/r/Enhancement/comments/5tgey1/is_there_any_way_to_go_back_to_the_old_style_of/?utm_content=comments&utm_medium=new&utm_source=reddit&utm_name=multi
> Combine "NER failed (try something else)" into "end of NER" banner

- lib/modules/hosts/ireddit.js
a.k.a. "why can't you get a vpn".
https://www.reddit.com/r/Enhancement/comments/5ndixx/feature_request_add_an_option_to_use/
> Optionally load all i.redd.it media from i.redditmedia.com

- lib/modules/subredditManager.js
haven't actually tested it, but the implementation it's working against is:
If user is logged out, show:
[Popular](https://www.reddit.com/r/popular) | All | Random
If user is logged in, show:
[Front](https://www.reddit.com) | [Popular](https://www.reddit.com/r/popular) | All | Random
> Popular in subreddit manager

- lib/modules/filteReddit.js
- lib/modules/nightMode.js
- tests/filteReddit.js
i.e. filter subreddits in /r/popular
> Treat /r/popular like /r/all

- lib/modules/spamButton.js
Fixes https://www.reddit.com/r/RESissues/comments/5ugrg2/bug_rts_spam_button_not_working/
> spamButton: Fix URL autofill

- lib/modules/commentTools.js
- lib/modules/sourceSnudown.js
https://www.reddit.com/r/RESissues/comments/5ue4k7/bug_clicking_inside_the_source_box_opens_editing/
https://www.reddit.com/r/restests/comments/5uha3m/source_button_test/
> sourceButton: fixes

- tests/spamButton.js
> test for spamButton

- tests/commentTools.js
> Test for commentTools ignoring source textareas

- lib/modules/submitIssue.js
> Prevent RES Diagnostics re-dumping

- lib/modules/RESTips.js
- lib/modules/commandLine.js
- lib/modules/presets.js
- lib/modules/profileNavigator.js
- lib/modules/quickMessage.js
- lib/modules/searchHelper.js
- lib/modules/selectedEntry.js
- lib/modules/settingsNavigation.js
- lib/modules/userTagger.js
- locales/locales/en.json
And a first run of autoi18n on one module to reduce future conflicts
closes #3964 (superseded)
> [i18n] add titles to modules with previously-translated descriptions

- lib/core/module.js
- lib/modules/hosts/imgur.js
- lib/modules/hosts/raddit.js
- lib/modules/search.js
- lib/modules/settingsConsole.js
- locales/locales/en.json
> Enforce existence of option titles with Flow

- examples/module.js
- lib/modules/RESTips.js
- lib/modules/about.js
- lib/modules/commentTools.js
- lib/modules/dashboard.js
- lib/modules/filteReddit.js
- lib/modules/hosts/ireddit.js
- lib/modules/keyboardNav.js
- lib/modules/neverEndingReddit.js
- lib/modules/nightMode.js
- lib/modules/search.js
- lib/modules/settingsConsole.js
- lib/modules/showImages.js
- lib/modules/subredditManager.js
- lib/modules/voteEnhancements.js
- lib/templates/searchResultOption.mustache
- locales/locales/en.json
> Render option descriptions as markdown, translate remaining ones

- lib/modules/saveComments.js
Fixes https://www.reddit.com/r/RESissues/comments/5w17bm/bug_ui_saveres_disappears_after_clicking_unsaveres/
> saveComments: Fix button disappearance when unsaving

- lib/modules/hosts/gyazo.js
> Fixed gyazo expandos

- lib/core/migrate.js
- lib/modules/keyboardNav.js
- lib/utils/Thing.js
- locales/locales/en.json
Tested on all page types that SelectedEntry runs on.
> keyboardNav: Don't restrict linkAnnotations to comments	

- lib/modules/hosts/wikipedia.js
Fixes
https://www.reddit.com/r/RESissues/comments/5vjshc/bug_links_to_anchors_in_wikipedia_expandos/
https://www.reddit.com/r/RESissues/comments/5uk8y8/bug_geohack_links_broken_in_wikipedia_expandos/
> Wikipedia: Fix fragment and schemeless links

- lib/modules/pageNavigator.js
- lib/utils/dom.js
So combining mouse scroll and keyboard move shortcuts gets less annoying.
> pageNavigator: Hide showLink when using scrollTo

- flow/lib/lodash.js
- lib/environment/ajax.js
- lib/environment/multicast.js
- lib/environment/storage.js
- lib/modules/backupAndRestore/serialization.js
- lib/modules/filteReddit.js
- lib/modules/filteReddit/postCases.js
- lib/modules/hosts/derpibooru.js
- lib/modules/settingsConsole.js
- lib/modules/settingsNavigation.js
- package.json
- webpack.config.babel.js
- yarn.lock
~~This doesn't seem to improve parse or runtime performance (though it does reduce bundle size). -- needs retesting in Webpack 2~~
Reduces bundle size by ~100k and speeds up init by a few frames (a few tens of ms on my machine)
> Use lodash-webpack-plugin

- lib/modules/hosts/masterypoints.js
Currently only the player profiles are supported but I'll modify the host to support more urls later on
> Added masterypoints host

- lib/modules/hosts/twitchclips.js
> Support new twitch clips URLs without usernames

- lib/css/modules/_commentNavigator.scss
> commentNavigator: Fix dropdown sometimes hidden

- lib/core/migrate.js
> Migrate maxWidth and maxHeight to string

- lib/modules/newCommentCount.js
- tests/newCommentCount.js
Fixes https://www.reddit.com/r/RESissues/comments/5w5rz8/bug_in_subscribed_threads_the_unsubscribe_button/
> newCommentCount: Fix initial subscrible toggle state

- lib/modules/submitIssue.js
> Update counter when adding diagnostics info

- lib/css/modules/_orangered.scss
- lib/modules/orangered.js
- locales/locales/en.json
> Added .res-orangered-hideEmptyModmailButton to orangered css

- edge/manifest.json
> Resolve expando's failing for specific mediahosts on Edge

- chrome/manifest.json
- edge/edge.entry.js
- lib/modules/noParticipation.js
- lib/modules/pageNavigator.js
- lib/modules/subredditManager.js
- lib/utils/dom.js
- package.json
- yarn.lock
https://github.com/WebReflection/dom4
Passive listeners aren't properly passive, of course, but this at least prevents them from capturing.
> Polyfill DOM 4 methods in Edge

- lib/modules/accountSwitcher.js
- lib/modules/neverEndingReddit.js
> ner: Reset state on account switch

- edge/manifest.json
> Workaround for YT times not working on Edge

- chrome/background.entry.js
- lib/utils/alert.js
- package.json
- webpack.config.babel.js
- yarn.lock
Part of #3919, reverts #3918 (in practice, but not in spirit)
> Switch to a targeted workaround for Chakra "use before declaration" bug

- lib/modules/hosts/hastebin.js
Closes #4110 
There seems to be no way to hide the control panel on top of the page, so this embeds the raw content.
> Add hastebin host

- edge/appxmanifest.xml
- package.json
- webpack.config.babel.js
- yarn.lock
> update spawn-loader, cleanup Edge build

- chrome/manifest.json
- edge/manifest.json
- firefox/manifest.json
- lib/modules/hosts/pixiv.js
As requested:
https://www.reddit.com/r/Enhancement/comments/4mnll2/pixiv_image_support_someone_finish_this_off_and/
thanks [/u/arandomguydontmindme](https://www.reddit.com/user/arandomguydontmindme)
> Pixiv Mediahost.

- lib/modules/searchHelper.js
- locales/locales/en.json
> searchHelper: Restore "always search subreddit" option

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- examples/host.js
- locales/locales/README.md
> Update contributing docs

- lib/modules/showImages.js
> showImages: move href defaulting into render functions

- tests/showImages.js
To help prevent #4056 from subtly breaking it.
> Basic integration tests for showImages

- lib/modules/showImages.js
Relevant issue: fixes #4133
Tested in browser: Chrome 59
> Fix reddit gold visited post syncing

- chrome/manifest.json
- edge/manifest.json
- firefox/manifest.json
- lib/modules/hosts/steamcommunity.js
- lib/modules/hosts/steampowered.js
Relevant issue: fixes #2500
Tested in browser: chrome 59, firefox 54
> steamcommunity host

- lib/modules/hideChildComments.js
- lib/modules/neverEndingComments.js
- lib/modules/pageNavigator.js
Relevant issue: fixes #3314
Tested in browser: chrome 59
> Use some less-fragile selectors

- lib/modules/accountSwitcher.js
- locales/locales/en.json
Added extra i18n with snazzy snippet
```
'.source.js':
'RES-i18n':
'prefix': 'i18n'
'body': """
${i18n("$2")}${3:
"$2": {
"message": "$1"
\\},
}"""
```
part of #3755
> Accountswitcheri18n

- lib/core/migrate/migrate.js
- lib/modules/userbarHider.js
Relevant issue: fixes #2558
Tested in browser: chrome 59
> disable userbarHider by default

- browser/background.js
- flow/lib/dom.js
- lib/environment/ajax.js
- lib/modules/accountSwitcher.js
- lib/modules/hosts/onedrive.js
Tested in browser: chrome 59, firefox 54
> Switch XHR to fetch

- browser/background.js
- edge/edge.entry.js
- edge/remove-fetch.js
- lib/environment/ajax.js
- lib/modules/accountSwitcher.js
- package.json
- yarn.lock
Relevant issue: fixes #4156, fixes #4157
Tested in browser: Chrome 59, Firefox 54, (soon Edge)
> Fix cookie handling (all browsers) and polyfill fetch() in Edge

- lib/core/metadata/index.js
- lib/core/metadata/packageInfo.js
- lib/templates/settingsConsole.mustache
> Show git description of HEAD on version hover

- lib/modules/accountSwitcher.js
- locales/locales/en.json
- tests/accountSwitcher.js
Relevant issue: fixes #4063
Tested in browser: chrome 59
> Improve account switcher error reporting

- lib/utils/string.js
> Fix templates on Edge

- lib/modules/showImages.js
> showImages: drag improvements

- locales/locales/en.json
> fixes #4170

- lib/utils/createElement.js
> createElement.toggleButton: Templatify

- lib/core/migrate/migrate.js
- lib/modules/onboarding.js
...in anticipation of a (more) rapid release cadence.
> Migrate minor release notifier to notifications

- lib/modules/RESTips.js
- lib/modules/filteReddit.js
FeatureTips are now seamlessly included with dailyTips / tips & tricks.
Tested in Chrome 58
> Improve featureTip—dailyTips integration 

- lib/modules/tableTools.js
These look harmless to me (and pass the current tests).
> tableTools: Convert to an arrow function

- tests/i18n.js
- tests/showImages.js
It seems to have a really hard time loading each successive page for some reason, so try breaking it up.
And show images button seems to have trouble ref #4213
> break up i18n test into multiple test cases, fix show images button test

- lib/environment/pageAction.js
- lib/modules/styleTweaks.js
Relevant issue: https://www.reddit.com/r/RESissues/comments/69n6ub/subreddit_css_toolbar_button_cant_be_properly/
Tested in browser: Firefox 54
> Fix subreddit style pageAction spuriously appearing

- lib/modules/pageNavigator.js
- lib/modules/showImages/templates.js
- lib/modules/submitIssue.js
- lib/utils/createElement.js
- tests/showImages.js
Relevant issue: fixes #4210
Tested in browser: Chrome 60, integration tests
> Fix images opening in a new tab on click

- lib/modules/backupAndRestore.js
> backup and restore: use setMultiple

- lib/environment/history.js
- lib/environment/privateBrowsing.js
- lib/modules/newCommentCount.js
- lib/modules/showImages.js
- lib/modules/subredditManager.js
- lib/modules/troubleshooter.js
Noticed this could be sync during #4228.
Trivial refactoring so not worth delaying to 5.7.0
> Make isPrivateBrowsing synchronous

- lib/modules/hosts/aarli.js
> aar.li host

- lib/modules/spamButton.js
- tests/spamButton.js
Update spam button to send modmails to /r/reddit.com
https://www.reddit.com/r/modnews/comments/6bj5de/state_of_spam/
> Spam button update

- lib/modules/subredditManager.js
- lib/utils/Thing.js
- locales/locales/en.json
Adds r/profileposts link to subreddit manager (to match reddit update)
Fixes getting subreddit from profile post (for filtering purposes)
> Profile Posts support

- chrome/beta/manifest.json
- chrome/manifest.json
- edge/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
- package.json
> Make author and options manifest keys as consistent as possible across browsers

- lib/core/options/index.js
- lib/core/options/options.js
- lib/modules/commentTools.js
- lib/modules/submitIssue.js
- lib/utils/location.js
Only shows modules that have been modified in some way, but ignores certain options like arrays, builders, and lists in order to avoid sensitive and mostly unimportant information.
Macros are available  only for /r/RESissues` and /r/Enhancement, and inserts it in a format like this:
```
RESTips              
dailyTip                    	true → false
accountSwitcher      
betteReddit          
commentsLinksNewTabs        	false → true
hideLinkInstant             	false → true
scoreHiddenTimeLeft         	true → false
commentCollapseInInbox      	false → true
commentQuickCollapse 
scrollOnCollapse            	false → true
commentStyle         
continuity                  	false → true
commentTools         
filteReddit          
filterSubredditsFrom        	"everywhere-except-subreddit" → …
```
> Macro for displaying changed settings

- lib/modules/hosts/streamable.js
To support links like these:
* https://streamable.com/s/b416n
* https://streamable.com/s/b416n/zxmwtq
> Update streamable pathname regex

- browser/background.js
- chrome/background.entry.js
- chrome/beta/manifest.json
- chrome/manifest.json
- edge/authResponder.entry.js
- edge/background.entry.js
- edge/manifest.json
- firefox/background.entry.js
- firefox/beta/manifest.json
- firefox/manifest.json
- lib/environment/auth.js
> Use launchWebAuthFlow to get OAuth tokens

- browser/background.js
- chrome/background.entry.js
- edge/authResponder.entry.js
- edge/background.entry.js
- edge/manifest.json
- firefox/background.entry.js
- package.json
- yarn.lock
Relevant issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4269#issuecomment-305792831
> OAuth: redirect to res.com for interactive auth in all browsers

- chrome/beta/manifest.json
- chrome/chrome.entry.js
- chrome/manifest.json
- flow/lib/dom.js
- lib/environment/ajax.js
- lib/modules/commentDepth.js
- lib/modules/hosts/pixiv.js
- lib/modules/hosts/raddit.js
- lib/modules/hosts/redditmedia.js
- lib/modules/hosts/steamcommunity.js
- lib/modules/hosts/youtube.js
- lib/modules/quickMessage.js
- lib/modules/showImages.js
- lib/utils/__tests__/generator.js
- lib/utils/__tests__/location.js
- lib/utils/generator.js
- lib/utils/index.js
- lib/utils/location.js
- tests/commentQuickCollapse.js
> Use native URLSearchParams instead of custom parsing

- browser/background.js
- lib/environment/multicast.js
- lib/modules/backupAndRestore.js
- lib/modules/backupAndRestore/providers/GoogleDrive.js
- lib/modules/backupAndRestore/providers/Provider.js
- lib/modules/nightMode.js
- locales/locales/en.json
- package.json
- yarn.lock
> Automatic backups

- lib/modules/commentPreview.js
Fixes https://www.reddit.com/r/RESissues/comments/6f6q42/res_big_editor_shortcut_is_broken_deletes_posts/
https://www.reddit.com/r/Enhancement/comments/5nssy5/not_sure_if_bug_or_not_i_just_typed_a_nice_long/
Tested in browser: Chrome 59
> Fix bigEditor not submitting when opened by keyboard shortcut

- lib/modules/subredditManager.js
- lib/utils/index.js
- lib/utils/localization.js
Show relative time of last visit to subreddit by default. On hover display actual date of visit.
Relevant issue: Fixes #4254 
Tested in browser: Chrome 59, Firefox 54
> SubredditManager: relative time for "last visited"

- lib/css/modules/_showImages.scss
- lib/modules/showImages.js
Centers the text properly, and restores the margin when appended to images, text etc.
> showImages siteAttribution: Fix style

- .travis.yml
- appveyor.yml
Might have slightly better performance, as usual.
> Update CI to Node 8

- lib/modules/filteReddit/postCases.js
- lib/utils/Thing.js
Relevant issue: fixes #4271 
Tested in browser: Chrome 59
> Add option to filter locked posts

- edge/manifest.json
- lib/modules/backupAndRestore/providers/OneDrive.js
- lib/modules/backupAndRestore/providers/index.js
> Backup to OneDrive

- edge/manifest.json
- lib/modules/backupAndRestore/providers/Dropbox.js
- lib/modules/backupAndRestore/providers/index.js
> Backup to Dropbox

- lib/modules/backupAndRestore.js
- locales/locales/en.json
Relevant issue: https://www.reddit.com/message/messages/8ji170 (only works for me)
Tested in browser: Chrome 60, Firefox 53
Mainly to fix [read: reduce] two races related to the backup/restore decision.
This should work well enough, though we might still do some redundant work. If there are more issues I'll make a proper lock.
> Backup tweaks

- lib/environment/auth.js
- lib/environment/permissions.js
- lib/modules/backupAndRestore/providers/Dropbox.js
- lib/modules/backupAndRestore/providers/GoogleDrive.js
- lib/modules/backupAndRestore/providers/OneDrive.js
- lib/modules/notifications.js
- lib/modules/showImages.js
> Move expando perms notifications to showImages, show alert before asking for backup perms

- lib/modules/stylesheet.js
Relevant issue: fixes #4302
It'll be cached for the entire session, which should be long enough, given that this is an opt-in feature (if the concern is load on reddit).
> stylesheet: load and cache from wiki page

- lib/modules/hover.js
- lib/modules/keyboardNav.js
- lib/modules/showParent.js
- lib/modules/subredditInfo.js
- lib/modules/userInfo.js
Allows for easier customization of infocards.
From #4191
> hover: Change `populate` signature, keep visible on focus

- lib/core/module.js
- lib/modules/accountSwitcher.js
- lib/modules/contribute.js
- lib/modules/menu.js
- lib/modules/noParticipation.js
- lib/modules/saveComments.js
- lib/modules/search.js
- lib/modules/settingsConsole.js
- lib/modules/settingsConsole/templates.js
- lib/modules/styleTweaks.js
- lib/modules/submitIssue.js
- lib/modules/troubleshooter.js
- lib/modules/userTagger.js
- locales/locales/en.json
> Allow markdown for module descriptions

- lib/modules/filteReddit/postCases.js
Relevant issue: fixes #3571
Tested in browser: Chrome 59.0.3071.104 (Official Build) (64-bit)
> Check for visited class in visited filter (#3571)

- lib/modules/showImages.js
- lib/modules/showImages/expando.js
From #4191 
Tested in: Chrome 60
> showImages cleanup

- lib/modules/hover.js
> hover infocard positioning cleanup

- lib/css/modules/_nightMode.scss
- lib/css/res.scss
- lib/modules/settingsConsole.js
Changes made in order to allow easier insertion of its components to other contexts, such as infocards.
From #4191 
Tested in browser: Chrome 61, Firefox 55
> settingsConsole builder: Style cleanup

- lib/modules/hosts/pornhub.js
Tested in browser: Chrome 59
This will add support for Pornhub embed player :)
> Add Pornhub embed player support

- lib/modules/hosts/supgif.js
Hey there,
Added host file supgif.com domain which plays an iframe.
Is there a specific protocol for adding hosts?
Thanks!
> Add host file for supgif.com

- lib/modules/searchHelper.js
> searchByFlair: use Thing to avoid getting fooled by xpostlinks

- lib/modules/settingsConsole.js
> Open module settings by cli `mod xyz`

- lib/modules/styleTweaks.js
- locales/locales/en.json
Relevant issue: fixes #2577, affects #4262
> Option to disable subreddit style checkbox

- lib/modules/newCommentCount.js
Attempts to fix https://www.reddit.com/r/RESissues/comments/6nly3t/constant_color_wheel_after_580_update/ by running `checkSubscriptions` at most once every 5 minutes.
> Reduce newCommentCount slowdown

- lib/css/modules/_nightMode.scss
Fixes  #4361
Tested in Chrome and Firefox
I assumed that CSS mixin for the z-index are accepted by this project.
> Fixing styling issues in Night Mode w/ new profiles #4361

- lib/css/modules/_nightMode.scss
Fixes #4360 
Tested in Chrome & Firefox
>  Fixing styling issues in Night Mode w/ reporting

- lib/modules/hover.js
- lib/modules/subredditInfo.js
- lib/modules/userInfo.js
> No jQuery in HoverContents or hover target

- .travis.yml
> travis: Specify exact version of Yarn to use

- lib/css/res.scss
Fixes #4380
This probably isn't the best solution but i think its best to come back to this when the redesign has been completed.
> Move video pin close button to prevent interference with RES floater

- lib/modules/userInfo.js
> Fix ignore button showing up on userInfo bubble when no userTagger is disabled

- lib/css/modules/_nightMode.scss
> Nightmode support for 2FA

- lib/core/host.js
- lib/modules/showImages.js
> Remove go() prop from Host

- lib/css/modules/_nightMode.scss
> Nightmode support for enabling 2FA & tweaks

- lib/css/modules/_nightMode.scss
Fixes a few nightmode issues on http://reddit.com/users/
> /users nightmode fixes

- lib/css/modules/_nightMode.scss
https://www.reddit.com/r/changelog/comments/6yqqri/testing_out_user_hover_cards/
> Nightmode support for new user hover cards

- lib/css/modules/_nightMode.scss
Previous PR no longer works due to changes to page, this cleans it up a bit so you dont blind yourself.
It will probably only work until the next change.
> New profile pages nightmode fixes

- lib/css/modules/_nightMode.scss
https://www.reddit.com/live/x3ckzbsj6myw/updates/7fc904fe-9413-11e7-af1c-0e8b9a276cbe
The close button is a bit iffy as its shared across multiple modal boxes.
> Add nightmode support to new signup flow

- lib/modules/subredditManager.js
- locales/locales/en.json
> Show users in subreddit manager bar.

- lib/css/modules/_nightMode.scss
- tests/subredditInfo.js
https://www.reddit.com/r/beta/comments/704gl3/profiles_update_overview_page_bug_fixes_and_other/
> Support new profile page in nightmode.

- lib/css/modules/_redditUserInfo.scss
- lib/css/res.scss
- lib/modules/redditUserInfo.js
- locales/locales/en.json
As a temporary solution until #4417 is completed.
> Module to hide the new reddit hovercards

- changelog/UNRELEASED.md
> 5.8.5 changelog

- lib/modules/RESTips.js
- lib/modules/contribute.js
- lib/modules/dashboard.js
- lib/modules/menu.js
- lib/modules/nightMode.js
- lib/modules/search.js
- lib/modules/settingsConsole.js
- lib/modules/settingsConsole/templates.js
- locales/locales/en.json
> Implement i18n in RES gear menu and some top-level interface items

- .travis.yml
https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/
> Remove manual Yarn updating now that it's baked into the image

- edge/appxmanifest.xml
Update for creators fall update. Release includes multiple browser fixes which was reported by the RES team.
> Update min supported version for edge

- browser/background.js
- lib/utils/alert.js
Relevant issue: closes #3919
Tested in browser: Edge 16
> Revert workaround for Chakra arrow function bug

- lib/core/module.js
- lib/css/modules/_keyboardNav.scss
- lib/modules/keyboardNav.js
- lib/modules/neverEndingReddit.js
- lib/modules/selectedEntry.js
Reduces the amount of complexity needed in the callbacks.
> KeyboardNav: Callback simplification and error logging

- lib/css/res.scss
- lib/modules/notifications.js
- lib/modules/profileRedirect.js
- lib/utils/__tests__/location.js
- lib/utils/location.js
- locales/locales/en.json
Redirect from landing page to legacy overview, comments, etc. or custom section
>  Add Profile Redirect module and desktop2x fix-upx

- lib/modules/styleTweaks.js
- lib/modules/stylesheet.js
Relevant issue: fixes issue #1680
> add no-subreddit-style class to body on pages without srstyle

- lib/core/migrate/migrate.js
- lib/modules/hosts/imgur.js
> remove spaces from imgur 'prefer RES albums' option key

- lib/utils/watchers.js
Replies to such comments wasn't processed.
Fixes regression from #3644.
Tested in browser: Chrome 63
> Fix watching of comments without replies

- chrome/background.entry.js
- edge/background.entry.js
- firefox/background.entry.js
- firefox/beta/manifest.json
- firefox/manifest.json
- lib/environment/auth.js
- lib/modules/backupAndRestore.js
- lib/modules/backupAndRestore/providers/Dropbox.js
- lib/modules/backupAndRestore/providers/GoogleDrive.js
- lib/modules/backupAndRestore/providers/OneDrive.js
- lib/modules/backupAndRestore/providers/Provider.js
Reverts honestbleeps/Reddit-Enhancement-Suite#4440
We can't add new permissions in Firefox without causing a warning dialog (until #4471), as we're not going through this shitstorm again
> Revert "Google Drive backup provider: Remember which account to use if there are multiple Google accounts logged in"

- lib/modules/showImages.js
- lib/utils/Thing.js
- lib/utils/string.js
- package.json
- yarn.lock
Fixes issue #3561 using fast-levenshtein. Tested in Chrome.
> Don't add post expando title if it matches the post

- lib/modules/backupAndRestore.js
- lib/modules/backupAndRestore/providers/Dropbox.js
- lib/modules/backupAndRestore/providers/GoogleDrive.js
- lib/modules/backupAndRestore/providers/OneDrive.js
- lib/modules/backupAndRestore/providers/Provider.js
- locales/locales/en.json
Relevant issue: closes #4376, re #4440 and #4489
> Add googleAccount option to backupAndRestore

- CONTRIBUTING.md
Just substituting the word 'choose' for the word 'chosen' so it makes a little more sense
> Fixing grammatical error in contributing.md

- tests/showImages.js
Since moving to 5.9.0, a new tab appears for installing/updating the beta.
> fix integration tests

- lib/modules/userTagger.js
related to PR #4480 @larsjohnsen
> Fix selected color in userTagger dialog

- lib/modules/announcements.js
- locales/locales/en.json
> add i18n to announcements.js

- lib/css/modules/_commentNavigator.scss
- lib/css/modules/_wheelBrowse.scss
- lib/modules/commentNavigator.js
- lib/modules/keyboardNav.js
- lib/modules/userInfo.js
- lib/modules/wheelBrowse.js
- tests/commentNavigator.js
- Shows the number of matches for each category.
- Fixes AMA mode when a comment has multiple replies by submitter.
- When opening the box with keyboard shortcut, it is properly focused.
- Adds a wheelBrowse widget on comment pages. When used, it opens the the box which can be used to specify what category to browse. Clicking it hides the box.
- Makes the box significantly smaller.
Closes #1602
Tested in browser: Chrome 63
> commentNav: Cleanup & integration with wheelBrowse

- lib/modules/neverEndingReddit.js
Minor clean-up.
Tested in browser: Chrome 63
> ner duplicate handling: utilize watchForElements

- lib/modules/subredditManager.js
- locales/locales/en.json
- package.json
Hello,
Add a quick-filter box to the top of the "my subreddits list", that allows people to quickly filter down their subreddit list to find the sub they are looking for.
Mostly inspired by how often i end up having to use the browsers built in search to find what i'm looking for in my subreddit list.
Have also added it to settings so that users can disable it if they don't like it there.
resolves https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1748
> Add quick-filter to my subreddits list

- lib/modules/hosts/googlemaps.js
First pass at a google maps media host. Has basic support for both new and old google maps url structures.
Not entirely sure how to handle the fact google potentially use 100's of TLD's in their domains. For now i've just supported what appear to be the most common.
fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2042
> Google maps media host

- lib/modules/userTagger.js
Relevant issue: resolves #2081
Tested in browser: Firefox, Chrome
Basically maps `tagData` again without the filter for 'tagged users' and updates the `#tagFilter` dropdown to 'all users'
> Show all users if there are no tagged users in UserTagger

- lib/css/modules/_commentNavigator.scss
- lib/modules/commentNavigator.js
> commentNav tweaks

- lib/modules/saveComments.js
> saveComments: Clean-up, faster button generation

- lib/css/modules/_commentQuickCollapse.scss
- lib/modules/selectedEntry.js
- lib/modules/showParent.js
Fixes issue where subreddit style / nightmode classic etc overrides option to not style selected entry in any way.
Tested in browser: Firefox 56, Chrome 63
> selectedEntry: Replace selected class with attribute res-selected

- lib/modules/dashboard.js
> dashboard: Ignore invalid widgets

- lib/css/modules/_commentNavigator.scss
- lib/modules/commentNavigator.js
> commentNav fixes

- lib/modules/filteReddit/postCases.js
- lib/utils/Thing.js
Adding a new filter for posts that I have upvoted/downvoted/unvoted.
Relevant issue: closes #2701 , #4072 
> A filter for upvote/downvote/unvote

- lib/modules/commentTools.js
- lib/modules/userTagger.js
>  Fix commentTool userTagger application

- lib/utils/watchers.js
> Fix newSitetable sort

- lib/css/modules/_nightMode.scss
> Fix quote box colouring on new profile page nightmode

- lib/utils/dom.js
- lib/utils/index.js
- lib/utils/watchers.js
Relevant issue: re https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4519/files#r148139027
~~Currently breaks things.~~
> waitForDescendant and other MutationObserver utils

- lib/css/modules/_styleTweaks.scss
- lib/modules/styleTweaks.js
- locales/locales/en.json
Relevant issue:  fixes #4444 
Tested in browser: Firefox 58, Chrome 61
> Added styletweak that hides domain link in the title of posts.

- lib/css/modules/_commentQuickCollapse.scss
- lib/modules/selectedEntry.js
Using attribute causes a style recalculation on comment pages, though I don't know why that's the case.
> selectedEntry: Use class instead of attribute

- browser/options.html
- lib/utils/__tests__/escapeHTML.js
- lib/utils/location.js
The `escapeHTML.js` change isn't really necessary, but might as well update the URL.
> Remove last remnants of HTTP Reddit URLs

- lib/modules/sourceSnudown.js
- tests/sourceSnudown.js
> Fix source button appearing before NSFW/spoiler badge

- lib/environment/i18n.js
There's [been](https://www.reddit.com/r/RESissues/comments/6a8oy6/res_suddenly_stopped_working/) [some](https://www.reddit.com/r/RESissues/comments/6pkhiu/bug_res_dashboard_not_working_with_chrome/) [reports](https://www.reddit.com/r/RESissues/comments/6owj24/res_no_longer_working_my_subreddits_drop_down_not/) where RES fails to start because of this.
The issue appears to originate from Reddit, and seemingly also breaks some Reddit functionality like voting.
> i18n localStorage: Contain error when storage quota exceeded

- lib/css/modules/_temporaryDropdownLinks.scss
- lib/css/res.scss
- lib/modules/temporaryDropdownLinks.js
- locales/locales/en.json
- tests/temporaryDropdownLinks.js
> Resurrect #1566: updated sortCommentsTemporarily module

- lib/modules/commentPreview.js
> Fix title character count being null

- .eslintrc.json
- edge/edge.entry.js
- lib/core/migrate/migrate.js
- lib/core/modules/modules.js
- lib/core/options/options.js
- lib/modules/backupAndRestore.js
- lib/modules/commentHidePersistor.js
- lib/modules/commentPreview.js
- lib/modules/commentTools.js
- lib/modules/customToggles.js
- lib/modules/newCommentCount.js
- lib/modules/settingsConsole.js
- lib/modules/showImages.js
- lib/modules/subredditManager.js
- lib/modules/subredditTagger.js
- lib/utils/async.js
- lib/utils/object.js
- lib/utils/string.js
The changes should be pretty minor.
> eslint: Enable guard-for-in, new-cap, disallow `in`

- lib/modules/orangered.js
> Select from (new) favicons

- webpack.config.babel.js
This should make the build a bit leaner and faster.
> webpack: Enable scope hoisting

- lib/css/modules/_nightMode.scss
> Fix nightmode styling on API docs

- lib/modules/betteReddit.js
- lib/utils/index.js
- lib/utils/time.js
Resolves #1766
Relevant issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1766
> Add YouTube continue time (t=?) to link title

- lib/modules/selectedEntry.js
> selectedEntry: Fix forced reflow when selecting

- lib/modules/filteReddit/commentCases/CommentContent.js
- lib/modules/filteReddit/postCases/Domain.js
- lib/modules/filteReddit/postCases/LinkFlair.js
- lib/modules/filteReddit/postCases/PostTitle.js
- lib/modules/filteReddit/postCases/UserFlair.js
- lib/modules/filteReddit/postCases/Username.js
As noted [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4191#issuecomment-355762712).
Tested in browser:  Chrome 64
> Filterline: Don't display simple strings as RegExps

- lib/css/modules/_filteReddit.scss
- lib/modules/selectedEntry.js
- lib/utils/dom.js
Seems to restore the performance to previous level.
Relevant issue: Closes #4609
Tested in browser: Chrome 64, Edge 16
> Improve comment selection performance

- .travis.yml
- build/deployChangelog.js
- build/utils/changelog.js
- build/version.js
- package.json
https://github.com/Reddit-Enhancement-Suite/Reddit-Enhancement-Suite.github.io/commit/c9f25109ddd03efea32aea16b52dcf4d971a62ac
> Automate changelog post deployment

- lib/modules/userTagger.js
> userTagger text input: Position cursor at the end

- lib/modules/selectedEntry.js
Restores CSS override for some custom subreddit styles.
> Fix typos in selectedEntry styles

- lib/modules/userTagger.js
Fixes https://www.reddit.com/r/Enhancement/comments/7pmdm6/another_user_tagging_bug_cant_see_tags_for_myself/
> Display tag text for own user

- lib/css/modules/_filteReddit.scss
> Filterline: Use Batch for powered icon

- lib/modules/settingsConsole.js
Should be fairly straightforward.
> settingsConsole: Make minor cleanup changes

- lib/modules/filteReddit.js
> filteReddit: Ignore invalid entries in filter lists

- lib/modules/commentPreview.js
> live preview: restore sidebarPreview functionality

- lib/modules/keyboardNav.js
Relevant issue: https://www.reddit.com/r/Enhancement/comments/7ravhp/keyboard_navigation_auto_xpando_on_j_after_h/
Tested in browser:  Chrome 64
> Fix mediaBrowse not working when hiding posts

- lib/modules/userTagger.js
Relevant issue: https://www.reddit.com/r/Enhancement/comments/7rkazl/user_tags_in_white/
> userTagger: add color to tags with 'none' color

- lib/modules/commandLine.js
Relevant issue: https://www.reddit.com/r/Enhancement/comments/7rpqhq/is_there_a_way_to_quickly_change_the_sort_top/
> CLI: Add 'period' parameter to sort by command

- lib/modules/hideChildComments.js
Relevant issue: https://www.reddit.com/r/Enhancement/comments/7s0txi/when_i_try_to_hide_all_the_child_comments_it_only/
> hideChildComments: Fix state on posts loaded after toggling all

- CONTRIBUTING.md
> Update contrib docs to include IRC details.

- build/deploy.js
> Remove firefox beta deployment

- lib/modules/betteReddit.js
- lib/modules/commentPreview.js
- lib/modules/commentStyle.js
- lib/modules/neverEndingReddit.js
- lib/modules/nightMode.js
- lib/modules/userTagger.js
- lib/modules/xPostLinks.js
- lib/types/events.js
- lib/utils/index.js
- lib/utils/location.js
- lib/utils/watchers.js
> RedditV4/d2x: basic framework support, show user tags as PoC

- chrome/beta/manifest.json
- chrome/manifest.json
- lib/environment/background/download.js
- lib/environment/foreground/download.js
- lib/modules/showImages.js
Relevant issue: fixes #4701
Tested in browser: Chrome 66, Firefox 58
> Dynamically request downloads permission in chrome

- lib/modules/logoLink.js
- locales/locales/en.json
Resolves #4710
Tested on: Chrome 65
> Add /hot to logoLink

- lib/constants/jsapi.js
- lib/utils/watchers.js
> Use named JSAPI containers

- lib/modules/showImages.js
> showImages: Fix collapsing comment not collapsing expando

- lib/css/modules/_floater.scss
- lib/modules/accountSwitcher.js
- lib/modules/floater.js
- lib/modules/menu.js
- lib/utils/dom.js
- lib/utils/index.js
This diff looks much better with [whitespace changes hidden](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4729/files?w=1).
> Add account switcher and gear menu UI to redesign

- lib/modules/commandLine.js
Adds a command to take the user to the reddit front page via the RES commandline
> Add front command

- lib/core/module.js
- lib/modules/settingsConsole.js
- lib/modules/stylesheet.js
> stylesheets customToggle: Rename and use select instead of enum

- lib/modules/userTagger.js
- lib/types/events.js
- lib/utils/watchers.js
- tests/userTagger.js
Bonus: store latest version of event data on the element itself.
> Add only one usertagger to post author, comment author, hovercard

- tests/Filterline.js
- tests/RESTips.js
- tests/accountSwitcher.js
- tests/commentDepth.js
- tests/commentNavigator.js
- tests/commentQuickCollapse.js
- tests/commentTools.js
- tests/filteReddit.js
- tests/hideChildComments.js
- tests/i18n.js
- tests/keyboardNav.js
- tests/menu.js
- tests/notifications.js
- tests/pageNavigator.js
- tests/readComments.js
- tests/saveComments.js
- tests/selectedEntry.js
- tests/settingsConsole.js
- tests/showImages.js
- tests/sourceSnudown.js
- tests/spamButton.js
- tests/userHighlight.js
- tests/userTagger.js
- tests/voteEnhancements.js
- tests/xPostLinks.js
Avoid getting bucketed into new.reddit.com
> Explicitly run tests on en.reddit.com

- lib/modules/nightMode.js
- tests/presets.js
Relevant issue: https://www.reddit.com/r/RESissues/comments/8gn4vl/presets_not_working/
> Fix cleanSlate preset

- chrome/beta/manifest.json
- chrome/manifest.json
- edge/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
Not much for RES to do here yet.
> Disable RES on /chat

- lib/modules/userTagger.js
Relevant issue: https://www.reddit.com/r/Enhancement/comments/8gyl1s/when_you_delete_the_text_from_a_user_tag_a_small/
> Usertagger fixes

- lib/modules/subredditInfo.js
Added the new CSS selector for subreddit links on the front page of the new re-design
> Module "Subreddit Info" working for new re-design

- lib/modules/neverEndingReddit.js
Makes the `loadNextPage` process faster, more in line with Reddit's implementation.
>  ner: Prefetch next page when when approaching bottom

- lib/utils/watchers.js
1. Upgrade "JSAPI consumer ready" to `<meta name="jsapi.consumer" />`
2. Accommodate Firefox's tendencies toward being more technically correct
> Firefox JSAPI fixes

- edge/manifest.json
- package.json
> Remove Edge URLSearchParams polyfill

- lib/modules/filteReddit.js
- lib/modules/filteReddit/Case.js
- lib/modules/filteReddit/ExternalFilter.js
- lib/modules/filteReddit/Filter.js
- lib/modules/filteReddit/Filterline.js
- lib/modules/filteReddit/LineFilter.js
- lib/modules/filteReddit/cases.js
- lib/modules/filteReddit/postCases/Expando.js
- lib/utils/Thing.js
>  Filterline: Some cleanup

- lib/modules/hosts/gfycat.js
> Remove gfycat reverse

- lib/css/modules/_filteReddit.scss
- lib/modules/filteReddit.js
- lib/modules/filteReddit/Filter.js
- lib/modules/filteReddit/Filterline.js
- lib/modules/filteReddit/LineFilter.js
> filteReddit: Side-effects and option to hide children of matched comments

- lib/css/modules/_accountSwitcher.scss
- lib/modules/accountSwitcher.js
- lib/modules/betteReddit.js
- lib/modules/hover.js
- lib/modules/userbarHider.js
- tests/accountSwitcher.js
Dependent on #4782 
Tested in browser: Chrome 61, Firefox 62
> accountSwitcher: Use Hover module to display accountMenu

- lib/modules/filteReddit/postCases/NewCommentCount.js
> Filter newCommentCount: Allow concurrent filters, tweak text

- lib/modules/dashboard.js
Not 100% sure how the string interpolation works but I think this is correct.
> dashboard: Fix bug mentioned in 37d5e38e's comments

- lib/core/module.js
- lib/css/modules/_commandLine.scss
- lib/modules/commandLine.js
- lib/modules/keyboardNav.js
- lib/modules/menu.js
Relevant issue: https://www.reddit.com/r/RESissues/comments/941l0n/issue_closing_filter_dialog/
> commandLine: Close on Escape also when blurred

- changelog/v5.12.6.md
3b8bb2cf4bcf2ec2d224520eb5a37fd51cce038f
https://github.com/honestbleeps/Reddit-Enhancement-Suite/releases/v5.12.6
Drop changes to package.json
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4861
> 5.12.6 (cherry-pick)

- lib/css/modules/_userbarHider.scss
- lib/modules/userbarHider.js
This should resolve #3128. This is my first contribution to this project so I'd welcome any input. 
Relevant issue: #3128 
Tested in browser: firefox 62.0.3, chrome 69.0.3497.100
> Userbar hider bodyclass toggle

- lib/css/modules/_commentNavigator.scss
- lib/css/modules/_nightMode.scss
- lib/modules/selectedEntry.js
- lib/modules/showParent.js
- lib/modules/userInfo.js
Tested in browser: Chrome 70, Firefox 62
> Minor fixes

- lib/core/init.js
- lib/modules/neverEndingReddit.js
- lib/utils/index.js
- lib/utils/watchers.js
Tested in browser:  Chrome 70, Firefox 62
> Fix neverEndingReddit returnToPrev issue on Firefox

- lib/modules/pageNavigator.js
Appears that Reddit sometimes inserts ads along with the submission on comment pages.
https://www.reddit.com/r/Enhancement/comments/9nha5n/why_am_i_getting_an_ad_in_the_page_navigator/
Tested in browser: Firefox 63
> pageNavigator showLink: Fix ad sometimes being shown instead of submission

- lib/modules/filteReddit/Case.js
- lib/modules/filteReddit/Filter.js
- lib/modules/filteReddit/browseCases/Date.js
- lib/modules/filteReddit/commentCases/CommentContent.js
- lib/modules/filteReddit/commentCases/CommentLength.js
- lib/modules/filteReddit/commentCases/Depth.js
- lib/modules/filteReddit/postCases/CommentCount.js
- lib/modules/filteReddit/postCases/CommentsOpened.js
- lib/modules/filteReddit/postCases/Domain.js
- lib/modules/filteReddit/postCases/IsVisited.js
- lib/modules/filteReddit/postCases/NewCommentCount.js
- lib/modules/filteReddit/postCases/PostAfter.js
- lib/modules/filteReddit/postCases/PostAge.js
- lib/modules/filteReddit/postCases/PostType.js
- lib/modules/filteReddit/postCases/Score.js
- lib/modules/filteReddit/postCases/Subreddit.js
- lib/modules/filteReddit/postCases/UserAttr.js
- lib/modules/filteReddit/postCases/UserVoteWeight.js
- lib/modules/filteReddit/postCases/Username.js
- lib/modules/filteReddit/postCases/VoteType.js
The previous way only worked when filters where set to state `false`, i.e. hiding posts.
Relevant issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4768#discussion_r212934405
> filteReddit: Don't hide posts when not able to ascertain data

- lib/modules/betteReddit.js
- lib/modules/dashboard.js
- lib/modules/neverEndingReddit.js
- lib/modules/showImages.js
- lib/modules/subredditTagger.js
Tested in browser: Firefox 64, Chrome 71
> Minor optimizations

- lib/modules/commentSortBy.js
- lib/modules/userTagger.js
- lib/types/events.js
- lib/utils/watchers.js
- locales/locales/en.json
Relevant issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2697
Tested in browser:  Google Chrome 70.0.3538.77
> Adds quick link to comment sort-by preference menu

- lib/modules/hosts/gfycat.js
Relevant issue:  Fixes #4978 
Tested in browser:  Firefox 63
> gfycat: Update endpoint

- tests/showImages.js
> Fix test showImages: generic expando

- chrome/beta/manifest.json
- chrome/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
`Element#toggleAttribute` requires Chrome > 68.
> Bump required browser versions

- package.json
- yarn.lock
Relevant issue: NA
Tested in browser: NA
Based on suggestion here: https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4976#discussion_r242148344
> Fixed dependency's version in package.json

- lib/modules/hosts/gfycat.js
https://www.reddit.com/r/Enhancement/comments/a8ij8d/gfycats_now_have_a_sound_option/
> hosts gfycat: Add support for non-muted videos

- lib/modules/showImages.js
Tested in browser: Firefox 65, Chrome 71
> showImages: Optimize modulesForHostname

- lib/modules/hideChildComments.js
- locales/locales/en.json
Fixes #4882.
Tested in Firefox and Chrome.
First contribution, let me know if anything can be improved!
> Localize show/hide child comment buttons

- lib/modules/orangered.js
> legacyFavicon: Make independent of option showUnreadCountInFavicon

- lib/modules/searchHelper.js
- locales/locales/en.json
Clean and simple.
Relevant issue: #4725
> Capability to set default sort and time options sidebar search

- lib/modules/quarantineHide.js
- lib/utils/location.js
- locales/locales/en.json
Add module to hide warnings for quarantined subreddits.
> Add quarantineHide module for hiding quarantine warnings

- lib/modules/dashboard.js
- locales/locales/en.json
- locales/locales/en@lolcat.json
- locales/locales/en@pirate.json
- locales/locales/en_CA.json
- locales/locales/en_GB.json
Tested in browser: Google Chrome Version 70.0.3538.67
This feature was overdue. There are a lot of old posts in /r/Enhancement asking for this feature, although I couldn't find any related GitHub issue.
Anyway, here it is. Let me know if something is wrong.
> Added sort feature to the search widget in dashboard

- examples/module.js
- lib/core/module.js
- lib/options/settingsConsole.js
> SettingsConsole now requests (optional) permissions on behalf of modules that need them

- lib/modules/announcements.js
> Add announcement biff (megaphone) to floater in redesign

- edge/appxmanifest.xml
- edge/generationInfo.json
> Fix edge validation issues.

- lib/modules/styleTweaks.js
Relevant issue: Fixes https://www.reddit.com/r/RESissues/comments/ah8d43/dark_mode_bugs_out_on_opening_threadssubs/
> Fix FOUC on some subreddits with nightmode enabled

- lib/options/settingsConsole.js
Improves speed on a heavily populated filteReddit page with about 1/3. Necessary since now also users filters are rendered on that page.
> Optimize settingsConsole

- lib/modules/filteReddit.js
- lib/modules/filteReddit/Case.js
- lib/modules/filteReddit/commentCases/CommentContent.js
- lib/modules/filteReddit/postCases/Domain.js
- lib/modules/filteReddit/postCases/LinkFlair.js
- lib/modules/filteReddit/postCases/PostTitle.js
- lib/modules/filteReddit/postCases/Subreddit.js
- lib/modules/filteReddit/postCases/UserFlair.js
- lib/modules/filteReddit/postCases/Username.js
- tests/filteReddit.js
The tests didn't invoke the reconcile code path, which contained the bug.
Tested in browser: Firefox 65, Chrome 72
> filteReddit: Fix partial match for flair / domain

- lib/core/migrate/migrate.js
- lib/core/options/options.js
- lib/modules/commentHidePersistor.js
- lib/modules/newCommentCount.js
- lib/modules/readComments.js
- lib/utils/index.js
- lib/utils/storage.js
Tested in browser: Firefox 65, Chrome 72
> Storage clean-up interface, prune preferences

- lib/utils/user.js
The first text node in the user button contains the username.
Tested in browser: Chrome 74
> Redesign: Implement loggedInUser

- .travis.yml
e.g. https://github.com/mozilla/build-tools/commit/c13a297
> Don't get notifications from fork build failures

- lib/modules/submitHelper.js
- lib/utils/index.js
- lib/utils/location.js
Relevant issue: fixes #4956
Tested in browser: Chrome 73, Firefox 65
> Make uncheckSendRepliesToInbox compatible with redesign

- lib/environment/background/storage.js
- lib/environment/foreground/storage.js
> Fix automatic backup check in Chrome

- .travis.yml
- package.json
Reverts honestbleeps/Reddit-Enhancement-Suite#4830
To test if it started working again.
> Revert "Temporarily disable FF integration tests"

- lib/css/modules/_nightMode.scss
Tested in browser: Edge Version 76.0.172.0
Fixes: https://www.reddit.com/comments/bvelql
> Fix nightmode on /report and tweaks to link.

- chrome/beta/manifest.json
- chrome/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
- lib/css/modules/_showImages.scss
- lib/modules/hosts/vreddit.js
- lib/modules/keyboardNav.js
- lib/modules/showImages.js
- lib/modules/showImages/expando.js
- lib/modules/showImages/templates.js
- locales/locales/en.json
- package.json
- tests/showImages.js
- yarn.lock
Tested in browser: Firefox 68, Chrome 77
> Showimages updates: Native ResizeObserver in Firefox, muted vreddit expandos

- lib/modules/subredditInfo.js
- lib/utils/index.js
- lib/utils/subreddits.js
This also hides the pop up if the subreddit is a fake subreddit like r/all//
*Before:*
*After*
Tested in browser: Chrome 73, Firefox 66
> Hide subredditInfo if no data

- lib/modules/submitHelper.js
Relevant issue: #4958
Added a function to focus the first textarea on the redesigned reddit.
My first PR for this repo! Let me know if I need to change anything about how I made this 😄
> Add focus function to submitHelper.js, fixes #4958

- lib/modules/hosts/peertube.js
addition to PR #5065 
note: I have not tested this change in a browser, because it is only a single line. If you want me to, I'll gladly test it.
> added peervideo.net to known peertube domains

- chrome/beta/manifest.json
- chrome/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
- lib/modules/backupAndRestore/providers/GoogleDrive.js
- yarn.lock
Relevant issue: Fixes #5180
Tested in browser: Chrome 82, Firefox 74
> Use new google drive api domain

- lib/css/modules/_nightMode.scss
Fixed nightmode issue on create a sub page on old reddit.
Tested in Edge 80. Thanks to CoolShot for report on Discord.
> Fix nightmode for create sub page.

- lib/css/modules/_showImages.scss
- lib/modules/hosts/liquipedia.js
Added Liquipedia.net hosts file and some scss for it. Based on existing Wikipedia hosts file using Mediawiki API. I have also confirmed with Liquipedia that this is acceptable use of the API.
> Liquipedia.net Host Support

- lib/modules/hosts/navertv.js
- lib/modules/hosts/vlive.js
Relevant issue: Similar to #5090, this is also used in Korea (kind of like the YouTube of Korea) - used commonly in kpop subreddits as seen here https://www.reddit.com/domain/tv.naver.com/ 
Tested in browser: Chrome 78.0.3904.108
> NaverTV host

- lib/css/modules/_showImages.scss
- lib/modules/hosts/liquipedia.js
Adding future-proof removal of elements using custom class. Added some recently added css for items which are commonly included in the included content. Follow up to #5176
> Liquipedia.net: Adding futureproof and some css changes

- lib/css/modules/_showImages.scss
> Remove liquipedia css.

- lib/modules/hosts/tuckbot.js
An iframe version will come soon (TM), however a direct embed will do the job for now
Tested in browser: Brave/Chrome
> Add basic tuckbot.tv support

- lib/modules/hosts/gamerdvr.js
> Add GamerDVR and update XboxDVR.

- lib/modules/hosts/twitchclips.js
Updates Twitchclips for new API.
Before: https://i.imgur.com/sEfOOKB.png
After: https://i.imgur.com/Xhutp1L.png
Tested on Edge 83.
@larsjohnsen How far do you think we are off stable build as theres a lot of issues being raised for this on /r/enhancement, resissues as well as my PMs. Are you able to join discord as well if you arent on it? https://discord.gg/UzkFNNa
> Update twitchclips for new API.

- lib/modules/hosts/redditgallery.js
- lib/modules/showImages.js
- lib/types/reddit.js
> showImages: Add support for Reddit image galleries

- lib/modules/hosts/redditpoll.js
Adds support for Reddit Poll on old reddit.
Tested on Edge 84.0.522.40.
On main feed:
In Post:
> Add Reddit Poll support

- lib/modules/accountSwitcher.js
Relevant issue: None
Tested in browser: Chrome 80
Added some hints for screen readers on the account switcher
> Added support for screen readers to the account switcher

- firefox/beta/manifest.json
- firefox/manifest.json
https://www.reddit.com/r/RESissues/comments/iy67g9/any_shortcut_meant_to_open_a_new_tab_or_tabs_does/g6nlz5k/?context=3
> Re-add cookie permission to Firefox

- CONTRIBUTING.md
Build parameter should be `browsers` not `browers`.
> Fixed Misspelled Parameter

- lib/modules/hosts/streamja.js
- lib/modules/hosts/streamwo.js
Relevant issue: https://www.reddit.com/r/Enhancement/comments/pr9ois/streamjacom_streamwocom_embed_request_for_rsoccer/
Tested in browser: Chrome 93 on Windows 10 Pro, Firefox 90 on Windows 10 Pro
> Add hosts for /r/soccer - streamja and streamwo

- .github/workflows/pipeline.yml
> First pipeline test

- lib/modules/announcements.js
> Fix announcement

- lib/modules/showImages/templates.js
> fix: minor code typo

- chrome/beta/manifest.json
- chrome/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
Enables RES to run on TOR.
Some features dont work as expected (Console cannot iFrame onpage and must new tab, however browser redirects and still works). Otherwise works fine from tests.
> Add Reddit Tor Support

- lib/modules/spamButton.js
/r/reddit.com was deprecated a year ago.
Relevant issue: #5294
Tested in browser: Firefox 90.0.1/99.0.1
> Use reddit.com/report for spam reports

- chrome/beta/manifest.json
- chrome/manifest.json
- firefox/beta/manifest.json
- firefox/manifest.json
> Remove tor support

- lib/modules/commentStyle.js
> Revert profile styling based on feedback.

- lib/utils/pagePhases.js
https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/921c6593a21d28d238c811af826a3eb434217639
> Revert change causing visual flash on DOM pageload.

- lib/modules/showImages.js
> Swap pinVideos to true based on feedback pending further work.

- lib/modules/showImages.js
> Revert pinVideo change

- lib/utils/watchers.js
> Add support for 10 character post IDs

- lib/modules/hosts/ireddit.js
- lib/modules/hosts/vreddit.js
- lib/types/reddit.js
Relevant issue: https://www.reddit.com/r/RESissues/comments/zqvuis/inline_image_viewer_missing_text/
Tested in browser: Google chrome 108.0.5359.125 (Official Build) (64-bit)
Not really a web dev so I may well have done something stupid here. This seems to bring in the Reddit selftext correctly and still looks right if there's no selftext. I'm using selftext_html which seems to double up on formatting, but includes anchors for links such as on the post in the issue.
Would appreciate any feedback on this but hopefully it's a clean fix.
> Include captions on i.redd.it and v.redd.it media

- chrome/beta/manifest.json
- chrome/manifest.json
> Remove un-needed perms

- firefox/beta/manifest.json
- firefox/manifest.json
- lib/environment/background/pageAction.js
Some APIs are backwards compat, these arent. Adding build time switch.
> Fix MV3 apis not in FF MV2 Compat + Firefox for Android prelim support

- firefox/beta/manifest.json
- firefox/manifest.json
> Move to browser_specific_settings for Firefox

- chrome/beta/manifest.json
- chrome/manifest.json
> Move hosts to optional permissions

- lib/environment/background/pageAction.js
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/5507
Tested in Firefox/Chrome.
> Rollback change to fix icon not switching

- lib/modules/subredditManager.js
Changes "may take a a few seconds" to "may take a few seconds", removing the repeated "a".
Relevant issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/5540
> Grammar fix  to remove repeated word in module subredditManager.js
